### PR TITLE
presentation "DevOps in SAP ABAP Landscapes"

### PR DESCRIPTION
**Pull request by JohannesKonings**
added presentation "DevOps in SAP ABAP Landscapes" which include abapGit

### CODE REVIEW

**Comment by larshp** [comment]
thanks 👍

**Comment by jfilak** [comment]
Cool, that's exactly "my" SAP landscape! Hooray, I am not alone!

**Comment by SaschaJunkert** [comment]
@jfilak: Nice to hear! Would you be open to discuss this in a skype session further? Your landscape (https://github.com/larshp/abapGit/issues/1574#issuecomment-405512867) sounds fantastic and very progressive! ;)

**Comment by jfilak** [comment]
@SaschaJunkert Sure, I always open for discussions :) What about Google Hangouts? My Fedora box does not play nice with Skype.

**Pull request merged**
