### PR TITLE
File format update collection

### PR DESCRIPTION
**Pull request by larshp**
Rebasing PR https://github.com/larshp/abapGit/pull/2586, issue https://github.com/larshp/abapGit/issues/2309

"
I removed the following fields:

CLAS
VSEOCLASS-VERSION

INTF
VSEOINTERF-VERSION

PROG
PROGDIR-STATE

DCLS
AS4LOCAL
ABAP_LANGUAGE_VERSION (if exists)

DDLS
ABAP_LANGUAGE_VERSION (if exists)

DDLX
VERSION
RESPONSIBLE
MASTER_SYSTEM

MSAG
DOKIL-DOKSTATE

ENQU
DD25V-AS4LOCAL
DD25V-AS4VERS
"

### CODE REVIEW

**Comment by larshp** [comment]
todo:
PROG VARCL
CLAS STATE
CLAS UNICODE

**Comment by larshp** [comment]
Test repos:
https://github.com/abapGit-tests/CLAS/pull/1

**Comment by jfilak** [comment]
DCLS + DDLX format has changed.
DDLS format is seems untouched.

**Comment by larshp** [comment]
thanks

**Pull request merged**
