### PR TITLE
Set filter for file open and save dialogs / Add new setting for default commit comment

### PR DESCRIPTION
**Pull request by mbtools**
Set the file filter dropdown and default to *.ZIP in file open and save dialogs

### CODE REVIEW

**Comment by mbtools** [comment]
(still an aG beginner... didn't means to combine those changes, sorry)

**Comment by mbtools** [comment]
Some screenshots of the new setting with $FILE:

image
image
image

or using $OBJECT

image
image
image

**Comment by larshp** [comment]
personally I think the predefined commit comment is an anti pattern, but its behind a user flag, so ok

**Comment by mbtools** [comment]
Thx for approving! It's a great simplifier esp. when you're the only one commiting to your own repos 👍

**Pull request merged**
