### PR TITLE
SHI3 serialization (user menu)

### PR DESCRIPTION
**Pull request by sbcgua**
Addressing #261 
Thanks for code examples of @sshlapak

### CODE REVIEW

**Comment by larshp** [comment]
thanks, looks good, there are 2 errors from abaplint, 

change
```abap
IF sy-subrc <> 0.
   _raise 'error from BMENU_DELETE_TREE, SHI3'.
ENDIF.
```
to
```abap
IF sy-subrc <> 0.
  _raise 'error from BMENU_DELETE_TREE, SHI3'.
ENDIF.
```
(remove 1 space)

**Comment by sbcgua** [comment]
yeap, fixed.

**Comment by larshp** [comment]
if you have time, can you add a SHI3 to repository https://github.com/larshp/abapGit-Unit-Test
?

it is used for the evil unit test in ZABAPGIT, trying to collect the different object types there for future testing

**Comment by sbcgua** [comment]
Unit test: hmm, you mean adding an object there ?

**Comment by larshp** [comment]
just add a zobject.shi3.xml to the repository(https://github.com/larshp/abapGit-Unit-Test), then it should automatically be tested via the ltcl_dangerous unit test in ZABAPGIT

**Comment by larshp** [comment]
thanks, I'll merge the PR :+1:

**Comment by sbcgua** [comment]
OK, I will but a bit later today :)

**Comment by larshp** [comment]
no hurry, it is just nice to have

**Comment by sbcgua** [comment]
added something (zabapgit_shi3_test.shi3.xml) ... hope it works :)

**Pull request merged**
