### PR TITLE
FUGR, clear RSFDO-INDEX

### PR DESCRIPTION
**Pull request by ibnbr**
But It's generate a lot of DIFF, when XML remote has the INDEX filled.

### CODE REVIEW

**Comment by larshp** [comment]
#2957

**Comment by ibnbr** [comment]
Yes, I did some tests with a offline repo.
I'll open a PR.
image

**Comment by larshp** [comment]
test PR: https://github.com/abapGit-tests/FUGR_with_parameters/pull/1

**Comment by larshp** [comment]
all okay, will wait until new version release with merging, so it can get into to the changelog

**Pull request merged**
