### PR TITLE
Add subrc before the value

### PR DESCRIPTION
**Pull request by gregorwolf**

### CODE REVIEW

**Comment by christianguenter2** [comment]
Seems the PR doesn't contain any changes (Files changed = 0)?

**Comment by flaiker** [comment]
Hmm?
f0db6449e7f1ecd23b3642d1b605f9469779fa80 was already merged into master with 24486c7d56eba954d6eb76a664fdab955b18755f  in #2477

**Comment by gregorwolf** [comment]
Looks like a display issue check https://github.com/larshp/abapGit/pull/2646/commits/f0db6449e7f1ecd23b3642d1b605f9469779fa80

**Comment by larshp** [comment]
f0db644 was already merged into master with 24486c7 in #2477

**Pull request closed without merging**
