### PR TITLE
Performance Improvement in BITBYTE_TO_INT Conversion

### PR DESCRIPTION
**Pull request by mkaesemann**
Reduced the number of calculations and processing required to convert a bit string into an integer value. which increases performance by a factor of 2 or more (depending on the string to be converted).
Note that a performance increase of >2x only happens for long strings that start with a lot of zeroes.

### CODE REVIEW

**Comment by larshp** [comment]
cool, can you help adding some unit tests for this method? currently there are none covering BITBYTE_TO_INT ?

**Comment by mkaesemann** [comment]
What would be required for the unit tests?
Just new methods in `zcl_abapgit_convert.clas.testclasses.abap` or something else? I havent worked with Travis-CI before, so I do not know the details.

**Comment by larshp** [comment]
Just new methods in zcl_abapgit_convert.clas.testclasses.abap: yes

Travis-CI only runs simple checks on the code, it does not execute any of the unit tests

**Comment by mkaesemann** [comment]
I've added a test that covers BITBYTE_TO_INT and X_TO_BITBYTE of class ZCL_ABAPGIT_CONVERT.
Please let me know if it aligns with what you expect a unit test to cover.

**Comment by larshp** [comment]
Looks good, merging

Few comments:
* Much of the git stuff is quite old, I guess it can be further optimized with SET BIT and implict conversion between hex and integer values
* Note the use of prefixes in abapGit, http://docs.abapgit.org/development/guidelines.html
* Regarding unit tests, would also like a few hardcoded tests, if all 4 methods in ZCL_ABAPGIT_CONVERT used in convert_bitbyte has similar logic, but not the intended(not sure if this is possible, but anyhow), the test will succeed

**Comment by mkaesemann** [comment]
- BITBYTE_TO_INT and X_TO_BITBYTE were the ones standing out in the performance analysis. The rest seems to perform not that bad despite its age. Maybe I'll have a look at the rest at a future point in time. 😉 
- The link in the docs regarding prefixes leads to an almost empty "CHECK_69 - Naming Conventions" page. Am I missing something? Or is it okay to rely on TravisCI checking the naming conventions when commiting a pull request?
- I see your point regarding the unit test. Even though it is rather unlikely that two bugs in the separate conversion directions level each oter out, it might happen. Maybe I'll be able to get around to it at one point.

**Comment by larshp** [comment]
**Naming**
Sorry, I'm lazy 😄 See https://blogs.sap.com/2018/05/11/all-your-abap-prefixes-are-belong-to-us/ try installing it if you are allowed.

TravisCI does not check the naming conventions 😞 Travis just runs https://github.com/larshp/abaplint which only performs very simple checks(also not documented very well)

**Pull request merged**
