### PR TITLE
SFPF, SFPI: Error by import (issue #2353)

### PR DESCRIPTION
**Pull request by p-dmitrij**
The renumbering of the attributes "id" and "href" is reworked

### CODE REVIEW

**Comment by p-dmitrij** [comment]
@larshp now it looks better :)

**Comment by larshp** [comment]
please run pretty printer for the full class source

**Comment by p-dmitrij** [comment]
done

**Comment by larshp** [comment]
#2353

**Comment by larshp** [comment]
does this PR only fix the SFPF part of the issue?

**Comment by p-dmitrij** [comment]
both parts, because this static method is called from both classes

**Comment by larshp** [comment]
code looks good to me

does it work installing https://github.com/abapGit-tests/SFPF, ie. the change is downwards comopatible? I dont have a ADS connection in my test system

**Comment by p-dmitrij** [comment]
yes, the changes are downwards compatible, no additional actions needed. If you want, you can connect the ADS in SAP Cloud (trial version) to your development system:
https://blogs.sap.com/2015/11/19/how-to-try-out/

**Comment by larshp** [comment]
welcome to abapGit as a contributor 🎉

**Pull request merged**
