### PR TITLE
Order by on repo page

### LINKED ISSUE #2852: Add order by function to repo page
Follow up #2778

I find the new sorting on the repo page a bit confusing. I'd suggest to add a order byfunction to sort by column and ascending or descending.
Maybe similar to the repo list?
image

### PR DESCRIPTION
**Pull request by christianguenter2**
closes #2852 

Disabled by default. Enabled via options and persistet in user record.
image

image

### CODE REVIEW

**Comment by sbcgua** [comment]
Really good feature. After some recent change about sorting order I was also thinking that we need custom sort order :)
But I think we could do better UI ... dropdowns are inconvenient and bulky. I guess the top header with clickable title could be better. Also maybe the sorting can be done in JS rather than in abap (maybe ...). What do you think ? I can help if needed.

P.S. Just came to mind: there is a very funny and insightful video regarding usability of dropdowns - https://www.youtube.com/watch?v=hcYAHix-riY

**Comment by christianguenter2** [comment]
Sure we can do better. I just reused the logic and design from the repo overview page. So at least it's consistent within abapGit :-) Feel free to improve. I usually find it a lot easier todo such things in server side ABAP, but that's most likely due to my limited frontend skills.

**Comment by christianguenter2** [comment]
> I guess the top header with clickable title could be better. 
I don't know how that should look like. Do you have an example somewhere?

**Comment by a-fas** [comment]
> Do you have an example somewhere?

Yeah, I'll try to prepare something

> design from the repo overview page

:))) yeap, I was actually going around it with a desire to refactor it a bit :)

**Comment by sbcgua** [comment]
> Do you have an example somewhere?

Yeah, I'll try to prepare something

> design from the repo overview page

:))) yeap, I was actually going around it with a desire to refactor it a bit :)

**Comment by sbcgua** [comment]
@christianguenter2 have a look https://github.com/larshp/abapGit/pull/2887 - something like this :)

**Comment by christianguenter2** [comment]
Closing for now. I'll adjust and reopen after #2887 is merged.

**Pull request closed without merging**
