### PR TITLE
Commit form should not be cleared on error

### PR DESCRIPTION
**Pull request by ibnbr**
issue #3011

### CODE REVIEW

**Comment by FreHu** [comment]
try running `npm run merge` and activating zabapgit.abap.

The error comes from the line `DATA ms_commit TYPE zcl_abapgit_services_git=>ty_commit_fields .`

**Comment by larshp** [comment]
abapmerge is not super intelligent 😄 but for this case the ty_commit_fields should probably belong to some interface instead

**Comment by ibnbr** [comment]
the type definition moved.

**Comment by larshp** [comment]
suggest moving `ty_commit_fields` new interface `zif_abapgit_services_git`

**Pull request merged**
