### PR TITLE
i18n texts, doma, dtel

### PR DESCRIPTION
**Pull request by sbcgua**
Hi @larshp 
My colleague @sshlapak did some code for text translations. Could you pls have a look ?

Conceptually:
1) there are dedicated methods `(de)serialize_texts` for it, that runs at the end of regualar `(de)derialize`
2) deserialization goes only for installed languages
3) there is a tag `I18N_LANGS`, which contains additional languages. It can be theoretically obtained dynamically but we decided it is better to declare it explicitly. Some times part of translation are missing and etc ... so it is better to have clear list (also better to overview in XML). The idea is to have this tag similar in all object types.

P.S. I cannot find the issue, where we discussed some translation stuff - do you remember where was it ?

### CODE REVIEW

**Comment by larshp** [comment]
Cool, few questions

a: If user A has languages EN and ES installed, releases data element as open source. User B only has language EN installed, but want to contribute to the open source project, then if user B submits a PR, the ES translation will be gone?
What if it always imports and exports all languages, will it work?

b: funtion module DDIF_DOMA_PUT is called inside a loop, and also called earlier in the DOMA code. Can the code be refactored so DDIF_DOMA_PUT is only called once?

**Comment by sbcgua** [comment]
a) that's a good point. In this case ES translation will be broken. I'll remove that installed lang check, you're right. 
Just one question: shell I keep the `lcl_objects=>is_language_installed` for any future use ? Or remove ?

b) mmm ... looks like not. `dd01v_wa` is a structure (and does also contain a translation).

**Comment by sbcgua** [comment]
Ok, removed `is_language_installed check`. But not the method itself. May be useful in future. But if you insist I'll delete because actually it is not used now anyhow.

**Comment by larshp** [comment]
cool, thanks

can we remove field 'I18N_LANGS' from the serialized XML? I guess it is not needed anymore, we can just loop through the other data?

**Comment by sbcgua** [comment]
I'm a bit doubtful about this. Here are the thoughts:
1) there should be some list of languages to iterate through. I'm not sure if all objects has some primary record to iterate over. This point is very arguable however
2) But there is another point. With the dedicated tag it is easy to see in XML which languages are there. Which can be useful.

What do you think ? Not that the above is critical. If you insist, I'll remove.

**Comment by larshp** [comment]
it looks like there is a 1:1 relation between I18N_LANGS and DD01_TEXTS in the XML?

METHOD serialize_texts, gets languages from DD01V, saved in xml field DD01_TEXTS, so in deserialization, we can loop at DD01_TEXTS to find the languages?

**Comment by sbcgua** [comment]
For `doma` and `dtel` (and I guess majority of objects) - yes. But it is it for all types ? Also I even care more about point 2 :)

**Comment by sbcgua** [comment]
But anyway this is more a conceptual decision. It is not absolutely required from technical perspective.

**Comment by larshp** [comment]
lets just keep it as is and move ahead :smile: squashing...

**Comment by sbcgua** [comment]
:+1: 
Actually it will be easy to remove it if it will prove to be useless.

**Pull request merged**
