### PR TITLE
activate new CLAS deserialization #1141

### PR DESCRIPTION
**Pull request by larshp**
activate new CLAS deserialization #1141

Please help test

Note that it does not show CLAS activation errors, as new CLAS deserialization overwrites the active version. Syntax errors can be shown via "Advanced" -> "Syntax Check"

### CODE REVIEW

**Comment by larshp** [comment]
lets try, merging 🚢

**Comment by larshp** [comment]
@nomssi if you have time, can you help testing the latest version on 702?

**Comment by nomssi** [comment]
smoke test passed (compiles and starts).
Extended program check issues:
1. functin module SU20_MAINTAIN_SNGL could not be found - method zif_abapgit_object~exists( ) of class lcl_object_auth
2. exception ICM_NOT_AUTHORIZED is not defined in the interface of the function module ICM_GET_INFO2 - method is_local_system of class lcl_http.
3. Exception CX_CLIF_SCAN_ERROR is neither caught nor is it declared in the RAISING clause of INIT_SCANNER (class lcl_oo_class_new)

**Comment by larshp** [comment]
thanks 👍, only number 3 is caused by this PR, but I dont think it is critical, but all 3 needs fixing, I have opened  https://github.com/larshp/abapGit/issues/1167 with the above description

**Pull request merged**
