### PR TITLE
SFPF, SFPI: Error by import of big SIFbA forms #2353

### PR DESCRIPTION
**Pull request by p-dmitrij**
The renumbering of the attributes "id" and "href" is reworked

### CODE REVIEW

**Comment by p-dmitrij** [comment]
@larshp I have no idea why it tries to add the old commit b949c4f (issue #2348) into the new pull request. Is it possible to create a PR with just 1 commit?

**Comment by larshp** [comment]
only add one commit to the branch, currently, it is 2 commits ahead, https://github.com/p-dmitrij/abapGit/tree/issue_2353

before making the branch sync master of the fork to latest, see https://help.github.com/articles/syncing-a-fork/

**Comment by larshp** [comment]
Sometimes I just delete my fork and fork the project again, that way everything is updated 😄 You can do this as long as there are no open PRs with source = your fork

**Comment by p-dmitrij** [comment]
Sounds good, let me try...

**Pull request closed without merging**
