### PR TITLE
dynpros and cua in FUGR

### PR DESCRIPTION
**Pull request by VishnAndr**

### CODE REVIEW

**Comment by larshp** [comment]
Hi,
I suggest moving methods deserialize_dynpros and deserialize_cua to class lcl_objects_program as protected, that way both lcl_object_fugr and lcl_object_prog can access it. Currently it looks like both methods exist twice in the big picture?

**Comment by VishnAndr** [comment]
Yes, identical. Will try with next PR

**Comment by larshp** [comment]
just do another commit to your branch, then it will show up in this PR

**Comment by VishnAndr** [comment]
OK, got it, thanks

**Comment by VishnAndr** [comment]
Done.

**Comment by larshp** [comment]
thanks, looks good to me

**Pull request merged**
