### PR TITLE
Remove fallback object lookup on SICF deserialization

### LINKED ISSUE #3230: Multiple SICF with identical names is not imported
Trying to pull a repository, a SICF object cannot be imported.

This is caused because, at import, it determines that the object exists because it is searching a pattern in TADIR that found an incorrect entry:

This is the logic to read TADIR entry:
image

And this is the TADIR table in the original system:
image

### PR DESCRIPTION
**Pull request by Elberet**
The SICF object handler considers an SICF service's URL to be the object's primary identifier rather than the object name in TADIR. Due to the nature of how SICF nodes are created, this is quite necessary; however, this also means that the SICF handler must implement some mapping between SICF nodes (identified by URL) and TADIR entries (identified by an unpredictable UUID).

Issue #3230 reports problems when multiple SICF services within one development package are being deserialized. This problem is caused by a fallback logic in the URL-to-TADIR mapping which assumes that when exactly one SICF entry exists in TADIR (for a given package), then any SICF service being deserialized should map to that object. It follows that when >1 services within the same package are being deserialized, the first service is created correctly, and any following services will simply overwrite the one that already exists.

This PR eliminates this fallback and fixes #3230.

However, due to this change, abapGit's ability to track changes to SICF nodes will be slightly impacted: when a service's URL changes, the old and new version of the service will always appear as two distinct objects rather than one changed object. When pulling, this may create additional ICF services in the system until the repo is also reset or the previous, now "untracked", version of the service is removed manually.

### CODE REVIEW

**Comment by larshp** [comment]
see comments in https://github.com/larshp/abapGit/pull/3234

**Comment by Elberet** [comment]
You mean the "this may be dangerous" comment?

See the paragraph about caveats above. Yes, it is a major change in behaviour, but I don't think it's dangerous in a "may break your system" or "may corrupt your data" way.

What could/should be done to make it even less dangerous?

**Comment by larshp** [comment]
not sure, dont exactly remember the scenario, will take a look sometime

**Comment by Elberet** [comment]
After some more digging, which also resulted in #3453, I am fairly convinced that the fallback branch is a grave mistake and should definitely be eliminated. For example:

1. Create an ICF service on the root level to serve as a private namespace.
2. In your new namespace, create an ICF service with some generic name, e.g. "odata4".
3. Export with abapGit and import on another system that does not currently contain any of these services.

In this case, `read_tadir_sicf` will happily return the object catalog entry for `/sap/opu/odata4`, and consequently `deserialize` will attempt to update a service ***which belongs to SAP*** and should absolutely not be meddled with.

**Comment by larshp** [comment]
okay, lets try it

welcome to abapGit as a contributor 🎉

**Pull request merged**
