### PR TITLE
DDIC with reference to class/interface, Search Help with Exit Function

### PR DESCRIPTION
**Pull request by mbtools**
Fix for issue with cyclic dependencies between DDIC (data element, table, structure, table type) and classes or interfaces.
https://github.com/larshp/abapGit/issues/2015, https://github.com/larshp/abapGit/issues/2338
 
Inspired by https://launchpad.support.sap.com/#/notes/409671, the change replaces references to specific classes or interfaces with a generic OBJECT reference during DDIC step. This allows for successful activation. 

The DDIC objects are then updated during LATE step with the original references and activated again. At this time, the referenced classes/interfaces exist and the activation is successful. 

In a similar way, search helps with exit functions are pointed to existing exit function RS_DD_SELMEXIT during DDIC step. And then activated with the correct function during LATE step.

Successful tests:
https://github.com/abapGit-tests/TTYP_with_CLAS_reference 
https://github.com/abapGit-tests/SHLP_with_exit 
https://github.com/christianguenter2/test_TABL_SHLP.git

(just diffs related to language or old release, which should be fixed by updating these test cases)

### CODE REVIEW

**Comment by larshp** [comment]
nice solution for this problem IMHO

**Comment by mbtools** [comment]
Any other DDIC dependency issues?

**Comment by larshp** [comment]
any other DDIC: not that I know, but we'll see

**Comment by EduardoCopat** [comment]
That's a very clever solution! Nice.

**Pull request merged**
