### PR TITLE
SCP1 Import Order

### LINKED ISSUE #2418: SCP1: Not deserialized properly at first time
When installing https://github.com/abapinho/abaK.git business configuration set (SCP1) ZABAK_TABLE_CUSTOMIZING isn't deserialized properly. 

image

image

'Reset Local' then installs the object correctly.

### PR DESCRIPTION
**Pull request by goreraks**
closes #2418

### CODE REVIEW

**Comment by mbtools** [comment]
I tried to test with https://github.com/abapGit-tests/SCP1/pull/1 but that's a new pull request. We have to keep the existing SCP1 test since it's used in automated testing. Could you please create a new repo with your SCP1/TOBJ test?

**Comment by goreraks** [comment]
@mbtools So no need of a test case in [abapGit-tests](https://github.com/abapGit-tests)?

**Comment by larshp** [comment]
https://github.com/abapGit-tests/SCP1_TOBJ created, can you close https://github.com/abapGit-tests/SCP1/pull/1, and do the pull request to the new repo instead?

would like to keep the simple test case

**Comment by larshp** [comment]
thanks 👍

**Pull request merged**
