### PR TITLE
Improve error information

### PR DESCRIPTION
**Pull request by christianguenter2**
#1998 

With this commit errors that are raised with zcx_abapgit_exception=>raise
and issued with message are enriched with two additional functions.

1) Go to source
Navigates to the source code position where zcx_abapgit_exception=>raise
is called

2) Callstack
Shows a popup with the full callstack and the possibility to navigate to
the source of each line with double click

This feature requires the full abapGit repository. Without nothing
changes.

image

### CODE REVIEW

**Comment by larshp** [comment]
There is a new message class, how does this impact the compiled version?

**Comment by christianguenter2** [comment]
Compiled version uses the default message 001 in class 00.
https://github.com/christianguenter2/abapGit/blob/234c003bcc9b133ae6d634d5e1b4b770dfdf2a9e/src/zcx_abapgit_exception.clas.abap#L186-L197

**Comment by larshp** [comment]
hmm

`EXPORT callstack = lt_callstack TO MEMORY ID co_memid.` can this be changed to use a static variable instead?

**Comment by flaiker** [comment]
Does this impact performance? I am only asking because I've seen code where `SYSTEM_CALLSTACK` is used in the constructor of a frequently instantiated class to alter behavior based on which child class is calling the parent constructor (inheritance over composition was the saying right?!). And `SYSTEM_CALLSTACK` is very high up in the runtime analysis in that case.

**Comment by larshp** [comment]
some thoughts:
1: For message classes, we should go all-in or all-out, using/allowing it in some special cases is difficult from a maintenance view
2: the solution should work in a REST setup, ie. EXPORT TO MEMORY will probably not work
3: should work with the `log` object, it can collect multiple exceptions
4: we have full flexibility for building UI inside the HTML, `MESSAGE lx_error.` can be changed to something like `lo_html->show_error( lx_erro ).`. We can add a few linked icons next to the text in the HTML

**Comment by christianguenter2** [comment]
> hmm
> 
> `EXPORT callstack = lt_callstack TO MEMORY ID co_memid.` can this be changed to use a static variable instead?
> 
> Update: probably not, as there are new transaction codes

Yes, that's the reason.

**Comment by christianguenter2** [comment]
> Does this impact performance? I am only asking because I've seen code where `SYSTEM_CALLSTACK` is used in the constructor of a frequently instantiated class to alter behavior based on which child class is calling the parent constructor (inheritance over composition was the saying right?!). And `SYSTEM_CALLSTACK` is very high up in the runtime analysis in that case.

Though I didn't measure anything, I don't think that's a problem. Because zcx_abapgit_exception is only instantiated in exceptional cases, that shouldn't happen that often. At least as far as I know the codebase.

**Comment by christianguenter2** [comment]
> 2: the solution should work in a REST setup, ie. EXPORT TO MEMORY will probably not work

Yeah, the whole idea is to provide the (SAPGUI) user with a better way to analyse errors. Therefore the EXPORT TO MEMORY trick is only applicable if the shows the longtext of a message. That's of course only the case in SAPGUI. I'll make that more explicit in the code.
For REST scenarios we could addionally add the callstack as an read-only instance attribute, so that the handler of the exception can decide whatever todo with.

**Comment by christianguenter2** [comment]
> 1: For message classes, we should go all-in or all-out, using/allowing it in some special cases is difficult from a maintenance view

All-in means that the message class is also created by the compiled report? Downside is that we increase the abapGit footprint.

**Comment by christianguenter2** [comment]
> 3: should work with the `log` object, it can collect multiple exceptions
Agreed. Will be a bit of work as the log currently doesn't store the exception object or any message related data.

> 4: we have full flexibility for building UI inside the HTML, `MESSAGE lx_error.` can be changed to something like `lo_html->show_error( lx_erro ).`. We can add a few linked icons next to the text in the HTML
Yes, that would be nice. But a bit out of scope of this PR, I think. With the callstack as an attribute nothing prevents us from going in this direction.

**Comment by larshp** [comment]
I'll spend my time on other stuff this weekend, so will probably merge this.

But, the exception class should be decoupled from GUI, I also see the new transactions and message class being deleted in a final setup, just have the GUI show the error in the HTML linked with an icon. And the exception viewer will have to be refactored so it does not use MEMORY.

**Comment by christianguenter2** [comment]
I'll close this PR. The final solution with html view and without memory tricks and additional objects is already in construction.

**Pull request closed without merging**
