### PR TITLE
Ui themes support

### PR DESCRIPTION
**Pull request by sbcgua**
to #2610, point 2

colors are separated from layout css

P.S. just in case ... won't be near a computer after today for a while (~2 weeks), sorry if there are bugs :))) ... may also wait till my return, not urgent for sure

### CODE REVIEW

**Comment by larshp** [comment]
waiting until @sbcgua is back near a computer 😄

**Comment by larshp** [comment]
@sbcgua let us know when you are back

**Comment by sbcgua** [comment]
In fact tomorrow. So the PR can be merged imho. In case of issues i’ll be able to have a look during the weekend.

**Comment by larshp** [comment]
consider if we should remove the settings from the screen, as it communicates functionality that is not fully implemeted

**Comment by sbcgua** [comment]
Hmmm... i was actually hoping that @flaiker would commit his color scheme right after this pr so that at least 2 settings are there ... @flaiker do you have any plans on it ? :)

Otherwise, probably yes, i can do it next few days

**Comment by flaiker** [comment]
Sure can do
Should be able to get it done this weekend :)

**Pull request merged**
