### PR TITLE
Re-org includes

### PR DESCRIPTION
**Pull request by sbcgua**
to #329

### CODE REVIEW

**Comment by larshp** [comment]
looks good, however a bit difficult to review 8k lines

**Comment by larshp** [comment]
note that include ZABAPGIT_OBJECT has to be deleted manually after pulling these changes

**Comment by sbcgua** [comment]
> looks good, however a bit difficult to review 8k lines

Yeap, sorry for that. Changing includes assumes that :( I hope my description in 329 hwlped somewhat

> note that include ZABAPGIT_OBJECT has to be deleted manually after pulling these changes

you mean on target systems ? In my it was deleted.

**Comment by larshp** [comment]
changing includes: yeah, there is no way around it

target systems: yes, abapGit does not delete obsolete objects automatically

**Pull request merged**
