### PR TITLE
AREA Object support

### PR DESCRIPTION
**Pull request by pawelwiejkut**
Hello Guys,

After the break, support for AREA BW objects. Please check.

Thank you.

### CODE REVIEW

**Comment by larshp** [comment]
hi, in the PR there is also some changes to IOBJ ?

**Comment by pawelwiejkut** [comment]
@larshp ,cleaned up.

**Comment by larshp** [comment]
can you help submitting a PR with an example to https://github.com/abapGit-tests/AREA ?

**Comment by gregorwolf** [comment]
Maybe @RainerWinkler can help to test.

**Comment by RainerWinkler** [comment]
@gregorwolf , I have to think about how to test. My Mini SAP is running without working SAP BW system. So I had to use one of the systems by my company for the test.

**Comment by pawelwiejkut** [comment]
Pull request to test object created

**Comment by larshp** [comment]
merging, then it will be tested
pulled ok without syntax errors

**Pull request merged**
