### PR TITLE
fix bug of ignore subpackages flag

### LINKED ISSUE #3712: The option Ignore Subpackages no longer works when adding new Online
The following change introduced a user regression:
https://github.com/larshp/abapGit/commit/09120cb80d7f7ac3fee5378d30449c850c32b7b1#diff-a387b940e84b85067646dfdc3dc0e29bL447

Old behavior:
- it raised exception only if the package was already added as a repo

Current behavior:
- the exception is raised if the package is versioned as a sub-package too

Can you please take a look, @mbtools  @FreHu 

Thanks to Antonio Yanez Santamaria <antonio.yanez.santamaria@sap.com>!

### PR DESCRIPTION
**Pull request by antonioyanez**
Closes #3712

### CODE REVIEW

**Comment by jfilak** [comment]
@larshp What's wrong with abaplint in npm?

**Comment by larshp** [comment]
npm is down, https://status.npmjs.org/ so the build is failing, wait a while and then retry

**Comment by filak-sap** [comment]
Thank you!

**Comment by larshp** [comment]
welcome to abapGit as a contributor 🎉

**Pull request merged**
