### PR TITLE
Gui refactor, part 1

### PR DESCRIPTION
**Pull request by sbcgua**
Step 1  to #3286

- there is now a way to get access to selected function of GUI - `zif_abapgit_gui_services`
- in particular `register_event_handler`, which allows to tell GUI that this particular component want to handle event - they are stacked, kind of middlewares
- this removes the necessity for the components to care about `super` handler and etc. (well not exactly at the moment as most of event handler `redefine` parents but I will adjust it)
- a new class `zcl_abapgit_gui_component` is introduces as a base class for all others. It's role is actually very simple - conveniently get reference to `zif_abapgit_gui_services`

Makes sense to review e0c82f2 and cf93ed4  as it's improvement. Commits 2 and 3 are making what they were named - remove unnesessary params in event interface and add raising to the constructors of page subclasses - and the rest are reorderings which clutter the overview unfortunately :(

Next steps: hotkeys refactoring, and most difficult separation of page logic into components

### CODE REVIEW

**Comment by larshp** [comment]
note that there is a manual step to delete the testclasses in zcl_abapgit_gui_page_diff.clas.testclasses.abap after pull

**Comment by larshp** [comment]
looks okay from my point of view, @christianguenter2 can you take a look also?

**Comment by sbcgua** [comment]
> note that there is a manual step to delete the testclasses in zcl_abapgit_gui_page_diff.clas.testclasses.abap after pull

@larshp do you mean I occasionally committed old code ? But I don't see it in this PR. (Although I didn't delete it manually). Sorry, I'm a bit confused on what you mean.

**Comment by larshp** [comment]
its all okay, the comment is probably related to https://github.com/larshp/abapGit/pull/3283

**Comment by sbcgua** [comment]
Following https://github.com/abaplint/abaplint/issues/819: I'll fix the warning (a bit later today)

**Comment by sbcgua** [comment]
@larshp have a look https://github.com/larshp/abapGit/pull/3289/commits/9316443be9057cf40c571acc59c282e66ca06f2e

Imho fishy. But works.
P.S. global method is to reduce need to implement interface directly in UT - most UT will not need it I guess at the moment.

**Pull request merged**
