### PR TITLE
Fixes #921 DDLS skip generated SADL classes 

### LINKED ISSUE #921: DDLS skip generated SADL classes
In https://github.com/jasper07/Teched17 2 clases are automatically generated by SADL, the generated classes should be skipped by abapGit

Example: ZCL_ZC_TE_FLIGHT

image

### PR DESCRIPTION
**Pull request by EduardoCopat**
Some remarks:

- Exists DDLS with name ZCL_{ ddls_name } ✔️ 
- Class has TADIR-GENFLAG = abap_true ❗️  This flag is not updated at TADIR
- and inherits from CL_SADL_GTK_EXPOSURE_MP ✔️

### CODE REVIEW

**Comment by larshp** [comment]
#921

**Comment by larshp** [comment]
cool, will have a look tonight

**Comment by larshp** [comment]
Hi,
I think we should move the `lcl_skip_objects` call to https://github.com/larshp/abapGit/blob/55013696ae9d8bd9d341221127f611d2780fa3aa/src/zabapgit_tadir.prog.abap#L207 as this is where objects are skipped, this might also allow for doing a FOR ALL ENTRIES per package, which will increase performance, plus the skipped CLAS will not be serialized

Note that #927 might change the same include

**Comment by EduardoCopat** [comment]
Thanks Lars,

I still don't think this class `skip_objects` has a good name. Any alternatives?

I will wait for #927, then I push mine.

**Comment by larshp** [comment]
I think the `skip_objects` name is okay

**Comment by larshp** [comment]
@flaiker is it okay that we merge this PR? it might cause a conflict in #927...

**Comment by flaiker** [comment]
Sure, I'll just rebase. DEVC might take a bit more time.

**Comment by larshp** [comment]
yeah, DEVC is difficult 😄

**Comment by EduardoCopat** [comment]
> See comment in PR, moving the call closer to selection of TADIR objects

Done. Please check the latest code. Is it something like this?

**Comment by larshp** [comment]
will take a look tonight

**Pull request merged**
