### PR TITLE
Removed Branch Overview Singleton - issue#2047

### PR DESCRIPTION
**Pull request by Sdfraga**
Solving #2047

### CODE REVIEW

**Comment by larshp** [comment]
as noted in http://docs.abapgit.org/other-test-ssl.html, place `zabapgit_test_ssl` outside of the main abapGit package hierarchy, this way it does not end up in git

**Comment by Sdfraga** [comment]
Noted!
Regarding the bug, I know what do to. In fact all the other methods in zcl_abapgit_factory already use a multiton approach so I would just to the same.
Like this we are homogeneous.
Will create a new PR later today

**Comment by Sdfraga** [comment]
OK

**Comment by Sdfraga** [comment]
There's an issue with the current design. 
Using a table of Singletons and access them by the key of the repo solves the branch overview log when switching repos and that's OK.

The thing is if you continue working doing more branches/commits and go back to the branch overview. Since the instance it's stored in the table of singletons, it will retrieve the repo instance at the time of creation, where the latest branches/commits are not there yet.

I need to find a way of refreshing the commits on the ZCL_ABAPGIT_BRANCH_OVERVIEW object.

**Comment by larshp** [comment]
hmm

now there is 
image

whereas the bug can be fixed by changing

```abap
    IF gi_branch_overview IS INITIAL.
      CREATE OBJECT gi_branch_overview
        TYPE zcl_abapgit_branch_overview
        EXPORTING
          io_repo = io_repo.
    ENDIF.

    ri_branch_overview = gi_branch_overview.
```

to

```abap
      CREATE OBJECT ri_branch_overview
        TYPE zcl_abapgit_branch_overview
        EXPORTING
          io_repo = io_repo.
```

ie. removing 4 lines (not taking injection into account)

just looking at ZCL_ABAPGIT_BRANCH_OVERVIEW it is not obvious what the new UPDATE method does. Anyhow, I guess there are some issues with the overall OO design of the class, so I suggest not introducing new logic, as it will make it more effort to refactor in the future

**Comment by Sdfraga** [comment]
Hi Lars,

What does this statistics means?

In fact the UPDATE method is going to update all the objects of ZCL_ABAPGIT_BRANCH_OVERVIEW (branches, tags and commits). I encapsulated all the ZCL_ABAPGIT_BRANCH_OVERVIEW constructor in a method called SETUP and the UPDATE just calls the SETUP to force the loading of the latest git objects from the remote repo.

It's true that the class is a little bit messy and since I am getting into the context of it, I will attempt to refactor it if you agree.

Anyhow, the UPDATE is being called in the ZCL_ABAPGIT_FACTORY=>GET_BRANCH_OVERVIEW, and it's only called if the BRANCH_OVERVIEW instance is already instantiated.

I ran some tests and it works fine, maybe the method name UPDATE is not that clear enough. We could change it to REFRESH_GIT_OBJECTS, UPDATE_GIT_OBJECTS, UPDATE_OVERVIEW?

In the end it's your call, if you are not comfortable with that we can just remove the singleton strategy and it will work, even if it will fail for the injection scenario.

**Comment by larshp** [comment]
Just do the direct instantiation, it will fix the issue without adding extra complexity

**Comment by Sdfraga** [comment]
Done!

**Comment by larshp** [comment]
see conflicts

**Comment by Sdfraga** [comment]
Ups.. Forgot to remove the Setup method.
It should be OK now

**Comment by larshp** [comment]
cool, looks good to me, merging 👍

**Pull request merged**
