### PR TITLE
SFPF, SFPI: Error by import of big SIFbA forms #2353

### PR DESCRIPTION
**Pull request by p-dmitrij**
The renumbering of the attributes "id" and "href" is reworked

### CODE REVIEW

**Comment by p-dmitrij** [comment]
It seems I've placed accidentally both corrections #2353 and #2348 in one pull request.

**Comment by larshp** [comment]
in your fork, make one branch per change

**Comment by p-dmitrij** [comment]
Yeah, I've got it now, sorry. Is it possible to decline the pull request? Then I could create 2 separate..

**Comment by larshp** [comment]
this one is closed, feel free to open 2 separate

**Pull request closed without merging**
