### PR TITLE
always add byte order mark

### LINKED ISSUE #799: XML byte order mark
also see https://github.com/larshp/abapGit/issues/629

diffs show up, perhaps ignore the byte order mark when comparing files, hmm

image

### LINKED ISSUE #1044: ABAPGit repo - all files constantly modified
Hi, 

Not sure if that is the cause, but on a non-unicode system all the files keep the status 'modified' even after a pull. The difference highlighted is a hashtag (#) on the remote repo in the first line of the xml.

abap git modif

### PR DESCRIPTION
**Pull request by larshp**
this will always add the byte order mark to xml files, this is relevant for non-unicode systems.
assuming most systems are on unicode this is the least invasive fix.

closes #1044
closes #799

### CODE REVIEW

**Comment by larshp** [comment]
try triggering "Advanced" -> "Update local checksums"

**Comment by BlackmanCC** [comment]
Updating local checksums did not help. Still the same problem

**Comment by larshp** [comment]
hmm, I dont have access to any non-unicode systems, so its difficult to debug 😞

**Comment by BlackmanCC** [comment]
I will debug and try to figure out what's the problem. Can you give me some hint where to start?

**Comment by larshp** [comment]
see the changes to the xml class, https://github.com/larshp/abapGit/pull/2947/files

**Comment by larshp** [comment]
will close this for now, reopen when we have verified/changed the fix

**Comment by jrodriguez-rc** [comment]
It still happens
image
image

**Comment by larshp** [comment]
yes, the corresponding issues are still open

**Pull request closed without merging**
