### PR TITLE
News improvements

### LINKED ISSUE #714: changelog/news doesnt seem to work
gc_abap_version is 1.34.0

```abap
          CREATE OBJECT ro_instance EXPORTING
            iv_rawdata = <file>-data
            iv_version = gc_abap_version.
```

when it compares the versions and it finds 1.34.0, EXIT is performed,
```abap
      "Skip everything below current version
      IF lv_version IS NOT INITIAL
         AND lcl_news=>compare_versions( iv_a = lv_version iv_b = lv_current_version ) < 1.
        EXIT.
      ENDIF.
```

### PR DESCRIPTION
**Pull request by sbcgua**
closes #714 

appeared to be a lot of work ... :)

Important! setting the `last_seen_version` raised locking exception
image
So I added `commit and wait` to `user_persistence->update_repo_config`. Not sure that it is correct. Better to check. 

Also moved `split_string` to `lcl_convert` - can be useful somewhere else as a common tool.

UPD: mention #565

### CODE REVIEW

**Comment by larshp** [comment]
thanks, will do some testing tomorrow

**Comment by larshp** [comment]
LGTM 😄 

we should consider making the last_seen user specific, but we can do it in a later PR if needed

**Comment by sbcgua** [comment]
It is :) it is in user persistence.

**Comment by larshp** [comment]
ahh 👍

**Pull request merged**
