### PR TITLE
FULL folder logic

### PR DESCRIPTION
**Pull request by larshp**
support for FULL folder logic, see #521 

please test + comment + suggest + review

### CODE REVIEW

**Comment by EduardoCopat** [comment]
Doing some tests here, I created these subpackages:

image

Then, running abapGit, the names seems strange...

image

Seems like a problem with underscore package names?

**Comment by larshp** [comment]
thanks, will have a look tonight, guess this is something that can be reproduced in `ltcl_folder_logic unit` test class

**Comment by larshp** [comment]
@EduardoCopat your repository is running in PREFIX mode, https://github.com/EduardoCopat/abap-sandbox/blob/master/.abapgit.xml

Guess we need some error handling to throw an error for the scenario above

**Comment by larshp** [comment]
try again

**Comment by EduardoCopat** [comment]
Hi, Lars,

It is working now. I receive a validation error if a package has wrong naming in the prefix mode.

How can I change my repository from PREFIX to FULL mode? Directly changing .abapgit.xml? Maybe, after the pull request is done, we could update this in the wiki.

**Comment by larshp** [comment]
change it in the remote .abapgit.xml, note that it becomes active without pull

**Comment by larshp** [comment]
merging, moving forward 🚢

**Pull request merged**
