### PR TITLE
ignore files outside of starting folder #696

### PR DESCRIPTION
**Pull request by larshp**
issue #696

### CODE REVIEW

**Comment by larshp** [comment]
one concern: should files in the root folder also be ignored as now?

If changing the starting folder from "/" to "/src/" then it could be nice to have files from / still show up in staging so they can be deleted

**Comment by flaiker** [comment]
I'd say they should be ignored if the only option available in abapGit is to delete them. If you still need command line git to create and edit those files, _native_ deletion in abapGit is not much of a benefit in my opinion.
Having a simple editor for those files might be a nice feature as well.

Or do you mean the specific case where the starting folder is changed and the "new" configuration is already used before it is committed? It might be useful to look at how git handles changes to .gitignore in relation to staging files. If I remember correctly you need to commit .gitignore before they are taken into consideration.

So I guess the order should be:
1. Change starting folder by editing .abapgit.xml or using the gui
2. Serialized files should be added under the new path (e. g. /src/), old files should be removed
3. Starting folder change in .abapgit.xml, new files under /src/ and removed old files under / can be staged and committed

For that to work the ignore configuration change must not be active before the staging of the deleted files, otherwise they will not be removable by abapGit.

Does that make any sense?

**Comment by larshp** [comment]
think changes to .gitignore are taken into account right away

The scenario I was thinking about:
1: add file zfoobar.prog.abap to /
2: commit
3: change starting_folder to /src/
4: now I would like to remove/delete /zfoobar.prog.abap in remote and add /src/foobar.prog.abap (renaming is not supported in git)

But in step 4, if everything outside "/src/" is ignored then /zfoobar.prog.abap will not show up in the staging screen to be deleted

**Comment by flaiker** [comment]
There are some edge cases where gitignore changes are not "effective" immediately, for example ignoring files that were previously committed will force you to use `git rm` to also remove them from the repo and if you have staged files (which most IDEs do automatically for all changes) these will still be staged even if you edit your gitignore afterwards to ignore those files (in the same commit even).

Staging the files for removal before editing the ignore settings and then committing these two together would be the solution to your scenario, but afaik abapGit is not designed to have any "stage persistency" so maybe split these two actions up into two commits somehow? Or have an advanced option in the staging screen to show ignored files so one can remove them? Another option would be to have a popup on changing the starting folder option in the GUI which lets you "force remove" the old source files ignoring the ignore settings...

**Comment by larshp** [comment]
moving files works in the current version, via remove and add on the staging screen

**Comment by larshp** [comment]
I have changed the logic so it does not ignore files in the root folder, but only subfolders, lets try it to see if it works out

**Pull request merged**
