### PR TITLE
Manage files command

### PR DESCRIPTION
**Pull request by sbcgua**
To #514 
There is some explanation of the code in the issue.
Briefly:
- Advanced->Remove/Ignore files: can now run stage from 'no change' state to remove or ignore remote files
- some finetunings for error log css

### CODE REVIEW

**Comment by larshp** [comment]
hi, what would happen if `iv_manage_files` was not added? I guess it would also work without? Eg. keeping the logic as is for the page will also fix the problem?

**Comment by sbcgua** [comment]
`iv_manage_files` has `DEFAULT abap_false` so skipping it will just stick to normal (old) stage logic. Normal stage page just don't pass this param. 

Or do you mean that entering stage page with the **existing** logic would show just the files we want to remove - well, **YES**, it would... 

I see your point - we actually don't need `iv_manage_files` logic to fix the issue. But I just tried to look at it a bit wider - the 'Remove/Ignore files' is not to 'Force stage' - it is meant to do free arrangement in existing repo (which is now impossible otherwise). Managing ignore list can be also more convenient from here (maybe ...). 'Force stage' - would be a strange command among others - it is intended to fix a concrete rare issue. I wanted to make a more universal solution.

Although maybe not ideal, maybe I'm mixing stuff a bit ... so I'm all open for suggestion here.

**Comment by larshp** [comment]
yeah, I see your point

I guess it depends on how you regard the feature, I see it as a workaround due to the missing "Stage" button, so a "Force stage" will fix the problem.

Remove/Ignore files is part of the normal workflow, like if I do a `git status` then it will show the files that are available for staging

**Comment by sbcgua** [comment]
OK, changed to 'Force stage'

**Comment by larshp** [comment]
cool, thanks, merging

**Pull request merged**
