### PR TITLE
Remove redundant class and interface metadata

### PR DESCRIPTION
**Pull request by EduardoCopat**
Implements #1458.

Seems like a massive PR , but I just removed some fields from CLAS and INTF XML (VSEOCLASS).

More specifically:

- CLSNAME  = Cannot be removed. Part of primary key.
- VERSION = Cannot be removed. Part of primary key.
- LANGU = Cannot be removed. Part of primary key.
- DESCRIPT = Not redundant 
- **EXPOSURE = redundant, removed. (This is if the class is CREATE PUBLIC/PRIVATE/PROTECTED)**
-  _STATE = Tried to remove and it short dumped_
- **CLSFINAL = redundant, removed.**
- **CLSABSTRCT = redundant, removed.**
-  _CLSCCINCL  =Tried to remove and it short dumped._
- FIXPT = Not redundant
- UNICODE =  Not redundant

Consequently, I also removed EXPOSURE from the VSEOINTERF.

### CODE REVIEW

**Comment by larshp** [comment]
After pulling the branch, all the INTF are inactive,

dump during pull,
image

after pull,
image

**Comment by EduardoCopat** [comment]
I was testing with a sandbox repo and it did not happen. But when I cloned abapGit it gave me the same error. So, I reverted the `exposure` interface commit - interfaces are always public AFAIK.

**Comment by larshp** [comment]
once/if INTF are forced active we can remove the redundant INTF information

will test again tomorrow

**Comment by EduardoCopat** [comment]
We could merge this one and open a new issue regarding the redundant INTF

**Comment by larshp** [comment]
yeah, will test again tomorrow and merge if it works

**Pull request merged**
