### PR TITLE
CLAS deserialization refactoring

### PR DESCRIPTION
**Pull request by sandraros**
Refactoring proposed to prepare a new user exit for solving #2671 (abapGit bug for old 7.02 kernel, customers will have to implement the user exit by copying the implementation of `zif_abapgit_oo_object_fnc~deserialize_source` and adapt it).

It concerns one method: `zif_abapgit_oo_object_fnc~deserialize_source` of ZCL_ABAPGIT_OO_CLASS.

Currently:
- it calls 8 PRIVATE methods which are dedicated to the process of deserialization.
     - update_source_index
     - generate_classpool
     - update_meta
     - determine_method_include
     - init_scanner
     - update_full_class_include
     - create_report
     - update_cs_number_of_methods
- it also calls the PRIVATE method `update_report` (which is also called by `zif_abapgit_oo_object_fnc~generate_locals` right before `zif_abapgit_oo_object_fnc~deserialize_source` is called. `generate_locals` is also specific to the
	 deserialization process).
- The PRIVATE visibility of these methods prevents the future user exit to call them.

Not a good solution:
- so that the future user exit can call these methods, a simple solution would be to expose all these private methods publicly, but that will make too many useless public methods.

Proposal:
- moving these methods to a new deserialization class sounds better, including update_report.
     - The new class is named ZCL_ABAPGIT_OO_CLASS_DESERIAL.
- make ZCL_ABAPGIT_OO_CLASS its friend so that update_report can be moved to ZCL_ABAPGIT_OO_CLASS_DESERIAL and be called by `zif_abapgit_oo_object_fnc~generate_locals` of ZCL_ABAPGIT_OO_CLASS.

### CODE REVIEW

**Comment by larshp** [comment]
hmm, using "FRIENDS" is typically workaround, will it be part of the long term solution?

**Comment by sandraros** [comment]
Well, I prefer this temporary workaround than letting `update_report` public or doing a bigger refactoring of `zcl_abapgit_oo_*` classes that would be complex to test. The current refactoring is only for grouping most of deserialization methods needed by the future user exit.

**Comment by larshp** [comment]
check conflicts

**Comment by larshp** [comment]
conflicts

**Comment by larshp** [comment]
closing for now

**Comment by sandraros** [comment]
I won't work on it anymore. Too much work for no added value...

**Pull request closed without merging**
