### PR TITLE
Function groups with namespaces - not implemented #824

### PR DESCRIPTION
**Pull request by Gekke-Jakke**
Function groups with namespaces - not implemented #824

### CODE REVIEW

**Comment by larshp** [comment]
thanks, looks good, does the function group activation work after applying this fix?

**Comment by Gekke-Jakke** [comment]
Yes everything works and activates fine (tested on SAP S/4 1610 release)

**Comment by larshp** [comment]
cool, merging, welcome as a abapGit contributor 😄

**Comment by Gekke-Jakke** [comment]
Thanks! Hope to be able to contribute in the future as well!
Great project by the way! 😄

**Pull request merged**
