### PR TITLE
background pull: always overwrite all objects

### PR DESCRIPTION
**Pull request by larshp**
always choose to overwrite all objects when using the pull in background feature. If the decision is not set the job will fail with a "undecided" error

#3800

### CODE REVIEW

**Comment by hardyp** [comment]
image

Beside "Background" being spelt wrong, where is the box to choose to overwrite all objects?

**Comment by larshp** [comment]
its determined in the code, https://github.com/larshp/abapGit/pull/3802/files

**Comment by larshp** [comment]
typo will be fixed via https://github.com/larshp/abapGit/pull/3802/commits/75a943849e964f3eb2580fad0c1f82b60568fb53

**Comment by mbtools** [comment]
FYI, perfect example of https://github.com/larshp/abapGit/issues/3757. Check will be executed twice.

**Pull request merged**
