### PR TITLE
Hotkeys no longer depend on abapGit installation #2629 

### PR DESCRIPTION
**Pull request by christianguenter2**
When this commit is applied hotkeys also work with
the single abapGit report. ~~Limitation is still that users
only can override hotkeys with the installed abapGit repo.~~

#2629

### CODE REVIEW

**Comment by sbcgua** [comment]
:+1: 
P.S. I’ll be able to check it just on Sunday from my side. Sorry. Fill free to merge if anyone else confirm

**Comment by christianguenter2** [comment]
Now it's also possible to override the hotkeys within the single file abapGit report.

**Comment by larshp** [comment]
how so? what is the new approach?

**Comment by christianguenter2** [comment]
Inspect local classes which implement interface ZIF_ABAPGIT_GUI_PAGE_HOTKEY with FM SCAN_ABAP_OBJECTS_CLASSES.

https://github.com/christianguenter2/abapGit/blob/4bc1c234beb5953e0e3259d923fa3d7fa2404140/src/ui/zcl_abapgit_hotkeys.clas.abap#L64-L69

https://github.com/christianguenter2/abapGit/blob/4bc1c234beb5953e0e3259d923fa3d7fa2404140/src/ui/zcl_abapgit_hotkeys.clas.abap#L155-L187

**Comment by larshp** [comment]
consider the following scenario:
1: I have the development version installed which contains syntax errors
2: run the merged report, will it try to instantiate the pages from the development version?

anyhow, something like 
https://github.com/larshp/abapGit/blob/ff6725e7596bedd1f5b3fb3610df266246e576f0/src/zcl_abapgit_serialize.clas.abap#L163 should solve this issue, if it is an issue

**Comment by christianguenter2** [comment]
Yeah, you're probably right. Should we make is_merged reusable? What's the right class for the method?

**Comment by larshp** [comment]
suggest adding it as new method in class `zcl_abapgit_environment`

**Pull request merged**
