### PR TITLE
HTML refactoring

### PR DESCRIPTION
**Pull request by larshp**
#3460

* delete method ZCL_ABAPGIT_HTML=>CREATE

### CODE REVIEW

**Comment by sbcgua** [comment]
Hmmm, why ? It's kind of convenient ?

**Comment by larshp** [comment]
it was only used 3 places, and many more with CREATE OBJECT

If we want to centralize this(the HTML class is just an utility), I guess we want to do it via a factory like the other things?

**Comment by sbcgua** [comment]
mmm. yes, because I added it rather recently. not that it is critical. just more convenient. but how you prefer.

factory ... what is the use case ? I mean, it is an utility, so even for cases like unit tests it is easy to fill the real class with data, then mock it. factory would be an overkill imho. The `create` was kind of self-factory :)

But no big deal anyway.

**Comment by larshp** [comment]
yea, do agree its kind of overkill

but for consistency, keep the instantiation to the factories, then the developers will know where to look, instead of some special cases 🤷‍♂️

**Comment by larshp** [comment]
@sbcgua ok to move this ahead? I think its better to have one type of instantiation to refactor going forward

**Pull request merged**
