### PR TITLE
fix possible SQL injection in generic serialization #1621

### PR DESCRIPTION
**Pull request by ThomasPloski**
Fixes all listed ATC findings following SAP note 1852318

### CODE REVIEW

**Comment by larshp** [comment]
#1621

**Comment by larshp** [comment]
hmm, will this work? I guess it should escape normal single quotes, but not at this level. 

What is the code flow that it finds?

**Comment by ThomasPloski** [comment]
I also started with escaping single quotes, but then I got a  CX_SY_DYNAMIC_OSQL_SEMANTICS exception. The usage of method escape_quotes_str works fine -- I already tested it with some objects.

As an example the data flow for method delete:
--
Class: ZCL_ABAPGIT_OBJECTS_GENERIC Section: PUBLIC SECTION Method: CONSTRUCTOR Parameter: IS_ITEM
IS_ITEM -> MS_ITEM (Method: CONSTRUCTOR Line: 28)
MS_ITEM-OBJ_NAME -> LS_OBJKEY-VALUE (Method: GET_WHERE_CLAUSE Line: 63)
LS_OBJKEY -> CS_OBJKEY (Method: GET_WHERE_CLAUSE Line: 66)
CS_OBJKEY-VALUE -> LS_OBJKEY_SUB-VALUE (Method: DISTRIBUTE_NAME_TO_COMPONENTS Line: 39)
LS_OBJKEY_SUB -> CT_OBJKEY (Method: DISTRIBUTE_NAME_TO_COMPONENTS Line: 42)
CT_OBJKEY -> LT_OBJKEY (Method: GET_WHERE_CLAUSE Line: 66)
LT_OBJKEY -> LS_OBJKEY (Method: GET_WHERE_CLAUSE Line: 116)
LS_OBJKEY-VALUE -> LV_VALUE128 (Method: GET_WHERE_CLAUSE Line: 133)
LV_VALUE128 -> LV_WHERE_STATEMENT (Method: GET_WHERE_CLAUSE Line: 134)
LV_WHERE_STATEMENT -> RV_WHERE (Method: GET_WHERE_CLAUSE Line: 139)
RV_WHERE -> LV_WHERE (Method: DELETE Line: 13)
Cannot be deactivated using a pragma.

**Comment by larshp** [comment]
it works on the entire WHERE clause, but only the values have to be escaped.

Try replacing `CONCATENATE '''' ls_objkey-value '''' INTO lv_value128.` in method `GET_WHERE_CLAUSE` with `lv_value128 = cl_abap_dyn_prg=>quote( ls_objkey-value ).`

**Comment by ThomasPloski** [comment]
Test was successful

**Pull request closed without merging**
