### PR TITLE
Condense messages in case of package move

### PR DESCRIPTION
**Pull request by mbtools**
If an object is assigned to a different package, abapGit shows multiple warning messages per object and file:

image

In case the files are identical in old and new folder (same SHA1), the messages are reduced to one per object:

image

### CODE REVIEW

**Comment by FreHu** [comment]
:+1:  I'd also include package from/package to in the message.

**Comment by mbtools** [comment]
How do you know which side is newer ie the to value?

Best,
Marc

**Comment by FreHu** [comment]
Actually I think you can't, I didn't realize. Looks okay as it is currently then.

**Comment by larshp** [comment]
add unit tests?

**Pull request merged**
