### PR TITLE
FORM, js solution

### PR DESCRIPTION
**Pull request by larshp**
Ready for testing,

a hidden value is added to keep the action,
`|<input type="hidden" id="hidden_action" name="action" value="?">|`

and then updated when using a link,
`|document.getElementById('hidden_action').value = '{ is_cmd-label }'; document.getElementById('{ mv_form_id }').submit();|`

this PR is just to show some code for a possible solution, needs work in form data parsing

solution can also be extended to handle multiple forms on the same page by using the form id in connection with the hidden id

### CODE REVIEW

**Comment by sbcgua** [comment]
Does it work in JAVA GUI browser ? I think it was the main downside.

**Comment by larshp** [comment]
yes, needs some more work, but set a breakpoint, all the data is there

**Comment by larshp** [comment]
Ready for testing @pokrakam 

@sbcgua there are some CSS missing, buttons to the right, plus the main indicator, perhaps you can help?

Some tests,
java

normal

web

**Comment by pokrakam** [comment]
Unfortunately the fields are still getting cleared when clicking Clone in JavaGui

**Comment by larshp** [comment]
@pokrakam are you running on this branch? have you restarted abapgit? can you record a gif of it and post here?

**Comment by larshp** [comment]
closing, in favor of web edition

**Pull request closed without merging**
