### PR TITLE
Fix startup of repo view

### LINKED ISSUE #3826: Multiple login dialogs on cancel from repo list
- Click on a repo that requires authentication in repo list
- The login popup appears
- You want to cancel and click cancel in the dialog
- The message "Falling back to master branch" appears
- The login popup appears 3 more times before the operation is cancelled

I don't remember it being this way before. I guess somewhere zcx_abapgit_cancel needs to be handled separately in a catch block.

### PR DESCRIPTION
**Pull request by mbtools**
This PR fixes and harmonizes several issues that can occur during the startup of the repo view:
1. Check if current branch still exists 
1. Messages in case of login errors like incorrect password and cancelation of login popup
1. URL that does not refer to a Git repo
1. Continuous errors when "last used repo" setting to turned on but errors prevent start of repo view
 
Replaces #3749, Closes #3826 

Solutions for above:
1. Missing branch -> Error with a hint what to do (no more automated switch to master)
image

1. First failed or canceled login attempt -> Error in status bar, remain in popup
image
Second failed or canceled login attempt -> Error in repo view
image

1. Error, URL can be fixed with Advanced > Change Remote
image

1. Any error preventing a repo to be displayed correctly, will now reset the "last used repo" setting. A subsequent restart of abapGit, therefore, will go to the repo overview (instead of being stuck in the erroneous repo)

### CODE REVIEW

**Comment by FreHu** [comment]
Some questions (haven't tried it yet):
- After the second login, how does the user open the password again? Refresh?
- I assume if you don't have access to the repo, you also can't do anything bad through all the repo menus?

I don't like that you disabled the auto-switch, but maybe I could just add an auto-switch on/off setting later to satisfy everyone

 I like 4., seems like a smart behavior

**Comment by mbtools** [comment]
Yes, refresh will bring up the login popup again.

Any activity that goes via HTTP will bring up the login popup. But some local activities are probably possible (like changing settings). A bit of testing would not hurt.

The automatic reset required a login first (to check the branches). That didn't work well with catching the login errors or cancelation of the popup. It might be better to validate the branches in the repo overview.

**Review by sbcgua — APPROVED** [review]
Didn't check all of that, but seem to work. Messages looks better and the code looks fine imho. 👍

**Comment by larshp** [comment]
thanks 👍

**Pull request merged**
