### PR TITLE
Popup compatibility mode (workaround to reach old create repo dialog)

### PR DESCRIPTION
**Pull request by sbcgua**
2020-09-04_23h26_36

... and then the good old abap popup is used. The flag could be useful in future to force UI compatibility (if any ...)

ref: #3417 and hopefully closes. @filak-sap @pokrakam

### CODE REVIEW

**Comment by larshp** [comment]
hmm, moving in this direction we would have to do double maintenance for all gui pages?

**Comment by sbcgua** [comment]
well, compatibility is always double sided. Here I just reacted to complaints that it was not possible to clone a repo in javagui ... In general ... I don't know, imho either "keeping minimal viable functionality in old style, no new features" or completely switching new gui approach (rest + external ui). but, it is really a wide question, i'm really open for ideas, i don't like compat either :)

**Review by larshp — CHANGES_REQUESTED** [review]
moving discussion to #3417

**Comment by larshp** [comment]
Suggest closing this, we will either move towards https://github.com/larshp/abapGit/pull/3879 or the web edition

**Comment by sbcgua** [comment]
Yeap agree, that's a cooler stuff

**Pull request closed without merging**
