### PR TITLE
Completely dynamic JS hints

### PR DESCRIPTION
**Pull request by sbcgua**
to #2811

@christianguenter2 

draft for the moment, might be some polishing needed but works and ready for review

- hints are completely generated in JS, so no auxilliary `<span class="tooltiptext hidden">`
- some terminology fixes (tooltip vs hint) and some css
- I changed the JS code quite heavily ... sorry ... appeared to be an interesting subject, carried away :) ... hopefully for good.
- `ZCL_ABAPGIT_HTML ` - just removed the tooltip span, others are se80 reorderings
- same for ZCL_ABAPGIT_GUI_PAGE - just a rename in JS function
- known issue: a dropdown displayed with hint cannot be hidden ... actually no change from existing logic ... not sure if possible to fix cleanly ... maybe with timeout
- known issue: I added backspace for reverting hint steps back ... but works only on the first page - after IE perceives it as back button :( not sure how to fix

Doubt: why setting color in settings ? Imho it should depend on theme directly. Didn't change but imho not quite consistent.

### CODE REVIEW

**Comment by sbcgua** [comment]
P.S. I think JS file should be splitted in parts ... maintenance is quite inconvenient by now

**Comment by larshp** [comment]
what is hints?

**Comment by sbcgua** [comment]
The keyboard navigation feature Christian mentioned in #2775 
image

**Comment by larshp** [comment]
any impacts on performance with these changes?

**Comment by sbcgua** [comment]
No sure how to measure. In theory it should be faster because of pointers caching. But not sure how to measure it properly, especially in IE. I'm open for suggestions :)

**Comment by christianguenter2** [comment]
> Doubt: why setting color in settings ? Imho it should depend on theme directly. Didn't change but imho not quite consistent.

Agree. I guess there's the option to set the color in the chrome vimium plugin. I thought it would be cool to have the same in abapGit. But to be honest, I didn't change the standard color since then. And we hadn't themes when I implemented this ;-)

**Comment by christianguenter2** [comment]
Did some tests. LGTM from a functional point of view.

**Comment by christianguenter2** [comment]
> I changed the JS code quite heavily ... sorry ... appeared to be an interesting subject, carried away :) ... 

Sure, no problem at all :-) I can learn a lot.

**Comment by christianguenter2** [comment]
> known issue: a dropdown displayed with hint cannot be hidden ... actually no change from existing logic ... not sure if possible to fix cleanly ... maybe with timeout

I can be hidden with the hint. That's ok for me.

**Comment by christianguenter2** [comment]
> any impacts on performance with these changes?
Didn't notice any negative impact during my tests.

**Comment by FreHu** [comment]
@sbcgua
>No sure how to measure. In theory it should be faster because of pointers caching and less dynamic dom changes. But not sure how to measure it properly, especially in IE. I'm open for suggestions :)

You can profile using iechooser, although you need to export it and then import it in a normal IE window.

**Comment by larshp** [comment]
looks like the JS is only run when hotkeys are enabled, good,
image

**Comment by sbcgua** [comment]
@christianguenter2 

- color: ok, if you don't mind I'll remove it then :) 
- what do you think about backspace feature ? did you try ? I thought it would be nice to undo typings ... but since it works only on the first page (most frequently the tutorial ...) it does not make sense :( I'm considering removing it
- "dropdown can be hidden with the hint" - hmm, you mean remembering the last triggered dropdown and clearing it on hotkey press ? Interesting idea. Thought can be a bit tricky - I'll have a look. P.S. sadly `li` does not support `:focus` state - it would solve the issue cleanly, just click anywhere and focus changes together with CSS

**Comment by sbcgua** [comment]
@FreHu @larshp did some performance tests, with good old `console.time`

Scenario: init (obviously), show all hints, hide all hints, show all again, type 146 for filtering (each time less items to filter), total number of hints 3466. last 2000 hints were one above another ... made a separate test to check if block elements would be different but the difference seems to be minor.

Stages below named differently for new and old logic, but follow the same order - it has the same meaning

IE
```
New logic
deployHintContainers: 421ms
displayHints true:    489,9ms
displayHints false:   152,5ms
displayHints true:    441,4ms
filterHints 1:        283,8ms
filterHints 4:        59ms
filterHints 6:        44,2ms

Old logic
querySelectorAll:       2ms
toggleAllTooltips true: 471,2ms
toggleAllTooltips false: 401,8ms
toggleAllTooltips true: 399,2ms
filterTooltips 1:       326,7ms
filterTooltips 4:       77,6ms
filterTooltips 6:       44,8ms
```

Initialization is obviously taking more time in the new logic as it creates elements. Though half a second per 3,5k hints ... seems to be OK for me. Displaying, surprisingly for me, is a bit longer then in old one. Seems like because internal structure of the hint in the new logic is more complex (2 independent spans) - made a quick test for this. Hiding is faster in new logic. And also filtering (probably because of those 2 independent spans - back side of the coin - that was why I actually made them). But in general - same figures imho.

Now to extend the study, let's run it in Chrome

```
New logic
deployHintContainers: 17.22ms
displayHints true:    19.35ms
displayHints false:    9.38ms
displayHints true:    18.66ms
filterHints 1:        22.15ms
filterHints 4:        10.61ms
filterHints 6:         8.61ms

Old logic

querySelectorAll:         0.21ms
toggleAllTooltips true:  54.86ms
toggleAllTooltips false: 68.09ms
toggleAllTooltips true:  35.89ms
filterTooltips 1:       127.24ms
filterTooltips 4:        72.48ms
filterTooltips 6:       105.40ms
```
Yeah ... was is the same PC ? :)

**Comment by christianguenter2** [comment]
> * color: ok, if you don't mind I'll remove it then :)
okay

> * what do you think about backspace feature ? did you try ? I thought it would be nice to undo typings ... but since it works only on the first page (most frequently the tutorial ...) it does not make sense :( I'm considering removing it
Yeah, if I misstype something I press the activation hotkey twice and start over again.

> * "dropdown can be hidden with the hint" - hmm, you mean remembering the last triggered dropdown and clearing it on hotkey press ? Interesting idea. Thought can be a bit tricky - I'll have a look. P.S. sadly `li` does not support `:focus` state - it would solve the issue cleanly, just click anywhere and focus changes together with CSS

Note quite sure whether we are talking about the same thing. I mean this:
abapGit5

**Comment by sbcgua** [comment]
OK, committed the discussed changes.

> Dropdown logic

Ah, OK, I see what you mean. This should also work :)
But I also added some minor improvements in the last commits. 
- if you force-close the hints (second "f"), and a dropdown was displayed - it is closed automatically. 
- Also if you open a dropdown, and show hints again (like in your gif), and mistype the command, then all hints are closed (it was so before) and also opened dropdown closes too.

I release the PR from draft, imho it is complete. But I'll be away for a week, so no bugcare :)) Maybe wait a bit with the merge if you prefer :))

**Comment by christianguenter2** [comment]
Sorry for the force push. Somehow did something wrong while merging master.

**Comment by christianguenter2** [comment]
Small bug. When a page is newly rendered, hint on a dropdown doesn't work the first time.
abapGit6

I try to fix it.

**Comment by christianguenter2** [comment]
#2807

**Pull request merged**
