### PR TITLE
Fix #2171 - removed dependency on field order

### LINKED ISSUE #2171: Dump: After Save Repo Settings - Folder Logic Full
ABAPGIT Version: 1.80.0

I got a dump after saving the repository settings folder logic full.

Some screenshots from the dump:

### PR DESCRIPTION
**Pull request by pokrakam**
Rather than assuming fields arrive in a sequence, I've pushed it into a local class that only assumes the fields of a row are grouped. Not perfect but it works.

### CODE REVIEW

**Comment by larshp** [comment]
error, see https://travis-ci.org/larshp/abapGit/builds/472111388 its linked from the PR when there is an error

**Comment by larshp** [comment]
I'll will test the abapmerge feature

**Comment by larshp** [comment]
seems to work,
image

**Comment by pokrakam** [comment]
Hej Lars, 

Thanks, didn't know we should avoid local classes. But happy to be guinea pig, and that it works. 

Re. the linter, the message read: 
Parser error(Unknown statement), ABAP version v702
I got it in retrospect, but at the time "Parser Error" looked like an abaplint fault - bear in mind I haven't used a linter before. I was expecting something about bad indenting or naming convention.

Merry Christmas,
Now it's time for ... Skål!

**Comment by larshp** [comment]
suggestions for a better error message welcome

**Comment by pokrakam** [comment]
Re. message: if the 'Parser error' wasn't there it would be clearer IMO. Just: 
Unknown statement, ABAP version v702
Or else if the unknown keyword can be included in the message? 

I'm not overly fussed, now I know what to look out for. I've forgotten how much extra work v702 is :)

**Pull request merged**
