### PR TITLE
Release locks/abapGit on pure BASIS system Issue #1826 

### PR DESCRIPTION
**Pull request by marcellourbani**

### CODE REVIEW

**Comment by marcellourbani** [comment]
Hi Lars
It should: I do have it in the 7.1 systems I have access to:
[image: image.png]

PS: sorry for the chaos, I'm rather new to PRs

**Comment by marcellourbani** [comment]
Also, a google search found this
<https://help.sap.com/viewer/109c9fd96c53101484f0ceb38844e91e/7.0.35/en-US/489709f255493987e10000000a421937.html>,
I think it's been around since 7.0

**Comment by larshp** [comment]
cool, perhaps we should change it to fall back to BANK_OBJ_WORKL_RELEASE_LOCKS if the new one does not exist, then we are sure not to break anything

**Comment by marcellourbani** [comment]
Lol, I had code to do that and removed it because I thought we didn't need
it anymore.
Will put it back

**Comment by marcellourbani** [comment]
ok, done

**Pull request merged**
