### PR TITLE
hide current branch and HEAD in delete popup #1908

### PR DESCRIPTION
**Pull request by bigld**
don't show current branch, HEAD and its symref in the branch delete popup
check if branch delete was refused
also some refactoring in abapgit_popups

### CODE REVIEW

**Comment by bigld** [comment]
closes #1908

**Comment by larshp** [comment]
this PR also contains refactoring regarding the popup?

**Comment by bigld** [comment]
Yes, do you want a separate PR for this?

**Comment by larshp** [comment]
nah, but it would have been easier to review

merging, thanks

**Pull request merged**
