### PR TITLE
Support object type SRFC - RFC Service #977

### PR DESCRIPTION
**Pull request by christianguenter2**
#977

### CODE REVIEW

**Comment by larshp** [comment]
When installing a remote enabled RFC function module, I've previously experienced the SRFC object to be generated automatically, any thoughts on this?

**Comment by christianguenter2** [comment]
I don't have a clue.

**Comment by larshp** [comment]
another approach is to skip all SRFC objects, hmm, not sure what is best

**Comment by christianguenter2** [comment]
I just did some experiments with RFC FMs, but there were no SRFC objects been created. Are there any special steps required?

**Comment by larshp** [comment]
usually I've seen them being generated automatically when pulling the RFC FM, but not sure if it depends on version/system settings

**Comment by christianguenter2** [comment]
It seems that it can be activated via profile parameter ucon/rfc/active.
Class CL_UCON_HELPER method IS_UCON_RFC_ACTIVE checks that.

There's also the report RS_UCON_PHASE_CUSTOM.
image

I'm not yet sure how this fits in the big picture. I'll try to figure it out.

**Comment by larshp** [comment]
okay, with the possibility of it not being generated automatically, I think we should add the feature

**Pull request merged**
