### PR TITLE
SPRX: Proxy Object

### PR DESCRIPTION
**Pull request by christianguenter2**
Proxy objects are quite complex. With this commit we add basic SPRX support.

Working scenarios are:
- Service Consumer [test-repo](https://github.com/abapGit-tests/SPRX)
- Service Provider [test-repo](https://github.com/abapGit-tests/SPRX)

#87

All credit goes to @JohannesKonings who did most of the hard work.

### CODE REVIEW

**Comment by larshp** [comment]
hmm, the abaplint app did not run

**Comment by christianguenter2** [comment]
what's the abaplint app?

**Comment by larshp** [comment]
this result, https://github.com/larshp/abapGit/runs/54301906
Anyhow, it looks like its certificate related, as abaplint.org got a new certificate automagically a few days ago.

**Comment by larshp** [comment]
now it works

**Pull request merged**
