### PR TITLE
SAPLink wrapper and generic implementation for logical transport objects

### PR DESCRIPTION
**Pull request by mrsimpson**
Some time ago, I implemented a generic saplink-plugin which acts similar like the SAP transport process: It interprets the logical transports metadata and gets the content directly from the database tables. Similarly, it modifies the database-tables directly. Using OpenSQL as API and the table definition is of course dangerous. Therefore, the plugin also includes the table's metadata so that it can be at least compared on metadata-level, whether the tables are compatible.
Object deletion is implemented, but currently disabled (as SAPLink does not feature deletion).

In order not to re-implement everything, I implemented a wrapper for SAPLink-Plugins.

Feedback appreciated.

Oliver

P.s.: I neither had a clue about ABAPGit nor about Git in general: I just started getting to know it. Thus, I do not know whether forking & pull-request were the proper idea or whether I got the concepts right. Feel free to refuse the pull request if one of those assumptions is violated, I can keep trying in my on fork, I guess at least ;)

### CODE REVIEW

**Comment by larshp** [comment]
thanks, forking and pull request concepts are correct :smile: 

few questions/concerns
a. there are currently 2 abapgit files in the repository,
https://github.com/mrsimpson/abapGit/blob/master/zabapgit.abap
https://github.com/mrsimpson/abapGit/blob/master/zabapgit.prog.abap
I guess the installation process is to install zabapgit via copy paste, and then clone the rest of the objects into the system?

b. I am very worried about the licensing, the code in the pull request contains GPL and apache licensed code while abapGit is licensed under MIT.

I'm not an expert in licensing but it seems like including GPL code as part of the core project would require the core project to also become GPL,
https://www.quora.com/I-am-writing-software-licensed-under-MIT-and-including-GPL-software-Should-I-include-the-whole-GPL-license-text
http://stackoverflow.com/questions/11819831/including-gpl-external-library-in-mit-code

c. what are the SAP version requirements? I have looked in a 740 SP4 and some of the standard clases used are not present

**Comment by mrsimpson** [comment]
hmmmmmm - guess you are right with with all your questions & concerns.

ad a. That would be the process. Though I have not tried how that behaves if the pro zabapgit replaces itself. Will do that tomorrow. I thought this to enable multiple artifacts as discussed recently (without steamrolling).

ad b. yuck - licensing. You are right, I guess. I'd have to talk to one of the saplink-guys. @gregorwolf , what do you think?

ad c. I implemented in 7.40 SP8. Which dependencies are violated?

**Comment by larshp** [comment]
a. something like this approach might work out for addons/plugins. I see the steamroller discussion ending up with having all the same features in the installer as in the installed program. 
So one approach(like the one you outlined) could be to keep zabapgit as is, but have the option to install a addon/plugin repository alongside. This might also solve some problems with SAP versions and supported object types, stuff like Gateway builder/BOPF/FPM doesnt all go back to 702 which is the version requirement for abapgit.

c. will look more into it tomorrow

**Comment by larshp** [comment]
c. in https://github.com/mrsimpson/abapGit/blob/master/zsaplink_bopf.clas.locals_imp.abap class LCL_MAP can you help pointing out where it is used?

**Comment by mrsimpson** [comment]
Ahh, damn it. Forgot to refactor the locals. This was a relic  from a previous try to use a published API for BOPF. Didn't work out as expected and was available only as of SP08. After this fail, moved tothe generic sobj-based table-approach. Removed this part in my repo.

**Comment by mrsimpson** [comment]
Closing this pull-request due to Lars' idea & efforts with respect to plugin.
Might submit a new one once ready.
Work on plugins in https://github.com/mrsimpson/abapGit/tree/plugin-enabling

**Pull request closed without merging**
