### PR TITLE
Downport: Fix syntax errors in 702

### PR DESCRIPTION
**Pull request by mbtools**

### CODE REVIEW

**Comment by larshp** [comment]
does both changes trigger syntax errors in 702? I think both have been in the codebase for some time...

**Comment by mbtools** [comment]
Yes. The APACK error is in a test class so dev version only. I might have been the first to try this in 702.

The other one came up when I tried to activate the standalone 1.98 in 702. Chaining method calls in functional style gives errors if there are multiple exporting parameters. There are other locations where it's done properly with a local variable but this call was missed. 

PS: There are other issues with 702 like diffs related to serializing classes and exceptions. I guess no one is using it seriously on this release.

**Comment by larshp** [comment]
feel free to create an issue regarding parsing on 702 in the abaplint repository, ideally the linter should catch this at every pull request

**Comment by mbtools** [comment]
Already there https://github.com/abaplint/abaplint/issues/996

**Comment by larshp** [comment]
ahh, okay, thanks 👍

**Pull request merged**
