### PR TITLE
Dcls

### PR DESCRIPTION
**Pull request by christianguenter2**

### CODE REVIEW

**Comment by larshp** [comment]
many of the checks done by abaplint is also implemented in https://github.com/larshp/abapOpenChecks which you can run on the ABAP AS 😄

**Comment by christianguenter2** [comment]
yep, I'll do that in the future ;-)

**Comment by larshp** [comment]
thanks, looks good, so much new stuff 😄

**Comment by flaiker** [comment]
Activating travis on a fork works quite well too :)

**Pull request merged**
