### PR TITLE
Split up global settings button and utility menu

### PR DESCRIPTION
**Pull request by flaiker**
To me it feels like the settings button does not belong into the menu since it is a "user facing" functionality while the other stuff in the utility menu is more for development on abapGit itself or less commonly used utility functions. Open to opinions though, maybe I am alone in that assumption.

image

Addresses #3770 with the least amount of effort possible :)

### CODE REVIEW

**Comment by flaiker** [comment]
I also noticed the settings hotkey does not work on the repo page. I tried adding it in 1444744a5f5910dc17ee349d0030a348d3e2d89c but that causes the table to change the hotkeys to shortdump because of a duplicate key. So I reverted that change.

**Comment by mbtools** [comment]
I was about to split "Settings" into "Global Settings" and "User Preferences" since it was becoming rather big with the new HTML forms https://github.com/larshp/abapGit/issues/3878. Maybe with your change "Global Settings" and "Personal Settings" behind the "Settings" button make more sense.

**Comment by larshp** [comment]
thanks 👍

**Comment by flaiker** [comment]
> I was about to split "Settings" into "Global Settings" and "User Preferences" since it was becoming rather big with the new HTML forms #3878. Maybe with your change "Global Settings" and "Personal Settings" behind the "Settings" button make more sense.

If it's split into two pages then just change it to a dropdown again.

**Pull request merged**
