### PR TITLE
ENHO: class implementation #507

### PR DESCRIPTION
**Pull request by larshp**
#507

support for pre+post+overwrite exits implemented

still todo: enhancement types from interface enhancement, but I guess the method enhancements are most common

### CODE REVIEW

**Comment by larshp** [comment]
@sbcgua would you like to take a look at the code before it is merged?

**Comment by sbcgua** [comment]
I'll have a look tomorrow

**Comment by larshp** [comment]
thanks, also a bit far from my expertice :o)

1: It only impements pre+post+overwrite exits, I think the addition of new methods are handled via CL_ENH_TOOL_CLIF, also mentioned in the todo:
`* todo, CL_ENH_TOOL_CLASS inherits from CL_ENH_TOOL_CLIF so this
* should also be reflected in the code in this include`
I suggest we open a new issue for this after this PR is merged.

2: the exits method needs some rework, will try to fix,
```abap
  METHOD lif_object~exists.

    DATA: ls_tadir TYPE tadir.

* todo, it should look up in the ENHO database tables or call some methods
* to see if the object exists, looking in TADIR will not work
    ls_tadir = lcl_tadir=>read_single(
      iv_object   = ms_item-obj_type
      iv_obj_name = ms_item-obj_name ).
    IF ls_tadir IS NOT INITIAL.
      rv_bool = abap_true.
    ENDIF.
  ENDMETHOD.
```

**Comment by larshp** [comment]
- METHOD lif_object~exists fixed
- alignment fixed

we just need this to be better than the current code, not necessarily fix everything in this PR 😄

**Comment by sbcgua** [comment]
Sure. Anyway it seems there are a lot of feautres in class enhancements so they can be implemented one by one when really needed. :)

**Pull request merged**
