### PR TITLE
Minor improvements of icons in repo view

### PR DESCRIPTION
**Pull request by mbtools**
INTF + TYPE > code icon
DEVC > package icon

image

Bonus: Icon Legend in Debug Info:

image

I will copy the legend to docs.abapgit.org in separate PR

### CODE REVIEW

**Comment by larshp** [comment]
the overview is nice, but consider any kind of setup where no manual maintenance is required

**Comment by mbtools** [comment]
parsing the icon-css-mime seems overkill and wouldn't include the descriptions anyway. i was just curious what all icons looked like... and then thought we can reuse the HTML for the user doc (see separate PR)

**Comment by larshp** [comment]
yea, okay, just think it will get out of date

**Comment by larshp** [comment]
syntax error....

**Pull request merged**
