### PR TITLE
Removed all endmethod and endclass comments

### LINKED ISSUE #1570: Reduce "compiled" abapGit size, comments after ENDMETHOD
the code contains a lot of comments after ENDMETHOD, eg.

`  ENDMETHOD.  "get_page_playground`

we should delete all these dummy comments, it will decrease the compiled size a bit

### PR DESCRIPTION
**Pull request by FreHu**
Resolves #1570

### CODE REVIEW

**Comment by FreHu** [comment]
Done using find/replace 
(endmethod.)\s*".* for $1
(endclass.)\s*".* for $1

**Comment by larshp** [comment]
cool

we have some open pull requests, which might have conflicts when this is merged, not sure if to merge this one first or later

**Comment by FreHu** [comment]
Just curious, what exactly does reducing compilation size impact (and is the effect noticeable)? I saw similar comments in our own code.

**Comment by larshp** [comment]
not much, I guess

The comments were auto generated by some old pretty printer versions

**Comment by larshp** [comment]
conflicts, I'll prioritize getting the pull requests with features in, not sure when the queue is more or less empty so this can be merged

**Comment by larshp** [comment]
yeah, lets close this for now

**Pull request closed without merging**
