### PR TITLE
add IDoc Segment support as part of TABL

### PR DESCRIPTION
**Pull request by bigld**
IDoc Segment type/definition is just customizing and has no own transport object but it generates a structure and is coupled to it

The segment type/definitions have their own XML at the TABL object

### CODE REVIEW

**Comment by bigld** [comment]
I can't test this with multiple definitions! Does anyone have a Z-IDoc for different releases/definitions?

**Comment by bigld** [comment]
#1989

**Comment by larshp** [comment]
suggest adding a new test repo under https://github.com/abapGit-tests

**Comment by bigld** [comment]
Testrepos:
https://github.com/abapGit-tests/IDOC.git
https://github.com/abapGit-tests/IEXTgit

**Pull request merged**
