### PR TITLE
Replace assert in gui_page_stage with check

### PR DESCRIPTION
**Pull request by FreHu**
This is connected to the strange bug in #3073 which remains unsolved. Every time I update abapgit on our systems I need to change this line or people eventually run into this dump and I get e-mails about it.

### CODE REVIEW

**Comment by larshp** [comment]
this will give unexpected results to users? some parts of the commit will disappear?

perhaps raise an exception instead?

**Comment by FreHu** [comment]
Yeah, it will skip the file so let's go with an exception instead. Not sure if I should mention files with spaces in the message as the suspect because I can't offer a reliable solution - "it goes away eventually" is not very professional, but I've tried debugging it multiple times and this is in fact how it goes.

**Comment by larshp** [comment]
"staging files failed, reason unknown, try again"

**Comment by FreHu** [comment]
I came up with           

Unable to stage { ls\_file-filename }. If the filename contains spaces, this is a known issue. Consider ignoring or staging the file at a later time.

what do you think?

**Comment by larshp** [comment]
good, but might be too long to display, lets try anyhow

**Comment by FreHu** [comment]
It's not a standard message, longer texts look alright.

**Pull request merged**
