### PR TITLE
Serialize master language only - further improvements

### PR DESCRIPTION
**Pull request by FreHu**
Additional languages no longer serialized in DTEL, DOCT.

### CODE REVIEW

**Comment by sbcgua** [comment]
Quick review :) well, for me looks fine too

**Comment by FreHu** [comment]
You're super fast with the merges today, usually stuff stays here for weeks :D

**Comment by larshp** [comment]
thanks :D

sometimes I'm also busy with real work

**Comment by larshp** [comment]
if I'm too slow feel free to ping me, or have one of the other regulars do a review

**Pull request merged**
