### PR TITLE
Solve issue - Error determining the main package #2547

### PR DESCRIPTION
**Pull request by LMachado**

### CODE REVIEW

**Comment by larshp** [comment]
#2547

**Comment by larshp** [comment]
guess the PR should have been created for the master branch? https://github.com/LMachado/abapGit/branches

**Comment by LMachado** [comment]
> changes in code seems unrelated, the commit in the PR should be [LMachado@9afce36](https://github.com/LMachado/abapGit/commit/9afce36d68733ab8d85ae6a14a311372609fc323) ?

Yes, the root problem is in the method find_top_package of class  zcl_abapgit_transport.
Where is determinant the top package, used to in method zip. Pass this on creation of new instance of  class zcl_abapgit_repo_offline.

For instance in our case, we have 3 packages.

ZFI-CA in
ZFI in
ZHOME is the root package 

the internal table have this information:

line 1 - ZFI-CA 
line 2 - ZFI 
line 3 - ZHOME

after sort 
line 1- ZFI
line 2 - ZFI-CA  
line 3 - ZHOME

To get the root package he need to read the last position of internal table.  



> guess the PR should have been created for the master branch? https://github.com/LMachado/abapGit/branches

Yes, is this wrong?

**Comment by larshp** [comment]
yeah, suggest closing this PR and opening a new for correct branch

**Comment by larshp** [comment]
closing, see https://github.com/larshp/abapGit/pull/2551 instead

**Comment by LMachado** [comment]
Done in #2551 
Thank you!

**Pull request closed without merging**
