### PR TITLE
Added Utility method and used it in ENHS

### PR DESCRIPTION
**Pull request by ed-holland**
issue #3628

### CODE REVIEW

**Comment by larshp** [comment]
I think the change is okay, but there are some errors when pulling the changes

**Comment by ed-holland** [comment]
The problem is probably the exception class. I had to delete it and let non-developer AG create it again.

**Comment by ed-holland** [comment]
can this PR be merged?

**Comment by larshp** [comment]
yea, just need to consider the timing and communication, as this will probably cause a lot of reinstalls

**Comment by larshp** [comment]
^I'll merge this PR when doing a version bump, which is sometime soonish

**Comment by mbtools** [comment]
Careful. get_longtext was changed to IF_MESSAGE~GET_LONGTEXT.  This will break https://github.com/larshp/abapGit/blob/20f93ff514ab6cf68c10f4c82fb7a7f15e8aa320/src/ui/zcl_abapgit_gui_chunk_lib.clas.abap#L346 

The change should just add the raise_with_text method, but not change anything else.

**Comment by larshp** [comment]
having `METHOD get_longtext.` in the old source I see as an error, it should not be possible since this method is from `IF_MESSAGE`

**Comment by mbtools** [comment]
agree. so either we add an alias or fix the call in chunk_lib.

**Comment by larshp** [comment]
@mbtools this PR adds the alias, https://github.com/larshp/abapGit/pull/3658/files#diff-329001d7fdc74918422f2948c8647abfR121

which I guess is okay?

**Comment by mbtools** [comment]
LGTM

**Pull request merged**
