### PR TITLE
Changelog display

### PR DESCRIPTION
**Pull request by sbcgua**
To #565

Main part of code is implemented by @TheWirtschaftsmann + some review and finetuning from my side.

**Briefly how it works:**
At the main page rendering it checks if the repo is AG repo and finds `/changelog.txt` in repo status. Parses it comparing to current version of AG. If version parsed is higher -> adds the block of changes to news log. And renders it as a togglable div (toggled by "pulse" icon at repo toolbar).

**Important**: version header is supposed to strictly comply specific format (YYYY-MM-DD vX.Y.Z)

Text before the first version head - stripped
Text lines that consist of ` -=` - stripped
Changes ("!") are considered important so additional warning is shown on top of news div. Can and should be used to announce critical changes like format change and misc migrations. (thinking about additional highlighting to lines like that - not sure - but could be useful to actually "announce" things)

### CODE REVIEW

**Comment by larshp** [comment]
Hi,
a: can you add a screenshot of how it looks?
b: is the news always rendered?
c: if upgrading from 1.30.0 to 1.40.0, what is shown in the news field?

**Comment by sbcgua** [comment]
a) actually the screen has not changed from the one in the issue. But here is a bit wider one
image
Also I'm thinking if the toggle button should be e.g. orange and not blue

b) No, both news and toggle button are only rendered when there are some records in the changelg with version higher than current. By default div is hidden. There are 2 potential open points from my side to this fact:
- div is hidden by default - is it OK? One option is to show it to user once and then remember in settings that this particular version was shown and hide it next time. 
- it checks the current branch and current repo (fork!!!) so the news announcement does not work well for contributors :) ... maybe there is a room for improvement or maybe can be ignored since the main focus should be on a regular user who is always in master branch. Need an opinion. 

c) see the screenshot - I hardcoded 1.30 version there so this is actual changelog between 1.30 and last changelog updates in my fork.

**Comment by larshp** [comment]
okay, cool

I think we should add a feature so it remembers the version for each user, and if the news has been shown, but we can add this later

ok for merging 🚢

**Comment by sbcgua** [comment]
OK :) Let;s see how it is received then. I've also added some comments to the issue for discussion.

**Pull request merged**
