### PR TITLE
fix package change caching

### PR DESCRIPTION
**Pull request by sbcgua**
to #372

### CODE REVIEW

**Comment by larshp** [comment]
thanks :+1:

**Comment by sbcgua** [comment]
mmmm ?????? strange

**Comment by larshp** [comment]
argh, conflicts, can you update `zabapgit_page_main.prog.abap` ?

**Comment by sbcgua** [comment]
Do you know how to see the conflict in github ? I cannot see the conflict in the local tool :((

**Comment by sbcgua** [comment]
Hmmm, I'll remove my change in page_main. Will commit separately (actully it is style change not issue fix).

**Comment by larshp** [comment]
there is no conflict handling on github :disappointed:

**Comment by sbcgua** [comment]
Oh ! Seems to work now :)
Strange issue :)

**Pull request merged**
