### PR TITLE
Clearer error message for no branch

### PR DESCRIPTION
**Pull request by ed-holland**
Clearer error message when no entry is available for popup

### CODE REVIEW

**Comment by larshp** [comment]
Issue #3595

**Comment by ed-holland** [comment]
@larshp I thought i got rid of all the "Merge" entries from the commit list, but it looks like things only got worse. Conflicts on files not changed. Also it seem the original commits are not recognized as already in master. Git drives me nuts.

**Comment by FreHu** [comment]
https://xkcd.com/1597/

**Comment by ed-holland** [comment]
Finally... will do better in the future

**Comment by ed-holland** [comment]
@larshp I've added the ignore for the Gitlab config file, but it is still being added all the time. Is there a way to avoid it?

**Pull request merged**
