### PR TITLE
Removed original language validation

### PR DESCRIPTION
**Pull request by christian1020-94**
According to #545. Please validate this change doesn't affect anything else.

### CODE REVIEW

**Comment by larshp** [comment]
the check mentioned in #545 can be removed, but not the general check.

Eg. in the example from #545 only the master language text is saved in the xml, so we want to make sure this text is installed in the target system using the same language

**Comment by christian1020-94** [comment]
Mmm then I have to log on in Englisb in order to update my abapGit version? Or is there something else that can be done?

**Comment by larshp** [comment]
perhaps implement a feature allowing star in MASTER_LANGUAGE, `<MASTER_LANGUAGE>*</MASTER_LANGUAGE>`

However I am not sure if you install abapGit with login language = Spanish, and then modify it when logged in in English and submit a PR with english? Perhaps this is why the description was lost in PR https://github.com/larshp/abapGit/pull/581

image

**Comment by christian1020-94** [comment]
Yes,  I think that is exactly what happened. Should i uninstall abapgit for a clean setup?

**Comment by larshp** [comment]
would be nice, or alternatively just dont commit/stage the xml file

**Comment by christian1020-94** [comment]
Right,  but this should be fixed in your master?

**Comment by larshp** [comment]
fixed in https://github.com/larshp/abapGit/commit/a0ad8dcec9467ba630bdcc5110dd4a713e9ad11f

**Comment by larshp** [comment]
closing

**Pull request closed without merging**
