### PR TITLE
New repo with Folder Logic and Ignore Sub-packages params

### PR DESCRIPTION
**Pull request by filak-sap**
This pull request should allow us to create repositories for package whose sub-packages are already versioned. I do understand that package hierarchy is not the best I have no power to change it, so I need to cope with it.

The implementation is definetly not perfect, so I would like get some early feedback. It is partially copypasta of the offline repository stuff where the parameter Folder logic already made it into the popup window.

image

### CODE REVIEW

**Comment by larshp** [comment]
Suggest renaming "Ignore subpackages" to something else, "allow already versioned subpackages", "allow multi versioning", alternatively move it to a separate popup explaining the user the scenario

**Comment by filak-sap** [comment]
> Suggest renaming "Ignore subpackages" to something else, "allow already versioned subpackages", "allow multi versioning", alternatively move it to a separate popup explaining the user the scenario

The new option "Ignore subpackages" **does not** allow you to version a sub-package twice (by super package and by the dedicated repo for the sub-package).

Th new option  "Ignore subpackages" allows you to set the repo option ignore_subpackages in the new repo popup dialog in order to allow you create a repo for a package whose sub-packages are already versioned but those package will not be versioned in the new repo.

Do you still want me to change the label or move it to a new dialogue?

**Comment by larshp** [comment]
we should consider the user interface, the user is shown multiple options that are not needed in the typical setup

merging

**Comment by jfilak** [comment]
Thank you!

**Pull request merged**
