### PR TITLE
doc: link to opensource guide Open PR

### PR DESCRIPTION
**Pull request by JohannesKonings**
PR description from opensource guide
https://opensource.guide/how-to-contribute/#opening-a-pull-request

### CODE REVIEW

**Comment by christianguenter2** [comment]
Interesting. Are WIP pull request something we want to do?

**Comment by JohannesKonings** [comment]
I don't know 😄 
I just found the description (except the WIP) fits well and points to more details.
Could we add the link with the hint not to use WIP or should we describe it in our own words?

**Comment by larshp** [comment]
hmm

**Comment by larshp** [comment]
will close this

things kinda works as is

**Pull request closed without merging**
