### PR TITLE
INTF: fix changed by, close #486

### LINKED ISSUE #486: INTF - changed_by dump
test via menu option "Advanced" -> "Test changed by"

awaits
https://github.com/larshp/abapGit/pull/480
https://github.com/larshp/abapGit/pull/471

### PR DESCRIPTION
**Pull request by larshp**

### CODE REVIEW

**Comment by larshp** [comment]
@sbcgua @EduardoCopat would one of you like to review this one?

**Comment by EduardoCopat** [comment]
Looks fine to me. Just a few points:

- I prefer exceptions rather than assertions because then they do not generate a short dump
- Maybe `lv_clsname` could be renamed to `lv_class_name`
- 'ls_/lt_ repo_src' to repository_source and repository_sources

**Comment by larshp** [comment]
exceptions: When this error occurs it is due to an error in the ABAP programming, in this case I like to use assertions, when a user sees a dump he/she usually contacts a developer. When it is due to bad data/input or wrong use, I throw an exception. (plus I am lazy, ASSERT is easy)

lv_clsname: yeah, `lv_clsname` is used extensively in the include, if it should be changed, we should change it across the entire include

we can spend a lot of time renaming variables or methods, it is one of the most difficult things in programming :o) I suggest we leave the renaming to #21, both `lv_clsname` and `lv_class_name` sounds good to me, but I would like the naming of variables to be consistent in the CLAS include

**Comment by EduardoCopat** [comment]
ADT supports renaming refactoring. It works pretty well.

**Comment by larshp** [comment]
merging, feel free to do the suggested changes in #21 if you choose to start working on it :smile:

**Pull request merged**
