### PR TITLE
Apack serialization interface

### PR DESCRIPTION
**Pull request by jrodriguez-rc**
From abapGit to a git repo, `zif_apack_manifest` is replaced by `if_apack_manifest`, and pulling from a git repo to abapGit `if_apack_manifest` is replaced by `zif_apack_manifest`

You can check from https://github.com/jrodriguez-abapGit-Testing/package1

image
image
image

### CODE REVIEW

**Comment by sandraros** [comment]
You shouldn't replace the interface `IF_APACK_MANIFEST` in the source code during the pull/deserialization if this interface exists in the SAP system.

**Comment by jrodriguez-rc** [comment]
> You shouldn't replace the interface `IF_APACK_MANIFEST` in the source code during the pull/deserialization if this interface exists in the SAP system.

But it only exists in the ABAP backend for the cloud version, isn't it?
It is managed by ADT plugin for Eclipse, not in abapGit

**Comment by sandraros** [comment]
I don't understand what you mean. There are two cases during the deserialization, depending on the type of ABAP backend:

- ABAP for Cloud: both `IF_APACK_MANIFEST` and `ZIF_APACK_MANIFEST` exist. It's not required that ZIF is converted into IF in the deserialized source code (but you can do it if you want; I don't know if there are drawbacks). And I think everybody agrees that converting IF into ZIF makes no sense.
- ABAP not Cloud: only `ZIF_APACK_MANIFEST` exists. In fact I think it's planned that SAP delivers `IF_APACK_MANIFEST` in future SPs (with backporting), but right now abapGit should support its absence or presence. So, if `IF_APACK_MANIFEST` doesn't exist, abapGit should convert `IF_APACK_MANIFEST` into `ZIF_APACK_MANIFEST` in the the deserialized source code, otherwise it should leave the source code unchanged.

**Comment by SebastianWolf-SAP** [comment]
ZIF_APACK_MANIFEST doesn't necessarily exist in the Cloud, it's actually not that likely as it's not autogenerated by the abapGit infrastructure (that is the case in the on-premise/community version). To my knowledge there are no commitments by SAP that IF_APACK_MANIFEST will be available in on premise systems, especially not in earlier releases or lower SP versions. 

As a consequence, I wouldn't harmonize the source code to IF_APACK_MANIFEST during serialization. I'd limit the adaptation to the inbound (meaning deserialization) procedure. As we exclusively work on the on-premise version here, this change can IMHO be made automatically.

**Comment by jrodriguez-rc** [comment]
The change is to maintain always the same object in the repository (to prevent a permanent change detected) and support on-premise to cloud and vice versa.

**Comment by sandraros** [comment]
> (I said:) You shouldn't replace the interface IF_APACK_MANIFEST in the source code during the pull/deserialization if this interface exists in the SAP system.

@jrodriguez-rc I did this remark because my assumption was that ABAP Cloud used the code from abapGit project. If I'm wrong, then please ignore my remark.

**Comment by larshp** [comment]
To me, the performance of this PR looks bad, moving to issue https://github.com/larshp/abapGit/issues/3319

merging

**Comment by marcissimus** [comment]
Sometimes we need better release notes...

This change impacts all repositories that included APACK based on ZIF_APACK_MANIFEST. After this merge, abapGit will show a diff on the class containing interface ZIF_APACK_MANIFEST (local is serialized as IF_APACK_MANIFEST, but the online repo still contains ZIF_APACK_MANIFEST). 

>>> Stage the class containing interface ZIF_APACK_MANIFES to your repo to get things in sync

In general, it's quite confusing if the serialized object is different from the object in your system. I like this change here, but we should document and keep track of such cases.

**Pull request merged**
