### PR TITLE
A link to the development guidelines is added

### PR DESCRIPTION
**Pull request by p-dmitrij**
Can be useful for a quick start if you are a new contributor

### CODE REVIEW

**Comment by p-dmitrij** [comment]
@larshp I've added the link as we discussed, but not sure, how the link address should be written. I've checked sources of other pages, but all these pages have links only to files in the same directory. And here we have a page in a different directory (development/). So perhaps the link should be extended with the directory name. By the way, is it possible for a contributor to test changes of pages?

**Comment by larshp** [comment]
see https://docs.abapgit.org/development/docs.html for how to test the docs locally

but yeah, I think the link should be prefixed with "development/"

**Comment by p-dmitrij** [comment]
I've adjusted the link, now it looks like "development/contributing.html". But I can't test it right now, need some time to setup the test environment.

**Comment by larshp** [comment]
will try to merge it

**Comment by p-dmitrij** [comment]
It works! :)

**Pull request merged**
