### PR TITLE
Ignore files not in local repo

### PR DESCRIPTION
**Pull request by matt1as**
When commiting files from the Transport-to-branch option Abapgit tries to commit all objects in the transport request, and if these transports are for some reason ignored (.gitignore, generated SADL-objects for example) the commit fails since not all files to be commited are in the repo.

This change ignores these files, and trusts that the files not in the local repo should not be staged. Not sure if this is something we should trust, but it solves my itch.

### CODE REVIEW

**Comment by larshp** [comment]
lets try it, merging

**Comment by matt1as** [comment]
Seems to work, deleted my fork now

**Comment by Srinu3366** [comment]
Thanks folks. It solved one of the issues I am having. Now I don't need to worry about objects from different packages in same transport. I can go to respective package and create branch.

**Comment by matt1as** [comment]
@Srinu3366 

This change is only for the transport to branch-option, if you try to stage objects from packages outside of the repo it will still complain. So yes, this works if you only use transport-to-branch, but not if you subsequently try to make another commit, then you still need to cherry-pick your objects.

Also, wouldn't it be very easy to create dependencies between specific branches of different repos, not sure that's a good idea, I like to see my commits as "atomic" as far as possible

**Pull request merged**
