### PR TITLE
Check other dev clients in user master record

### LINKED ISSUE #2433: Background mode only finds user data in the current client
We have multiple development clients in the development system. Not all developers have users in all clients. Projects are separated by transport layer on package level.

abapGit background mode can only determine name and email for users in the current client. This causes commits to be created by username@localhost. I suggest adding a fallback to also look for the users in other development clients.
https://github.com/larshp/abapGit/blob/cfe976984e4328f8b8560d0fff16cad581355ccf/src/background/zcl_abapgit_background_push_au.clas.abap#L70-L89
https://github.com/larshp/abapGit/blob/cfe976984e4328f8b8560d0fff16cad581355ccf/src/utils/zcl_abapgit_user_master_record.clas.abap#L55

### PR DESCRIPTION
**Pull request by flaiker**
Fixes #2433 

Cannot check if this works until Friday.

### CODE REVIEW

**Comment by flaiker** [comment]
Finally someone developed something in the other client... Seems to work fine.

Regarding the `SELECT ... ENDSELECT` error: What is the recommended approach to get only the first result of a select? I remember `SELECT SINGLE` giving me SLIN errors if I don't specify the full table key in the where-clause. And declaring an internal table and using `UP TO 1 ROWS` seems like just an additional step to achieve the same result?
I have no problem changing it to the internal table variant, just curious as the `SELECT ... INTO wa ... EXIT ... ENDSELECT` pattern is very common in a codebase I maintain.

**Comment by larshp** [comment]
SELECT: I think this one can be changed to SELECT SINGLE. SLIN complains yea, but the SELECT ENDSELECT is just a workaround for not having SLIN complain, SELECT SINGLE is, in my opinion, easier to understand this is exactly what we want and yea, the result might not be unique. 

(Performance wise I think SELECT SINGLE will be a bit faster, as the database can close the cursor right away, but this is a suboptimization, first priority is to make it easy to understand)

**Comment by flaiker** [comment]
I'll change it later to SELECT SINGLE.

One downside I can think of though is that you cannot specify ORDER BY with SINGLE. So the result you get might be different for every execution on HANA?

**Comment by larshp** [comment]
yea, there is no ORDER BY in this statement, hence the "this one can be changed" comment

if it contained ORDER BY its more difficult, but there I lean towards using internal tables, this is quite easy on new ABAP versions, but a lot more work on 701

**Pull request merged**
