### PR TITLE
Packages excludable

### PR DESCRIPTION
**Pull request by CASAG-MariusRaht**
With these modifications it's possible to maintain multiple excludable packages for Online Repositories. There are two options to add/remove packages to be excluded: Via the Online Repository Creation Popup and the Repository Settings Page. Package Names are separated by Semicolon and max. 255 characters are supported for the settings attribute (maybe a html-table would be better?).

### CODE REVIEW

**Comment by larshp** [comment]
What is the use-case scenario for this feature? IMHO it makes it more difficult for both the system and users to understand.
Alternatively the package structure can be changed to reflect the repo structure, this will make it easy for both humans and computers to understand.

**Comment by CASAG-MariusRaht** [comment]
Use-Case-Scenario: Someone want to connect a repository to abapGit but doesn't want to sync all packages within a package linked to the repository.

I don't understand why you say "alternatively": In fact I change the internal table lt_packages in zcl_abapgit_tadir->build and filter it - do you mean that?

**Comment by larshp** [comment]
If you change the package structure in SE80, move the sub package to somewhere else, it will solve the issue?

**Comment by CASAG-MariusRaht** [comment]
Sure, it would. But the problem from my point of view is that you just want to filter and not change the package structure within the SAP System. With the Filtering you just exclude packages you don't want to host within the repository on GitHub without the need of changing the package structure within the SE80.

**Comment by CASAG-MariusRaht** [comment]
Sry that I updated .travis.yml within this branch/pull request - I'm not yet fully capable of GitHub. I just  wanted to create my own Travis CI build with my own API key and didn't know I have to create a new branch to separate it from this pull request.

**Comment by jfilak** [comment]
@CASAG-MariusRaht : you can run the travis check on your own machine:
https://github.com/larshp/abapGit/blob/master/travis.sh

Just push to your abapgit repo, pull the changes to your workstation, and run the script - you might need to read it and convert it from Bash syntax to something Windows can swallow.

**Comment by larshp** [comment]
IMHO, when this feature is needed it means there is something wrong in the package setup, the sub package does not belong under the super, if it is not to be versioned along with the super package.

This feature will also make it non-transparent which packages are versioned and why, raising the possibility for misunderstandings and hence more issues.

It also adds some complexity in the "only one repo per package" check, which is currently not addressed?

That being said, I think at least we should not promote the use of the feature in the new online popup, but instead hide it on the repo settings page only

**Comment by CASAG-MariusRaht** [comment]
"IMHO, when this feature is needed it means there is something wrong in the package setup, the sub package does not belong under the super, if it is not to be versioned along with the super package."
> Ahh...now I see your point of view. Also it is already possible to add the subpackages to be versioned one by one to the same repository (each has a single entry in abapGit) and preserving the hierarchy at the same time. That would make the feature obsolete. On the other side it would make the maintenance easier because it wouldn't be necessary to add single entries per subpackage.

"This feature will also make it non-transparent which packages are versioned and why, raising the possibility for misunderstandings and hence more issues."
> Yes, but I think that would be easy to solve: There could be a message/text which shows the filter value.

"It also adds some complexity in the "only one repo per package" check, which is currently not addressed?"
> Yes, the check would have to take the filtered subpackages into account and would have to identify them as packages with a link to a repository though they are not being processed by it.

"That being said, I think at least we should not promote the use of the feature in the new online popup, but instead hide it on the repo settings page only."
> I agree - due to your first argument I'm not sure anymore we need at all. Though maybe it would be a little bit easier and more comfortable for some users to add a super package where some subpackages shouldn't be linked to the repository. I experienced another use-case yesterday: A subpackage couldn't be imported (PULL on destination system) due to a missing generated development object which wasn't included into the subpackage. All in all I agree with your suggestion to hide it in the repo settings page only but at the moment also see some valid use-cases.

**Comment by larshp** [comment]
@CASAG-MariusRaht so can we close this?

**Comment by CASAG-MariusRaht** [comment]
I'll do the necessary changes to my branch (remove from online repo popup and extend one repo per package check) and then I'll pull it again. Should we close it then or leave it open to preserve the discussion?

**Comment by larshp** [comment]
lets close for now, and then you can open a new PR containing the changes. All PRs are kept as history

**Pull request closed without merging**
