### PR TITLE
CLAS: 702: Fix for missing suppress_dialog parameter

### PR DESCRIPTION
**Pull request by mbtools**

### CODE REVIEW

**Comment by larshp** [comment]
what happens in 702, then it will show a dialog?

**Comment by mbtools** [comment]
I didn’t get are popup for classes but for interfaces it will show a popup asking to activate the changes. So you have to press enter once.

**Comment by larshp** [comment]
guess its better than a dump

**Comment by mbtools** [comment]
it's a minor inconvenience but I don't see any other way

**Pull request merged**
