### PR TITLE
Database change warning - Issue #296

### PR DESCRIPTION
**Pull request by EduardoCopat**
Related to Issue #296.

The warning is triggered when a field name is changed, a field type is changed or a field is deleted.

image

Had to change many files, but the only considerable changes are at OBJECTS_TABL, stage_page and objects.

### CODE REVIEW

**Comment by larshp** [comment]
Hi,
Thanks! :smile: Few issues/questions:

a: it looks like the implementation of compare_to_previous_version is missing in a few objects_ ACID, AUTH, PROG etc. It looks like the code will dump when no object is returned?

```abap
  METHOD lif_object~compare_to_previous_version.

  ENDMETHOD.
```

b: Push vs pull

From the screenshot it looks like the changes have been implemented at push. 

Originally I thought of the following scenario:

User A releases a open source project with a database table, user B installs it. User A removes eg. a column in the database table. User B then does a pull to get the latest version, at this point I think the error should occur? As user B might loose some data, user A is the author of the project so he/she knows what is being changed.

c: Perhaps move `CLASS lcl_object_tabl_validation` to a new include?

**Comment by EduardoCopat** [comment]
Hi, @larshp, thanks for the review!

a) My mistake. I may have skipped some. I will review again all objects. 

I also thought of implementing the interfaces at the lcl_objects_super, but that did not sound good.

b) Yes, it is only valid for push. I thought that this was under **A** responsability.

I will adapt to the "pull" scenario, but then I will need more time to investigate how to do that...


c) That could be done

**Comment by larshp** [comment]
b: I guess user A knows what is happening, and did the actual change to the database before the push. I suppose user B knows less about what is happening since he/she is just a consumer of the project, and not a maintainer.

One solution could be to implement the check as first part in `lif_object~deserialize`(include ZABAPGIT_OBJECT_TABL), that way the extra interface method would not be needed. However I guess this will conflict with some of the checksum calculations that have recently been implemented.

Otherwise `METHOD deserialize`(include ZABAPGIT_OBJECTS_IMPL) is where the main deserialization is handled, it also already has another warning implemetned(METHOD warning_overwrite)

**Comment by EduardoCopat** [comment]
@larshp You are right. This change at "pull" level makes more sense. Let's do the following: Close this pull request and I will create a new one from scratch. This one helped me understand better the code base :).

I believe this warning_overwrite could be somehow overwritten by child-objects (i.e. the TABL validation is different from the regular validations).

**Comment by larshp** [comment]
`warning_overwrite` uses the checksums, and takes effect for all objects, and we can leave as is.

If we place the call to `compare_to_previous_version`(perhaps rename to compare_to_current_version) at eg.:
https://github.com/larshp/abapGit/blob/1096bb25a40e4754c60994bf9057601211180eb8/src/zabapgit_objects_impl.prog.abap#L654
the code knows the object reference, and we can use much of the approach from this pull request.

**Comment by larshp** [comment]
:+1: closing

**Pull request closed without merging**
