### PR TITLE
Add master language setting to new repo popups

### PR DESCRIPTION
**Pull request by FreHu**
Adds master language only setting to new online/new offline popup.

This makes the setting easy to discover, it is actually very useful and unknown - on our systems translations just magically appear and produce diffs, or you have different sets of languages between systems.

### CODE REVIEW

**Comment by larshp** [comment]
hmm, think we need to look into making it easier to understand which of these settings are local only

**Comment by FreHu** [comment]
I think this should be in .abapgit.xml, but local means you only need to set this once per system right? And you would always set it up when linking the repo.

**Comment by FreHu** [comment]
Also there could be a separate page instead of these popups, that would allow to better explain what is what.

**Comment by sbcgua** [comment]
One question: if i remember well the original feature (master lang only) is supported just for export. So the the flag can be a bit misleading. Would be nice to have it for online deserialization as well. Separately from this change of course - the feature is good.

**Comment by FreHu** [comment]
My use case assumes you don't want to commit the languages at all - it can add a lot of content so it takes longer to serialize/deserialize.

**Comment by sbcgua** [comment]
> My use case assumes ...

Ah, ok. I also used it differently. My scenario is deploying: complete product in master system (with several langs) -> deploy to another system where just english will be used. So I export package with master lang only and set master lang only in the target system to match it. 

But I just realized that the feature is incomplete and has room for improvement ... :)

**Comment by FreHu** [comment]
> So the the flag can be a bit misleading

the word _serialize_ unfortunately doesn't fit in the label

**Comment by FreHu** [comment]
And for you it wouldn't make sense to move the setting to abapgit.xml, since you want it different across systems.

**Comment by sbcgua** [comment]
@FreHu 
- abapgit.xml: it can be there **also**. Like a higher level setting that has higher priority. It just has to be a possibility to regulate it on local level if nothing was defined in abapgit.xml
- anyway in the context of this PR everything is OK imho. With my comments I just meant that there is another piece of puzzle to create in future

**Comment by FreHu** [comment]
That would work, but I wouldn't complicate the settings even more until it's really necessary.

**Pull request merged**
