### PR TITLE
skip initial fields in XML, #478

### PR DESCRIPTION
**Pull request by larshp**
guess this will work

### CODE REVIEW

**Comment by larshp** [comment]
I'm a bit afraid of merging this one, I have done some testing and it looks okay.

Does anyone have time to take a look and test it a bit?

**Comment by sbcgua** [comment]
I can have a look but probably on the weekend, might not have time before

**Comment by larshp** [comment]
should also fix https://github.com/larshp/abapGit/issues/42 at the same time as this is merged, as most XML files will have changes, we might as well include all ABAP files

**Comment by larshp** [comment]
closing, will open new PR for this in a bit

dont want all the file changes in the PR

**Pull request closed without merging**
