### PR TITLE
unprettify XML before save

### PR DESCRIPTION
**Pull request by sbcgua**
to #556

----
Solved the unprettify thing. Seems to work. 
But I'm not sure if it is the best solution. Maybe as short term ... but in general I think it would be better to actually de-serialize XML to be saved with appropriate class (and thus validate it) and serialize it again. What do you think ?

### CODE REVIEW

**Comment by sbcgua** [comment]
No linter today ? =)

**Comment by larshp** [comment]
sometimes travis-ci is a bit behind, https://www.traviscistatus.com/ 😄

**Comment by larshp** [comment]
yeah, it would be better to move the logic down

would like to merge https://github.com/larshp/abapGit/pull/587 before this one, as both contain changes in the persistence program

**Comment by larshp** [comment]
thanks, LGTM

**Pull request merged**
