### PR TITLE
SPRX, change serialization logic

### PR DESCRIPTION
**Pull request by larshp**
see discussion in #2430 

This changes the amount of data in each SPRX file, one header will now match one file. Change should be backwards compatible.

### CODE REVIEW

**Comment by larshp** [comment]
okay, all the SPRX are now deserialized, however the INTF and WEBI are not generated, as when the SPRX are deserialized it might not have enough information to build the proxy, and there is no diff for the SPRX objects the INTF and WEBI deserialization are not triggered again

Guess the part with
```abap
    IF mv_object = 'INTF'.
      generate_service_definition( lt_sproxdat_new ).
    ENDIF.
```
has to be moved to the INTF object

**Comment by larshp** [comment]
there is also some issues during uninstall, however triggering uninstall multiple times solves the issue, guess the ddic dependency graph for SPRX has to be calculated

**Comment by larshp** [comment]
tested ok with https://github.com/abapGit-tests/SPRX/pull/1

for https://github.com/abapGit-tests/SPRX_server_proxy I get the same error as with the old code

I think the file contents is correct now, however there are still problems during deserialization and uninstall, but I think the serialization problems are fixed

**Comment by larshp** [comment]
@flaiker can you try testing this change

@christianguenter2 would you like to review this change?

**Comment by flaiker** [comment]
Errors are gone 👍 
A commit with 3105 additions and 9780 deletions was created.
I cannot test deserilization for this project unfortunately.

**Pull request merged**
