### PR TITLE
Web DynPro Component Configuration Support

### PR DESCRIPTION
**Pull request by habrahams**
Web DynPro Component Configuration Support - ZCL_ABAPGIT_OBJECT_WDCC

### CODE REVIEW

**Comment by larshp** [comment]
issue #78

**Comment by habrahams** [comment]
I'm going to push another commit. I have to make one or two corrections.

**Comment by larshp** [comment]
no problem 👍

**Comment by mbtools** [comment]
Hi Harry, a few comments:
- There's no need to make everything dynamic. WDCC exists in 702 already so you can use table, structures, and classes directly (except maybe for fields which exist only in newer releases).
- COMMIT / ROLLBACK is handled by abapGit. Raising exceptions in case of problems is sufficient. Pls remove those statements.
- During deserialize, you can handle TADIR by simply calling `tadir_insert( iv_package ).` (which is in super class)
- TADIR deleting is done automatically, if you set `delete_tadir = abap_true` in get_metadata.

PS: Based on this, I can see that we need to enhance https://docs.abapgit.org/development/serializers.html a bit...

**Comment by habrahams** [comment]
Thanks for the feedback Marc, I'll make the requested changes.

**Comment by mbtools** [comment]
A couple things to remove:
"**[HJA]->
me->

do you have a minimal test repo for WDCC that we can copy to https://github.com/abapGit-tests?

**Comment by larshp** [comment]
https://github.com/abapGit-tests/WDCC created

**Comment by habrahams** [comment]
@larshp , thanks for the WDCC repo in abapGit-tests, I'll fork and commit my tests.
@mbtools , sorry I completely forgot about the testing that was mentioned in the guide. I do have a test repo, but it is in a namespace other than Z. I will copy over a few WDCC's to the Z namespace and commit to the test repo.

**Comment by habrahams** [comment]
Should I close the pull request, or is this done by yourself after the branch has been merged with the main repo?

**Comment by mbtools** [comment]
If you close it, we can’t merge ;-). Just give us a little while to test. The merge will finalize this Request and you can then drop the branch (but you used the master so just keep it).

**Comment by mbtools** [comment]
I copied a standard test to https://github.com/abapGit-tests/WDCC. There's a diff with OTR but it's unrelated to WDCC (and fixed with https://github.com/larshp/abapGit/pull/3681). 

Your class works but it's odd to store the config configuration which is already XML twice inside the WDCC XML:
https://github.com/abapGit-tests/WDCC/blob/master/src/zwdr_test_config%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2000.wdcc.xml

Why not save it as a separate file (using iv_extra parameter)? Have a look at https://github.com/larshp/abapGit/blob/master/src/objects/zcl_abapgit_object_xslt.clas.abap 

Instead of COMPONENT_CONFIGURATION_READABLE and COMPONENT_CONFIGURATION_RAW just this:

serialize:
```
    mo_files->add_string( iv_extra  = 'config'
                          iv_ext    = 'xml'
                          iv_string = lv_xml_xstring ) ##NO_TEXT.  
```
deserialize:
```
lv_xml_xstring = mo_files->read_string( iv_extra = 'config'
                                       iv_ext   = 'xml' ) ##NO_TEXT.

```

**Comment by habrahams** [comment]
Hi Marc, thank you for the feedback, I will have a look at your suggestions.
The reason I added the readable(escaped) part was for a person to view changes in the diff.
Initially I only tried to add the readable XML string, but if the string was not pretty printed it dit not want to add the complete string into the object xml. Thus I pretty printed the xml, this worked adding the xml string to the object xml, but the deserialisation was problematic as when the string was un-pretty printed certain white spaces would be removed and you would end up with constant differences(which were false).
For this reason I added the raw part to insure that the exact xml was written during deserialisation.

**Comment by larshp** [comment]
@mbtools any additional comments?

**Comment by mbtools** [comment]
Yes, I think it makes sense to separate the XML config of the WDCC object into a separate file. It's the same with XSLT and works well there. This extra file is human-readable so we will get proper diffs. Let's give it a try.

**Comment by habrahams** [comment]
@mbtools , with regard to being able to see the diff with the additional file, the additional file is saved as raw and yes the file is human readable in GitHub but the XML is an exact copy of the WDCC stored in the database, thus the XML is contained in the first line of the additional file which would still make it difficult to view the diff. The only middle ground I can think of is to actually include a pretty printed version in the base file which would show the differences, and the additional file used during deserialisation to ensure an exact copy is saved.

**Comment by mbtools** [comment]
The additional file should be pretty-printed. Does the deserialize not accept this pretty printed version? If it's just about the end of line character that could be easily replaced. 

I'm not using WDCC currently so I'm ok serializing it binary. But to serialize it in clear text as COMPONENT_CONFIGURATION_READABLE and then ignoring it on deserialize is not good. So either it's in a file that can be edited remotely and deserialized, or it's binary.

**Comment by habrahams** [comment]
@mbtools, the additional file is now pretty printed and in string format, no longer raw. Also I was able to get past the serialisation/deserialisation, pretty printing and un-pretty printing issue by using zcl_abapgit_convert and zcl_abapgit_xml_pretty classes.

**Comment by mbtools** [comment]
Excellent. I updated https://github.com/abapGit-tests/WDCC. Push, Pull, and Uninstall work beautifully.

Ready to merge!

**Comment by larshp** [comment]
welcome to abapGit as a contributor 🎉

**Comment by habrahams** [comment]
Great stuff, thank you.

**Pull request merged**
