### PR TITLE
Method descriptions - Issue #431

### PR DESCRIPTION
**Pull request by EduardoCopat**

### CODE REVIEW

**Comment by EduardoCopat** [comment]
@larshp 
>the methods table(type = seoo_methods_r) contains a lot of data. It would be cool if a method can be added in the ABAP code, and the XML will not need to be updated. Currently it looks like a lot of the ABAP code will be replicated in the xml(eg. method parameters)

Maybe I could only put the descriptions in the XML?

Check what was the result of the XML with <methods> in the example here:

https://github.com/EduardoCopat/abap-sandbox/blob/master/zec_b_class.clas.xml#L48

**Comment by larshp** [comment]
Descriptions only: yes

Implementation idea: When deserializing call SEO_INTERFACE_TYPEINFO_GET with version = inactive, and add the descriptions and call SET, dont know if it will work or not

**Comment by EduardoCopat** [comment]
Description: Is the impact in performance so high?

Idea: Why version inactive?

**Comment by larshp** [comment]
description: it is not due to performance; ABAP is moving towards source based editing, so I would like abapGit to store most of the data in the ABAP source code file

Idea: the ABAP source code is deserialized to inactive state

Idea 2: Alternatively find the place where the method descriptions is stored(table/function modules)

**Comment by larshp** [comment]
So only include the data from database table SEOCOMPOTX. It looks like the table can be updated directly, or alternatively function module `LXE_OBJ_TEXT_WRITE_CLAS` looks promising

**Comment by EduardoCopat** [comment]
Efforts so far: I tried only to put the "methods descriptions" in the UML, but when deserializing it does not work.

XML Example: https://github.com/EduardoCopat/abap-sandbox/commit/e6236ac0a3c0c6c297858129ca516cfe01c7c359#diff-c55e45c781a08dc936e43873ba4e948aR59

Might be the case that a direct update to the database table might be needed, but I'd like to avoid that.

**Comment by EduardoCopat** [comment]
Direct update on `SEOCOMPOTX` does not work. The class components (methods) were not created yet.

Latest try here: https://gist.github.com/EduardoCopat/18df63e5225039721c55ac19c0d4b6f7

Either we add more footprint in the XML or we don't save the descriptions.

P.S.: In ABAP 7.5, the method descriptions/help are in the source code: https://blogs.sap.com/2015/10/21/new-abap-doc-features-with-netweaver-75/

**Comment by larshp** [comment]
Can you put the code in a branch somewhere? It makes it easier to try out

I guess the update of the database table was successful? And something else removed the entries, or?

**Comment by EduardoCopat** [comment]
>Can you put the code in a branch somewhere? It makes it easier to try out

https://github.com/EduardoCopat/abapGit/blob/method-description-simple-xml

> I guess the update of the database table was successful? And something else removed the entries, or?

using `MODIFY` the entries were inserted, but probably something else override them (activation?)

**Comment by larshp** [comment]
seems to work for me, however I cannot figure out how function module SEO_CLASS_TYPEINFO_GET works, suggest just selecting directly from database table SEOCOMPOTX instead of calling the function module. This will also fix attribute + type descriptions.

Also it could be nice if the row is not included in the XML if the description is empty, and a check to only add the descriptions table to the xml if it contains rows

**Comment by EduardoCopat** [comment]
I will test it again then.. do not merge this request yet :)

**Comment by EduardoCopat** [comment]
@larshp I could make it work now using Function Module `SEO_METHOD_MODIFY`. Check an example XML here: https://github.com/EduardoCopat/abap-sandbox/blob/master/zec_d_class.clas.xml

Only the descriptions are added. Is it better? 

Do note pull request yet, because I still need to somehow put this under test, do refactorings (e.g. only add if description is there).

**Comment by larshp** [comment]
will it also work for attribute and type descriptions?

**Comment by EduardoCopat** [comment]
>will it also work for attribute and type descriptions?
No. Unfortunately only methods. We can open a new issue for this.

**Comment by larshp** [comment]
did a bit of testing, have one class with one method, however nothing is returned from `SEO_CLASS_TYPEINFO_GET`, which SAP version are you testing on? Perhaps it has something to do with ADT?

I am also afraid that `SEO_METHOD_MODIFY` will regenerate the ABAP class source, but have not been able to test it.

**Comment by larshp** [comment]
Did a quick and dirty solution, take a look at https://github.com/larshp/abapGit/pull/480

Comments for solution in PR 480:

a: bad since it updates the table directly
b: works with method + types + attributes descriptions
c: In the future I think the descriptions are going away, it will move towards ABAP Doc. So it might be okay not to have a perfect solution for these descriptions
d: This will not interfere with any ADT logic

**Comment by EduardoCopat** [comment]
a: Yes. I was trying to use APIs instead of direct SQL statements
b: That is better
c: indeed
d: I don't think it has to be with ADT. I still need to check the system version.
e: Yes

So, should we cancel this PR and merge #480  instead?

**Comment by larshp** [comment]
#480 instead: I think so. I would prefer the APIs but it looks like a lot of work, and it is _only_ descriptions, which ABAP is moving away from

@sbcgua do you have an opinion on this?

**Comment by sbcgua** [comment]
Not anything certain. In term of implementation - I don't know those internals well. In terms of descriptions in general: yeah, it feels incomplete without them, but also those texts are not exposed to users so doesn't seems really critical to me. API vs INSERT: nothing to add, indeed for texts maybe this is OK to insert ... similar code for MSAG exists for example ... of course API would be better if works.

**Comment by larshp** [comment]
@EduardoCopat I think we should go ahead and merge #480, is this okay with you?

**Comment by EduardoCopat** [comment]
@sbcgua thanks for the inputs

@larshp absolutely. No problems at all.

**Pull request closed without merging**
