### PR TITLE
CHAR: fix package popup during pull #1661

### PR DESCRIPTION
**Pull request by christianguenter2**
#1661 

tested with https://github.com/abapGit-tests/CHAR

### CODE REVIEW

**Comment by larshp** [comment]
hmm, there are multiple places where SET PARAMETER is used, https://github.com/larshp/abapGit/search?q=%27EUK%27&unscoped_q=%27EUK%27

**Comment by christianguenter2** [comment]
hm, they seem to work?

**Comment by christianguenter2** [comment]
I think we have the issue also at the other places. The error occurs always when there is another object deserialized before which uses the import/export mechanism in RS_CORR_INSERT. 
E.g. when a package is deserialized before.

The import/export mechanism seems to be more reliable to me. I'd suggest to change the other places as well.

**Comment by larshp** [comment]
hmm, looks like EXPORT is the better option

suggest refactoring the EXPORT to a method in the superclass, then we can change the existing SET PARAMETER calls to use that method instead in follow up PRs

**Comment by larshp** [comment]
cool 🎺

**Comment by larshp** [comment]
Tested ok, 

Part around refactoring moved to https://github.com/larshp/abapGit/issues/1690

**Pull request merged**
