### PR TITLE
local dot abapgit state #630

### PR DESCRIPTION
**Pull request by larshp**
fixes https://github.com/larshp/abapGit/issues/630 local .abapgit.xml state, including migration so all repositories are migrated automatically

Tested following ok:
* create new offline
* clone online
* create new empty online
* export package to zip
* export files to zip
* online project staging, add ignore file
* migration of online project
* migration of offline project
* offline import zip -> set dot abapgit
* update local abapgit on pull

after this is merged then https://github.com/larshp/abapGit/issues/227 can be started

### CODE REVIEW

**Comment by larshp** [comment]
@sbcgua do you have time to take a look?

**Comment by sbcgua** [comment]
I'll try to have look later today (or maybe tomorrow).

**Comment by sbcgua** [comment]
Checked the code, but will do some testing tomorrow. Looks good imho except one thing: `handle_stage_ignore` sets new state of .abapgit (`set_dot_abapgit( lo_dot_abapgit )`). I'd say it is too early and should be done after successful commit. Stage is stateless in AG. Example of potential issue: I click ignore, go to commit page and then change my mind and go back - the ignored file will not be in the list anymore ! I'd have to go to DB utils (or future settings page).

**Comment by larshp** [comment]
hmm, yeah, however I dont think there is any easy fix

**Comment by sbcgua** [comment]
From the top of my head: as `lcl_dot_abapgit` is not `create private` anymore then stage can create a copy of repo's .abapgit, add ignores there, serialize and add to the stage list (add or update existing) - this would happen in `handle_ignores`. And then somewhere at the end of the push there should be a check if .abapgit was in stage and if yes - deserialize and "set" it ... something like this. Maybe a copy instance can even travel with stage structure or class instance ... but not sure, don't remember that code, but then it will be even easier for the push part.

**Comment by sbcgua** [comment]
Or move ignore feature to .abapgit settings page ... controversial though and more to do from now definitely ;)

**Comment by larshp** [comment]
👍 will take a look tonight

**Comment by larshp** [comment]
handle_stage_ignore is called just before the push,

```abap
    handle_stage_ignore( io_stage ).

    lcl_git_porcelain=>push( EXPORTING is_comment       = is_comment
                                       io_repo          = me
                                       io_stage         = io_stage
                             IMPORTING ev_branch        = lv_branch
                                       et_updated_files = lt_updated_files ).
```

so I guess this is okay. Tested adding ignore in stage going to commit and cancel, the ignored is not saved until push

**Comment by sbcgua** [comment]
:warning: long read follows :)

**set_dot_abapgit**
Yeah, true. I missed that.
But I would still move it after push :) Somewhere near `update_local_checksum`
Managed to do the case: add ignore, push, but "forgot" password and so rolled back - ignore was added to local .abapgit and did not appear in stage page anymore (if reenter it from main). Although .abapgit shows up at the stage in this case ... but still this is unintended state change.

A very straight forward solution: return `lv_add` from `handle_stage_ignore` and `if lv_dag_changed ... set_dot_abapgit`. (not ideal though ... another option is just resave it every time ... maybe even better)

**Another issue: If I change DB page** the local .abapgit is not reloaded (even after repo refreash). This is a separate issue though - it is more to post-handling of DB changes than to local .abapgit feature itself.

**Another one: if I zip the package** I have as repo then just default .abapgit is saved. Not the one from repository. Not sure it is a bug itself. But maybe some place for process/UX improvement. Maybe `package to zip` should  check if this package has repo or maybe a repo advance commands has to have own save to zip ... probably a separate issue too. 

One **migration issue**: system has private repos. Migration converts all repos. And asks for password. What if user doesn't know the password? If I cannot enter the password the exception raises 'blah blah 401' and blank screen remains so I cannot proceed further anyhow. I'd say exceptions should be catched in migration and a list of failed repos should be shown at the end with approprate exception texts (e.g. repo XXX failed to update due to exception YYY)

**Comment by larshp** [comment]
I'd say the 3 first issues are minor, we can fix these later if needed

Migration issue:
We can add a lot of code to handle this gracefully, however I think this is overkill. Worst case the user can roll back to a old version or reinstall abapGit.
It shows up with error "HTTP 401, unauthorized" if the user does not know the password, I guess most users knows the passwords for all repos, I hope they can find someone. Worst case just empty database table ZABAPGIT and start from scratch, most state is stored in the git repository.

**Comment by sbcgua** [comment]
Well, yes, nothing major for sure. So then it works :)

**Comment by larshp** [comment]
if passwords during migration turns out to be a problem(issues submitted) then we can implement extra logic 😄

**Pull request merged**
