### PR TITLE
Add action column to repo overview

### PR DESCRIPTION
**Pull request by FreHu**
#3551 #3266

Added commands to the main page, which are faster as they allow you to skip going to repo first.

todo:

*   change remote?
*   remove?

### CODE REVIEW

**Comment by mbtools** [comment]
I like the idea of "actions" on the overview page. "Pull" (i.e. update) would be my wish. Ideally with some job to check if there's an update available (not a diff scan but a version lookup - separate topic). I do a lot of testing, so "uninstall" would be nice, but probably not relevant for many others. Maybe we end up with some settings like for hotkeys where users can pick the actions they want to see on the overview.

On the overview, I think refresh (check for diffs), syntax check, and CI (and possibly others) should be "bulk actions": select multiple repos via checkbox, then trigger the action. Results should then be shown as icons (for each selected repo): are there any diffs? are there syntax errors? did CI run successfully?

**Comment by FreHu** [comment]
Added pull, atlhough it is currently a bit mysterious without knowing the repo state. The rest are great suggestions, but there's more work involved. I'll create issues for them.

*   Background operations
*   Checkboxes + syntax check/inspector as actions on selected items
*   Diffs/status column

**Comment by sbcgua** [comment]
after-thoughts: Pull vs Stage ... Stage also "blind" at this screen ... but Stage is cancellable - so it is ok

**Comment by sbcgua** [comment]
aaah, hover actually brings the bg dows to grey ...
image

**Comment by mbtools** [comment]
Or make it two lines:

image
(from WordPress Plugin page)

**Comment by mwwhitted** [comment]
I like the WordPress plugin idea!

Thanks!
Mark

**Comment by mbtools** [comment]
Not being able to cancel "pull" is another issue maybe.

There will be many links on the screen. maybe show them for the current line "on hover" only

**Comment by FreHu** [comment]
### Action button placement

All the actions should be in the table header like the repo page, but operate on the selected repo. Selection would be either through line highlight, radiobutton or checkbox (later).

But to navigate to the repo, there should be an arrow, like this:

image

### Pull

I'll remove pull for now. 

In the future I think pull should be a page which combines all the popups that appear, lets you make a selection and continue/cancel.

### Maybe don't have syntax check for now?

You can always have syntax check be part of your code inspector variant so I guess it could go. 

This would only leave `Code Inspector | Stage | Patch` (i'll put code inspector first as you should check the code first).

**Comment by sbcgua** [comment]
@FreHu did you finish the changes from the latest comment ? I though you mention you agree to remove pull for now but the code in unchanged.

Other suggestions (from Action button placement): these are good ideas, need some experimenting I guess. E.g. I would personally switch to repo based on any click on the table row - this is really most typical action and imho should most optimized. But there are some cons too: will work with JS only, cannot navigate easily to pkg and repo (I never use it by the way ... so for me it's ok, but needs more opinions for use cases).

**Comment by FreHu** [comment]
All done. This is the final version:

**Pull request merged**
