### PR TITLE
Improve UX of object limit bottom line, #566

### PR DESCRIPTION
**Pull request by sbcgua**
to #566

(screenshot is in the issue)

### CODE REVIEW

**Comment by sbcgua** [comment]
"src/zabapgit_view_repo.prog.abap[193, 11] - Parser error(Unknown statement)"

Strange.

**Comment by larshp** [comment]
bug in abaplint, currently it does not handle nested string templates, https://github.com/larshp/abaplint/issues/84

**Comment by larshp** [comment]
workaround: suggest changing the ABAP code so it does not contain nested string templates

**Comment by sbcgua** [comment]
done

**Pull request merged**
