### PR TITLE
Issue 3042: Error author regex

### LINKED ISSUE #3042: Error author regex
For abapGit itself, trigger Tag -> Switch, gives following error

image

### LINKED ISSUE #3069: Add unit tests for author regex
Maybe this is a good point to introduce unit tests for that regex?

_Originally posted by @christianguenter2 in https://github.com/larshp/abapGit/pull/3067#issuecomment-554070478_

### PR DESCRIPTION
**Pull request by mariusraht2**
Closes #3042: Error author regex
Closes #3069: Unit Tests for author regex

### CODE REVIEW

**Comment by larshp** [comment]
please add the tests locally in src/zcl_abapgit_branch_overview.clas.testclasses.abap

**Comment by mariusraht2** [comment]
I'm still having a little trouble with the assignment of the is_author method. It belongs in my opinion to the commit class but currently we don't handle commits (and also branches) as objects rather than as types - IMHO we should change this. Normally there is class that handles the object and one for a list of these objects. 

At the moment I tend to rename the method to extract_commit_author, move the related source code from branch_overview to the utils method, move the test methods to this class too and check if theexception is being thrown or not. I don't like the idea that there's a method like is_author which is only used for the assertion checks and not productively within the program itself even once..

**Comment by mariusraht2** [comment]
@larshp Ok, I can't resolve the abapLint checks:
1) Yes, special characters are not 7 bit ascii but abap can execute them nonetheless and should as we experienced in the test case.
2) I think the definition of the local class is indeed not at the top because it was added to the global class zcl_abapgit_utils but (how) can I change this?
3) Don't know what that suppose to mean: "Missing space between string or character literal and parentheses, Parser error" - source code looks good to me with plenty spaces^^.

**Comment by larshp** [comment]
for `').` please change to `' ).`

**Pull request merged**
