### PR TITLE
ENHO: hook_impl support

### PR DESCRIPTION
**Pull request by VishnAndr**
lcl_object_enho : hook_impl now supported and fixed issue in lif_object~exists method

### CODE REVIEW

**Comment by larshp** [comment]
looks good, few minor things will fix in next commit

**Comment by VishnAndr** [comment]
Do you mind to point out which ones please? Preparing one more request with switches and BFs. So can fix them then.

**Comment by larshp** [comment]
fixed in https://github.com/larshp/abapGit/commit/89e3e396eefb46baca814d4d1333cbc23fbb7398

removed some "EXPORTING", changed some exceptions to be propagated instead of catching

**Comment by VishnAndr** [comment]
Thanks! 👍

**Comment by larshp** [comment]
btw, if you have https://github.com/larshp/abapOpenChecks installed, you can run 
https://github.com/larshp/abapOpenChecks/wiki/ZCL_AOC_CHECK_30
and
https://github.com/larshp/abapOpenChecks/wiki/ZCL_AOC_CHECK_16

one day I'll add a code inspector variant using https://github.com/larshp/upDOWNci but havent gotten around to it yet. Will also setup https://github.com/larshp/abaplint for this abapGit when its in a better state

**Comment by VishnAndr** [comment]
Great! I will use it for sure. However, Code Completion in Eclipse (shift+enter) knows nothing about these checks. Seems that my patterns should be adjusted.

**Pull request merged**
