### PR TITLE
Add format for *.abap

### PR DESCRIPTION
**Pull request by mbtools**

### CODE REVIEW

**Comment by flaiker** [comment]
Uhm, won't this cause the following issue?

- Clone abapGit on Windows with core.autocrlf=true
- Open a .abap file with an editor that supports editorconfig
- Editor will find a missmatch between the git generated CRLF files and the LF setting in editorconfig
  - And maybe convert the line endings?
  - New files will be created with LF
- git commit will be surprised there are no CRLF line endings to convert to LF

**Comment by mbtools** [comment]
First, let's make clear to others reading this that the discussion does **not** apply to using abapGit. It's only relevant if you download and edit files locally and add them back to the repo (or zip and then repo). 

If you work locally (outside ABAP), then you're responsible for the setup i.e. how things are checked in/out and how your editors work. 

If I understand it right, for abapGit repos local gits should be configured with
`
$ git config --global core.autocrlf input
`
"This setup should leave you with CRLF endings in Windows checkouts, but LF endings on macOS and Linux systems and in the repository."
https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration

I assume if you save it on Windows with just LF (as recommended by editorconfig), then the upload should work just fine. But maybe someone who actually has this setup can config.

**Comment by larshp** [comment]
newlines are difficult 😄 thinking of adding a rule in the linter to enforce one style of line breaks

**Comment by flaiker** [comment]
Tested with the VSCode editorconfig extension. Git clone with autocrlf=true gets the files with CRLF. VSCode will then change _on save_ the line endings to LF of a single file. Which seems very weird to me as you then have a mixed directory. Surprisingly git diff seems to handle that mismatch just fine and does not report any diffs based on line ending changes. I did not test commit/push.

**Comment by mbtools** [comment]
But why would you set autocrlf (changing away from LF), if you use editorconfig already (which ensures proper LF)? 

I think we agree that the ideal way is that every place uses LF. So our recommendation should be to use an editor that supports editorconfig (then we are sure it matches what abapgit needs) or to set the local editor accordingly (on Windows and possibly Mac). The autocrlf just confuses things in my view.

My point is that in the end, we can't control what users do locally. But we can give recommendations and make clear what's expected for abapGit.

**Comment by flaiker** [comment]
> But why would you set autocrlf (changing away from LF), if you use editorconfig already (which ensures proper LF)?

Historically not all tools on Windows can handle LF. For example notepad.exe just recently got LF support. I remember Visual Studio not supporting anything other than CRLF at all (might have changed). But to avoid any conflicts the easiest is to just use the default for your operating system. And autocrlf handles this nicely accross all repositories and platforms and editors at file system level with a global setting. _Unless you have this editorconfig setting which makes things behave differently depending on the tool you use_. As you say it then makes sense to disable autocrlf, but only at project level, so you have to change your settings depending on the editorconfig support of the tool you are using and the setting in the specific repository.

> I think we agree that the ideal way is that every place uses LF.

Sure. You could also easily argue everything should be CRLF though and there also wouldn't be a problem, right? ;)

> So our recommendation should be to use an editor that supports editorconfig (then we are sure it matches what abapgit needs) or to set the local editor accordingly (on Windows and possibly Mac). The autocrlf just confuses things in my view.
> 
> My point is that in the end, we can't control what users do locally. But we can give recommendations and make clear what's expected for abapGit.

I guess the options are:

- Either recommend using autocrlf=true on Windows, which does the thing we want and is mentioned in many Git getting started guides for Windows users (and is also the default setting when installing Git for Windows) and maybe ensure the users did the right thing by CI and a linter rule
- Or recommend not using autocrlf on Windows for this specific repository and to not use any tools that do not support LF and to not use any tools that do not support editorconfig

Maybe my state of knowledge is also outdated. I saw you can also set `* text=auto` in the .gitattributes file per repository and not rely on a user level setting instead (avoiding the editorconfig support problem).

What was the problem again that we are trying to solve? Was it the ZIP file upload scenario?

**Comment by mbtools** [comment]
https://github.com/larshp/abapGit/issues/3676. The question is how abapGit deals with files in online or offline repos that contain CRLF. 

This editorconfig change will ensure that supported editors will handle *.abap files as expected by abapGit. That's all.

**Comment by larshp** [comment]
I'm not really sure about this change, but guess we can try merging

**Pull request merged**
