### PR TITLE
CHDO change document object #802

### PR DESCRIPTION
**Pull request by jrodriguez-rc**
New class zcl_abapgit_object_chdo for CHDO object types.
Some changes were done to existing code:
- New method `is_generated` in `zcl_abapgit_objects_super` that checks generated indicator from TADIR
- New method `read_obj_type` in `zif_abapgit_tadir` (implemented in `zcl_abapgit_tadir` and test classes `zcl_abapgit_file_status` and `zcl_abapgit_injector`) to read all object types from a package from TADIR
- Object types PROG, TABL and FUGR are not serialized if they are generated by CHDO. This check is implemented in `exists` method

CHDO object generates dependent objects (PROG, TABL and FUGR) at pull calling `AFTER_IMP_CHDO` function

### CODE REVIEW

**Comment by larshp** [comment]
I'm worried about performance with this change, the TADIR lookup is expensive

**Comment by jrodriguez-rc** [comment]
I know...
Could be possible to load TADIR when the repository is loaded (or refreshed) and use them cached?

**Comment by jrodriguez-rc** [comment]
What do you think about this?
Instead of including logic in `exists` method, when the repository is loading files in `zcl_abapgit_file_status->status` I can determine first generated objects by CHDO and fill `it_filter` tab to pass to `io_repo->get_files_local`
Determining filter tab could be a new method before calling `zcl_abapgit_file_status->status`

**Comment by jrodriguez-rc** [comment]
Or... it can be done directly in `zcl_abapgit_repo->get_files_local`, between reading TADIR and applying filter, to avoid perform two selections to TADIR

**Comment by larshp** [comment]
actually its not so bad, because the expensive TADIR select is only performed if the generated flag is set

**Comment by jrodriguez-rc** [comment]
Yes, but in a project, with 10 CHDO the selection is performed 60 times (4 includes, 1 function group and 1 structure)

**Comment by jrodriguez-rc** [comment]
I'll close it while I move filter of generated objects

**Comment by larshp** [comment]
oh, okay

also suggest avoiding REDEFINITION, composition over inheritance

**Comment by jrodriguez-rc** [comment]
I removed logic from each class (PROG, FUGR, and TABL) and implement new method `zcl_abapgit_repo->apply_filter_generated_tadir`
I call this method from `zcl_abapgit_repo->apply_filter`
PROG, FUGR, and TABL changes were reverted, but I left the method `zcl_abapgit_objects_super->is_generated` and `zif_abapgit_tadir(zcl_abapgit_tadir)->read_obj_type`. They are not called but could be useful, but I can delete them if you prefer.

**Comment by larshp** [comment]
suggest extracting methods apply_filter + apply_filter_generated_tadir to a new global class, the repo class is too cluttered already

and delete methods that are not in use

**Comment by jrodriguez-rc** [comment]
Done, deleted unused methods and filter logic moved to a new class `zcl_abapgit_repo_filter`

**Comment by larshp** [comment]
thanks, can you help submitting a PR with an example to https://github.com/abapGit-tests/CHDO ?

**Comment by jrodriguez-rc** [comment]
Yes, PR is ready

**Comment by larshp** [comment]
thanks

we should clear the following fields during serialization,
```
      <AUTHOR>DEVELOPER</AUTHOR>
      <UPDNAME>DEVELOPER</UPDNAME>
      <DEVCLASS>$TEST_CHDO</DEVCLASS>
```

and if required, and fill them again during deserialization

**Comment by jrodriguez-rc** [comment]
I did it, I clear the fields and set only DEVCLASS in deserialization

**Comment by jrodriguez-rc** [comment]
I need to do more checks, I'm importing a package into an NPL system and CHDO is not importing because of some errors

**Comment by jrodriguez-rc** [comment]
The error is not directly related to this development. It was because of the created package has the original system SAP instead of NPL, this causes some errors, an example I can't uninstall the package because of some objects check the TADIR original system

**Comment by larshp** [comment]
@jrodriguez-rc okay, can you open a new issue with the error? then we can merge this PR and look into solving the issue separately?

**Comment by jrodriguez-rc** [comment]
No problem, I checked some issues trying importing/uninstalling a repository

**Pull request merged**
