### PR TITLE
Skip object types

### PR DESCRIPTION
**Pull request by jrodriguez-rc**
New interface to perform checks to object types.

Now I included a check to skip serialization of objects.

This should be needed [CHDO](/jrodriguez-rc/abapGit/tree/CHDO-Change-Document-Object-%23802) object type, to skip serialization of function group and includes, which are generated automatically when CHDO is imported

### CODE REVIEW

**Comment by jrodriguez-rc** [comment]
I created a new interface instead of changing zif_abapgit_object to avoid modify all object type classes

**Comment by larshp** [comment]
hmm

**Comment by larshp** [comment]
will it work by using the `EXISTS` method instead, and implement the logic in there?

**Comment by jrodriguez-rc** [comment]
Yes, you're right, I can implement checks in `EXIT` method.
Thank you.

**Pull request closed without merging**
