### PR TITLE
abapOpenCheck - Naming Conventions revision #3239

### PR DESCRIPTION
**Pull request by jrodriguez-rc**

### CODE REVIEW

**Comment by jrodriguez-rc** [comment]
Pending:

Description | Check | Object Name | Line Number
-- | -- | -- | --
Bad naming, expected IO_, got IX_ERROR | Prefix Naming Conventions | ZIF_ABAPGIT_GUI_ERROR_HANDLER | 4
Bad naming, expected C_, got CO_RUN_MODE | Prefix Naming Conventions | ZCL_ABAPGIT_CODE_INSPECTOR | 44
Bad naming, expected C_, got   CO_STARTING_BEACON | Prefix Naming Conventions | ZCL_ABAPGIT_DIFF | 6
Bad naming, expected C_, got CO_XML | Prefix Naming Conventions | ZCL_ABAPGIT_ECATT_HELPER | 35
Bad naming, expected C_, got   MC_HOTKEY_INTERFACE | Prefix Naming Conventions | ZCL_ABAPGIT_HOTKEYS | 24
Bad naming, expected C_, got   GC_SECTION_TEXT | Prefix Naming Conventions | ZCL_ABAPGIT_MESSAGE_HELPER | 8
Bad naming, expected C_, got   GC_SECTION_TOKEN | Prefix Naming Conventions | ZCL_ABAPGIT_MESSAGE_HELPER | 14
Bad naming, expected C_, got CO_NAME | Prefix Naming Conventions | ZCL_ABAPGIT_OBJECT_ECATT_SUPER | 46
Bad naming, expected C_, got   CO_DEFAULT_VERSION | Prefix Naming Conventions | ZCL_ABAPGIT_OBJECT_ECATT_SUPER | 50
Bad naming, expected C_, got   ATTRIB_ABAPGIT_LEADIG_SPACES | Prefix Naming Conventions | ZCL_ABAPGIT_OBJECT_SSFO | 14
Bad naming, expected C_, got   TRANSOBJECTTYPE_CLASS | Prefix Naming Conventions | ZCL_ABAPGIT_OBJECT_SUSC | 8
Bad naming, expected C_, got CO_VIEWCLASS | Prefix Naming Conventions | ZCL_ABAPGIT_OBJECT_VIEW | 17
Bad naming, expected C_, got GC_ZIP_EXT | Prefix Naming Conventions | ZCL_ABAPGIT_TRANSPORT_MASS | 113
Bad naming, expected C_, got   GC_AUTHORIZATION | Prefix Naming Conventions | ZIF_ABAPGIT_AUTH | 5
Bad naming, expected C_, got GC_STEP_ID | Prefix Naming Conventions | ZIF_ABAPGIT_OBJECT | 13
Bad naming, expected C_, got   GC_XML_VERSION | Prefix Naming Conventions | ZIF_ABAPGIT_VERSION | 4
Bad naming, expected C_, got   GC_ABAP_VERSION | Prefix Naming Conventions | ZIF_ABAPGIT_VERSION | 5

**Comment by jrodriguez-rc** [comment]
I can release this PR and another with constants

**Comment by larshp** [comment]
yes please, and move the pending to the issue, so we track the progress of the issue in the issue

**Comment by larshp** [comment]
and please delete file sci_config/ABAPGIT.xml from the PR, it will be a mess to keep it properly in sync with the abaplint config

**Comment by jrodriguez-rc** [comment]
Deleted the folder

**Comment by larshp** [comment]
looked through code, looks okay

pulled successfully, no new syntax errors

thanks 👍

**Pull request merged**
