### PR TITLE
Enable the relocation of class/intf between packages - #2706

### PR DESCRIPTION
**Pull request by arcanist123**
Enables the relocation of class/intf between packages. Probably resolves some other issues with the classes like reimport of enhancemens, etc.
Resolves the https://github.com/larshp/abapGit/issues/2706

### CODE REVIEW

**Comment by arcanist123** [comment]
Hi.
May I understand the reason of closing this? Was the change undesired/not correctly documented/replaced with some other changes?
Regards

**Comment by larshp** [comment]
reopening, but I dont think it works

**Comment by larshp** [comment]
fm SEO_CLASS_* should not be needed to relocate to a different package, plus we need a generic solution that works for all object types

**Comment by larshp** [comment]
closing, see comment in https://github.com/larshp/abapGit/issues/2706

**Pull request closed without merging**
