### PR TITLE
Pass log to deserialization API and show log

### PR DESCRIPTION
**Pull request by mfsap**
Interface ZIF_ABAPGIT_LOG is now passed for deserialization API.

This includes:
- Log messages for FUGR: Imported function modules and includes
- Improved error messages for TABL compare
- Log objects w/o changes
- Log is shown in the UI if available ("Log" entry appears if a log exists, no persistence!)
This PR enhances #2534 and #2694

Another important change: In case an object fails (or a single function module in a group fails), the import continues with the next object. Currently no error message is shown - I guess the log should be highlighted in case of an error!

Screenshot after "Pull" was triggered (red frame only in screenshot!):
image

When pressing the "Log" button, a simple message list appears (re-use of existing log UI):
image

### CODE REVIEW

**Comment by larshp** [comment]
As usual, suggest trying to split into more PRs, eg table compare, FUGR changes could be separate follow up changes.

Comments:
A: method `get_log`, have it RETURN a structure with the 2 fields? or better add title as an optional member in the log object and as part of constructor?
B: for the comparator object, would it be an idea to add log as optional input to the constructor?
C: `METHOD filter_files_to_deserialize`, logging is secondary but now takes up most of the code, need to consider how this can be refactored
D: We need to make the user aware when errors occur, not hide it behind menu option, cannot merge until this part is fixed

**Comment by mfsap** [comment]
I agree to the changes and they all makes sense, thanks Lars!
Unfortunately I'll not be able to split and enhance the PR in the next weeks due to an (temporary) organizational shift. Please be patient...

**Comment by mfsap** [comment]
Regarding D) Errors and warnings after a pull are now part of the “message list” above the object list in the main screen and will be shown immediately:
image

The new “Log” button shows errors, warnings and success messages on demand.

Regarding A) With the last commit, I also moved the log title to the log interface and the `get_log` method does only return the log interface.

Regarding B) Nothing changed so far. If required, a new PR may change this. 

Regarding C) This is right, now most of the coding is used for logging. But the logging code is separated into "blocks with comments". If a refactoring is required, I would also recommend a new PR.

**Comment by larshp** [comment]
moved follow up tasks to https://github.com/larshp/abapGit/issues/2750, merging

**Pull request merged**
