### PR TITLE
DOMA: Clear VALPOS to show the right diff

### LINKED ISSUE #1053: DOMA: consider clearing VALPOS
If the domain contains a lot of fixed values, and then inserting a new value in the top, it will trigger a very long diff due to the VALPOS field.

The value position is implicitly part of the XML, so we should consider clearing the VALPOS field

### PR DESCRIPTION
**Pull request by mariusraht2**
Closes #1053

Related to PR #3094

### CODE REVIEW

**Review by larshp — CHANGES_REQUESTED** [review]
For the texts, if not all values are translated, how does it find the value corresponding to the translated text?

image

**Comment by mariusraht2** [comment]
If there's a translation for a value it finds it by DOMVALUE_L or its absence and sy-langu. The example you chose is a fixed empty value - in your example the attribute DOMVALUE_L has been suppressed because of that. But fixed values can't occur twice so it's not possible to have multiple translated entries with an empty value (keyfield). 

image
-> not activatable

XML:
image

**Comment by mariusraht2** [comment]
If there's a translation for a value it finds it by DOMVALUE_L or its absence and sy-langu. The example you chose is a fixed empty value - in your example the attribute DOMVALUE_L has been suppressed because of that. But fixed values can't occur twice so it's not possible to have multiple translated entries with an empty value (keyfield). 

image
-> not activatable

XML:
image

**Comment by mariusraht2** [comment]
If there's a translation for a value it finds it by DOMVALUE_L or its absence and sy-langu. The example you chose is a fixed empty value - in your example the attribute DOMVALUE_L has been suppressed because of that. But fixed values can't occur twice so it's not possible to have multiple translated entries with an empty value (keyfield). 

image
-> not activatable

XML:
image

**Comment by larshp** [comment]
ie. the solution does not work

**Comment by mariusraht2** [comment]
@larshp Just want to make sure: But you saw the added DELETE of empty untranslated right? It didn't still work then? After I added it it worked for me

**Pull request closed without merging**
