### PR TITLE
Make error messages from ENHS clearer

### PR DESCRIPTION
**Pull request by ed-holland**
Issue #3628

### CODE REVIEW

**Comment by mbtools** [comment]
Works, but wouldn't this work too?

```
CATCH cx_enh_root INTO lx_enh_root.
  zcx_abapgit_exception=>raise( iv_text = lx_enh_root->get_text( )   " or get_longtext( )
                                ix_previous = lx_enh_root ).
```

**Comment by ed-holland** [comment]
The text would not show the exception from what it is raised. It would be generic.
The ix_previous helps if you do it in the gui as one can go to the originating exception.
In background, you only have the message.

It is a bit more work, but the issue became much clearer to me. I was having problems with an ENHS from SAP (which does not have an active version). It really raised an IO Error.

**Comment by mbtools** [comment]
Try this for fun https://github.com/mbtools/abapgit-test-exceptions ;-)

**Comment by ed-holland** [comment]
With the help of your example, i was able to create this:
image

image

Is there an easier way to get the name of the exception?

**Comment by ed-holland** [comment]
Closing as it is replaced by #3651

**Pull request closed without merging**
