### PR TITLE
STVI, Transaction variants

### PR DESCRIPTION
**Pull request by goreraks**
Read API RS_HDSYS_READ_TC_VARIANT_DB
Delete API RS_HDSYS_DELETE_VARIANT
No JUMP support available
#3174

### CODE REVIEW

**Comment by larshp** [comment]
Thanks, can you help submitting a simple example to https://github.com/abapGit-tests/STVI ?

regarding code see comments in https://github.com/larshp/abapGit/pull/3307

**Comment by goreraks** [comment]
Example added, see pull request https://github.com/abapGit-tests/STVI/pull/1

**Comment by goreraks** [comment]
User details are handled. Also see the updated https://github.com/abapGit-tests/STVI/pull/1.

**Comment by larshp** [comment]
check conflicts, the SCVI files should not be part of the PR

**Comment by larshp** [comment]
👍

**Pull request merged**
