### PR TITLE
Display contribution guidelines more prominently

### PR DESCRIPTION
**Pull request by FreHu**
#2726 Moved from deep inside the documentation. I also changed the wording a bit to make it more motivational.

### CODE REVIEW

**Comment by larshp** [comment]
I would like to keep the README as short as possible, suggest adding a very short text with a link to more information.

also consider if https://github.com/larshp/abapGit/blob/master/CONTRIBUTING.md should be referenced/refactored

**Comment by FreHu** [comment]
I didn't notice the file, it wasn't linked to from anywhere. I will move the stuff from the readme there and link it.

**Comment by larshp** [comment]
The GitHub platform shows a link to the CONTRIBUTING file, eg when opening issues and PRs, https://help.github.com/en/articles/setting-guidelines-for-repository-contributors

**Comment by larshp** [comment]
fixed a few minor things

should we still delete most of the text in `docs/collections/_development/guidelines.md` ? I think we should at least link to CONTRIBUTING from the document

**Pull request merged**
