### PR TITLE
Add auth check exit for repo creation

### PR DESCRIPTION
**Pull request by larshp**
Add auth check exit for repo creation, #2519

### CODE REVIEW

**Comment by filak-sap** [comment]
Nice! How we ensure that developers do not add own implementation of ZCL_ABAPGIT_AUTH_EXIT which would allow them to any action?

**Comment by filak-sap** [comment]
Got it, this will prevent non-developer users to "steal" source codes but we generally trust developers because they are (at least, I hope for that) able to steal source codes even without abapGit. Am I right?

**Comment by filak-sap** [comment]
Don't we also need to prevent them from pushing? Because they might be able to change remote URL and push the code to their own repo?

**Comment by larshp** [comment]
Trusting developers is the best thing to do, this exit can help reminding developers what they are supposed or not supposed to do, not provide full security.

We can add more authorization exits over time, this is just another

**Pull request merged**
