### PR TITLE
skip initial xml(#478) and fix newline(#42)

### LINKED ISSUE #42: newline when editing via web interface
align so abapGit removes the newline at end of file, so it matches when editing the files manuallay via github web interface

### LINKED ISSUE #478: XML: omit INITIAL fields
**Problem 1:** would like to decrease the file sizes

**Problem 2**: Diffs shows up in abapGit between AS versions, eg.:

image

**Solution:** in LCL_XML_OUTOUT method add, create a structure dynamically without the fields that are initial, and move the contents to this structure, after this the `CALL TRANSFORMATION id` should still work. Note that this will also be backward compatible

### PR DESCRIPTION
**Pull request by larshp**
fix #478 
fix #42 

note that the change is/should be backwards compatible

before merging:
* create tag

after merging:
* increase minor version
* update changelog
* update XML and ABAP to new format in abapGit repo
* submit pull requests to other major abapGit repositories

### CODE REVIEW

**Comment by larshp** [comment]
@sbcgua did/do you have time to test this?

**Comment by sbcgua** [comment]
1) From code perspectives, nothing to comment :)
2) Tested pull of "old" repo - woked well
3) Commit new XML to repo, delete objects, pull (reset actually) - also worked well

So I think can be merged.

One doubt: I wonder if the may be a case when XML treats field as empty but from domain perspective is not ... some kind of '00' (it is a char then though ...). Probably should be safe however.

One more though: probably it would be a good to think on some kind of 'in-abapgit' announcements. Some 'latest news' frame ... or event giving some warnings before pulling new changes from AG. What do you think ?

P.S. our 400 object project is completely modified with this change :) Showing complete diff dumped ... exceeded max runtime ... lcl_html has space for improvement for sure.

**Comment by sbcgua** [comment]
Just to add that it seem like a very good feature actually. :+1:

**Comment by larshp** [comment]
domain '00': yea, if we find some of these, I'm sure we can make a workaround for special cases

announcements: I do not have any good ideas on how to do it, easiest is just if people follow the github repository and check the commits, they have the full history

**Comment by larshp** [comment]
done

todo: update all existing abapGit based projects to the new format. I have a list of projects using abapGit at http://abaplint.org/

**Comment by flaiker** [comment]
For anyone having branches with unmerged or uncommitted changes in their repos: finish / merge them **before** upgrading to v1.26.0 or chaos ensues...
I just downgraded to v1.25.2 to do just that, FYI

**Comment by larshp** [comment]
yeah, sorry about that 🚢

**Pull request merged**
