### PR TITLE
DSYS serializer overhaul

### LINKED ISSUE #3374: abapGit does not serialize DSYS documents when the name contains a namespace-prefix
When a documentation object (here: a `CHAP` via SE61) has a name that contains a namespace, e.g. `/FOO/DOCU`, abapGit fails to serialize the object.

**Reproduction:**
* Create a namespace, e.g. `/FOO/`.
* Create a development package and (offline) abapGit repository in that namespace.
* Create a CHAP document in that package and include the namespace as a prefix in the document name, e.g. `/FOO/DOCUMENT`.
* Export the package in abapGit.

**Analysis:**
The document created above will have a a TADIR entry of type `R3TR DSYS` with object name `<prefix> 'CHAP' <remainder of document name>`, e.g. `/FOO/CHAPDOCUMENT`. However, in the document storage system, including table DOKIL which is read in the exists-check in `ZCL_ABAPGIT_OBJECT_DSYS`, the document is referred to as `'CHAP' <full document name>`, e.g. `CHAP/FOO/DOCUMENT`. This mismatch causes the exists-check to fail, so abapGit will ignore the TADIR entry entirely.

1. Line 43 here is broken, instead of just removing the leading four chars the constructor must first remove the namespace prefix, if any: https://github.com/larshp/abapGit/blob/840d818b2d6bbb2c80062c3dc557a8e378400445/src/objects/zcl_abapgit_object_dsys.clas.abap#L37-L45

2. The use of `mv_object` in line 118 here is broken, because the TADIR object name is not the same as the object name in the document tables: https://github.com/larshp/abapGit/blob/840d818b2d6bbb2c80062c3dc557a8e378400445/src/objects/zcl_abapgit_object_dsys.clas.abap#L114-L122
   This problem is repeated in most other uses of `mv_object` throughout the class, where that value is passed into the docu system as the document's name.

I'm planning to work on a fix myself, but would be glad if someone with more experience with agapGit and the documentation system could verify these findings. 🙇

### PR DESCRIPTION
**Pull request by Elberet**
The serializer class for DSYS objects has a number of issues, including #3374 and two more problems I encountered while working on a fix:
* most notably, in its current version, the serializer will only interact with version `0001` of the text, even if that is not the active version and/or newer versions exist on the system.
* texts are always handled in the current user's logon language, even if that is not the document's master language.

This PR rewrites the DSYS serializer from the group up using the `longtexts` facility, while retaining the ability to deserialize objects written by the current version of the deserializer. Additionally, texts are always opened in their master language when jumping to the text edit tool.

Closes #3374.
Closes two unreported issues as mentioned above.

### CODE REVIEW

**Comment by larshp** [comment]
any changes to the serialized XML files, will it also work with older serialized XML files?

**Comment by Elberet** [comment]
Yes, the deserializer checks the version recorded in the XML metadata. For `v1.0.0` it uses more or less the same logic as before (but updates the latest version of the document). New XML files are written with metadata version `v2.0.0`.

**Comment by larshp** [comment]
okay

can you help to submit a 1.0.0 example to https://github.com/abapGit-tests/DSYS_old
and the new serialized XML to https://github.com/abapGit-tests/DSYS_new

so we have it for testing and future reference

**Comment by Elberet** [comment]
Done - see abapGit-tests/DSYS_old#1 and abapGit-tests/DSYS_new#1.

**Comment by larshp** [comment]
@goreraks can you help testing this PR?

**Comment by goreraks** [comment]
In logon langauge EN, imported https://github.com/abapGit-tests/DSYS_old/pull/1, document created in DE language but abapGit shows the difference b/w local and remote. is it the correct behaviour?
image

**Comment by Elberet** [comment]
I'm assuming you're using the old version of `zcl_abapgit_object_dsys`, since the serializer version on your diff's local side is still `v1.0.0`.

If so, you're seeing the effect of one of the additional problems I've mentioned in the PR:

> * texts are always handled in the current user's logon language [...]

Basically, on import the document is created in language DE, but it gets compared to language EN because the serializer always tries to read version 1 in your logon language, regardless of what actually exists on your system.

**Comment by goreraks** [comment]
Tested https://github.com/abapGit-tests/DSYS_new/pull/1, works as expected i.e. including the translation of document.
The behaviour observed in my previous comment is also valid for new version v2.0.0 i.e. if the document is created in different language(Master language = true), after the pull request the object shows the difference.

**Comment by Elberet** [comment]
@goreraks can you post the diff you get after importing the v2 XML with the v2 deserializer?

**Comment by goreraks** [comment]
Sorry, the difference is not similar to version 1.0.0 but the difference is with the DOKL-MASTERLANG.
image

**Comment by Elberet** [comment]
Hm, I'll have a look into that when I'm back in the office next week.

It could be that it's impossible to create a document with a master-language that's different from the current logon language, in which case this would be a user-error because the repo's master language doesn't match the document's master language (altho, in all fairness, I probably should have included an `.abapgit.xml` in the test-data PRs).

**Comment by Elberet** [comment]
Yep, as mentioned above: this happens when the log-on language and document language are different. As long as the master lang in `.abapgit.xml` matches the master lang in serialized documents, this should never result in an actual problem. I'll update the test repo accordingly, but I don't think additional code changes are strictly necessary.

**Comment by goreraks** [comment]
I am not sure but seems the behavior is not in sync with the transport import. For example, if the same document is transported to other system then, masterlang would have been updated as 'X'.
One more thing, I think because of the difference, I can also stage the file which would overwrite masterlang in the remote file.

**Comment by Elberet** [comment]
Yes and no. You can do those things right now, because your abapGit repository is using master language EN. If the repository is setup correctly, then abapGit will refuse to pull the document unless you're logged in with the correct logon language; if your logon language is DE, none of these issues appear.

**Comment by larshp** [comment]
yea, sure, always feel free to raise new issues

thanks both 👍

**Comment by esjewett** [comment]
I believe this broke compilation in 7.31 and below. :(

image

**Comment by larshp** [comment]
thanks @esjewett, please open it as a new issue

"In Release 4.0" hmm?

**Comment by Elberet** [comment]
That's what you get for trusting the linter. 😄 

I think we have a 7.02 system for... reasons - but nothing between that and 7.4x; I'll have a look on Monday.

**Comment by larshp** [comment]
I dont have a 702 system, so dont have that option

will fix the linter, one bug at a time

**Pull request merged**
