### PR TITLE
Import BC Sets Very Late

### LINKED ISSUE #2418: SCP1: Not deserialized properly at first time
When installing https://github.com/abapinho/abaK.git business configuration set (SCP1) ZABAK_TABLE_CUSTOMIZING isn't deserialized properly. 

image

image

'Reset Local' then installs the object correctly.

### PR DESCRIPTION
**Pull request by goreraks**
Since the BC Sets have dependency on Table maintenance generation i.e. object type TOBJ, the deserialize step 'ABAP' or 'LATE' will lead to inconsistency. closes #2418 
So the BC Sets are now imported in a new step called 'Final'.

### CODE REVIEW

**Comment by mbtools** [comment]
Thanks for the help, Rakshith.

I don't think we need another step. We already have a place to order the object type deserialization in ZCL_ABAPGIT_OBJECTS->PRIORITIZE_DESER. Is that not sufficient?

Add 
`        AND obj_type <> 'SPC1'`
to the main loop.

And add the following after the loop (before PINF):
```
* SCP1 after everything as it can expose objects
    LOOP AT it_results ASSIGNING <ls_result> WHERE obj_type = 'SCP1'.
      APPEND <ls_result> TO rt_results.
    ENDLOOP.
```

**Comment by goreraks** [comment]
I didn't know, there is a separate method to prioritize object types. Method PRIORITIZE_DESER has now many object types, where the deserialization order is changed within the import step.
Instead of having this special logic for specific object types, I would recommend to move such object types to be imported in "Final" step.
This way, we can get rid of method PRIORITIZE_DESER and the code which does the several LOOP for handling of import order for such object types.

**Comment by larshp** [comment]
for now suggest doing the fix suggested by @mbtools 

and open an issue for RIORITIZE_DESER, it needs refactoring, but its not super easy

**Comment by mbtools** [comment]
My understanding is that "steps" are there so abapGit can "do something" **between** steps (like activate DDIC), not to order object types. 

We eventually need to refactor PRIORITIZE_DESER. Ideally, each object type would define itself, which other objects it depends upon. See https://github.com/larshp/abapGit/issues/3536

Let's change PRIORITIZE_DESER, which is a quick fix for SCP1 without adding more steps.

**Pull request closed without merging**
