### PR TITLE
Local checksums include individual file checksums

### PR DESCRIPTION
**Pull request by sbcgua**
as a prerequisite to #407

### CODE REVIEW

**Comment by sbcgua** [comment]
not sure what the linter actually argues about :)

**Comment by larshp** [comment]
need to look into the linter error, statements inside BEGIN OF should be excluded from the rule

will have very limited time this week

**Comment by sbcgua** [comment]
No prob. I'm also quite loaded these days. Although I spent some time on that `file_status` code - that will be a big commit :)  But will give more information.

Good luck with your presentation :))

**Comment by sbcgua** [comment]
Don't pull yet. There is a tricky bug - file hashes should be updated only for actually updated files in push/pull. And seems to be rather tricky, not sure how to do it yet.
Pls reject it for now, I'll PR the whole  407 code later.

**Comment by larshp** [comment]
rejected for now, @sbcgua will PR the whole #407 later

I'll look into the abaplint error in the meanwhile

**Pull request closed without merging**
