### PR TITLE
Solved: Maximum Number of GUI Session Reached

### PR DESCRIPTION
**Pull request by kuzeydev**
Solved: Maximum Number of GUI Session Reached

### CODE REVIEW

**Comment by kuzeydev** [comment]
> see #2187

I have already review #2187.
The problem is you may not use all threads the user has. Sometimes users have other GUI session active.  You may use only ( MaxThread - ActiveThread ) threads.

**Comment by larshp** [comment]
error "Maximum Number of GUI Session Reached" is not related to the general server setup, but the number of gui sessions allowed for the user. As mentioned in #2187, parallel processing should not take up any gui sessions for the user, if it does there is a bug in the serialization code.

Have you installed SAP note 2759002?

What SAP version are you on?

**Comment by kuzeydev** [comment]
Please check: 
https://help.sap.com/doc/abapdocu_751_index_htm/7.51/en-US/abapcall_function_starting.htm

It says: "... If the destination is not specified and also not defined in a callback routine using the addition KEEPING TASK of the statement RECEIVE, the destination "NONE" is used implicitly. ..."

image

if destination 'NONE' is used then a new user session is opened and It is same as GUI Session..

**Comment by kuzeydev** [comment]
> error "Maximum Number of GUI Session Reached" is not related to the general server setup, but the number of gui sessions allowed for the user. As mentioned in #2187, parallel processing should not take up any gui sessions for the user, if it does there is a bug in the serialization code, not the parallelization.
> 
> Have you installed SAP note 2759002?
> 
> What SAP version are you on?

S4HANA 1809.
After Implementing 2759002, It seems problem is solved. thanks

**Pull request closed without merging**
