### PR TITLE
Serialize ENHS, ENHC

### PR DESCRIPTION
**Pull request by sbcgua**
addressing #269

### CODE REVIEW

**Comment by larshp** [comment]
thanks, looks good, I'll do a few tests tomorrow and then merge if successful

**Comment by larshp** [comment]
hi,
While doing a pull from repository
https://github.com/larshp/CLAS

I get an error: "Error occured while checking ENHS: Enhancement object ENHS ZSPOT cannot be read", in the exists method:

```abap
  METHOD lif_object~exists.
    DATA: lv_spot_name  TYPE enhspotname,
          lv_message    TYPE string,
          li_cx         TYPE REF TO cx_root,
          li_spot_ref   TYPE REF TO if_enh_spot_tool.

    lv_spot_name = ms_item-obj_name.

    TRY.
      li_spot_ref = cl_enh_factory=>get_enhancement_spot(
                    spot_name = lv_spot_name ).
    CATCH cx_enh_root INTO li_cx.
      lv_message = `Error occured while checking EHNS: ` && li_cx->get_text( ).
      _raise lv_message.
    ENDTRY.
```

it looks like exception CX_ENH_IO_ERROR should be caught and return 'rv_bool = abap_false.'

can you have a look?

**Comment by larshp** [comment]
merging, will track issues in #269

**Comment by a-fas** [comment]
Hi Lars, sorry for silence - touch schedule on my project began. My collegue said that the issue was because of param `dark = Х`, but I see that you fixed already. Sorry for late responce.

P.S. abapmerge is awesome ;)

**Comment by larshp** [comment]
no problem :smile:

I did not test all corners of ENHS/ENHC, but I think a few issues has been solved

**Pull request merged**
