### PR TITLE
Show error for main packages

### PR DESCRIPTION
**Pull request by ibnbr**
Show a message to inform that the package is "MAIN" and can not have any objects.

image

### CODE REVIEW

**Comment by larshp** [comment]
thanks, the IF must be changed to "IF methodcall = abap_true.", to work on 702, https://github.com/larshp/abapGit/pull/2955/files#annotation_67174013

closes #2273

**Comment by ibnbr** [comment]
I just corrected, I'm sorry.

**Comment by larshp** [comment]
no problems, CI is in place to find these things, few method implementations missing, see https://github.com/larshp/abapGit/pull/2955/checks

**Comment by larshp** [comment]
Wonder what will happen in this scenario:
The local package is MAIN, but remote is changed to allow for objects and contains objects? It will show the error then?

**Comment by ibnbr** [comment]
I was doing new tests here and the scenario I tested is not good. I will cancel the PR.

**Pull request closed without merging**
