### PR TITLE
Add performance test

### PR DESCRIPTION
**Pull request by flaiker**
Adds the performance test report as a button.

image

image

image

Instead of getting frustrated creating a selection dialog in JS I opted for getting frustrated by using `FREE_SELECTIONS_DIALOG` :)
Maybe it's of some use to somebody else in the future.

### CODE REVIEW

**Comment by sbcgua** [comment]
wow, this is kind of cool ! 💪

**Comment by mbtools** [comment]
We should clarify that it's measuring runtime of the object serializer process only. The end-to-end process including git communication is a different beast. My measurements show a lot of time spent in the ZLIB classes. Too bad that this commonly used compression isn't supported by SAP kernel (cl_abap_gzip).

**Comment by flaiker** [comment]
Should I change the button to `Serialization Performance Test` ?

**Comment by mbtools** [comment]
The menu item is ok. Maybe adapt the title of the popup or add a text field to it (not sure if that works with FREE_SEL...). 

Runtime and Seconds in the screenshot look redundant.

Actually, this could be enhanced to become a more general test tool for all methods of `ZIF_ABAPGIT_OBJECT`. So maybe we combine "Test changed by" and "Performance Test" into "Test Util". Parameter popup fits great. Just needs some way - a dropdown? - to select the interface method to be tested.

**Comment by flaiker** [comment]
See #3770 . Might make more sense as a follow up PR though.

I seem to have broken the deps check in the merged report. I can move the local helper class to a global class which should fix it.

**Comment by flaiker** [comment]
Hmm, moved to global, still failing. Any idea what this means? Are interface signature components not allowed to refer to types defined in classes?


> ../ci/zabapgit_standalone.prog.abap[3173, 7] - Type of "et_object_type_filter" contains unknown: Could not resolve top ZCL_ABAPGIT_PERFORMANCE_TEST, resolveTypeChain (unknown_types)
> ../ci/zabapgit_standalone.prog.abap[3174, 7] - Type of "et_object_name_filter" contains unknown: Could not resolve top ZCL_ABAPGIT_PERFORMANCE_TEST, resolveTypeChain (unknown_types)

**Comment by larshp** [comment]
hmm, I'll have a look tomorrow

**Comment by larshp** [comment]
yea, having the following code in **src/ui/zif_abapgit_popups.intf.abap** doesn't work in the compiled report. Suggest moving the definitions of `gty_object_type_range` and `gty_object_name_range` to the interface(`zif_abapgit_popups.intf.abap`)

```abap
  METHODS popup_perf_test_parameters
    EXPORTING
      et_object_type_filter         TYPE zcl_abapgit_performance_test=>gty_object_type_range
      et_object_name_filter         TYPE zcl_abapgit_performance_test=>gty_object_name_range
```

**Comment by flaiker** [comment]
Moving these performance test specific types to an interface for popups kills UI decoupling in my opinion. I'll just move them to the general definitions interface.

**Comment by larshp** [comment]
thanks 👍

**Pull request merged**
