### PR TITLE
objects: work around the protected redefinition shortdump

### PR DESCRIPTION
**Pull request by filak-sap**
The methods CL_OO_CLASS_SECTION_SOURCE=>SCAN_SECTION_SOURCE calls the
function SCAN_ABAP_OBJECTS_SECTION without the parameter superclsname
which causes that variable scan_result (vse_tabs) holds a broken table of
redefinitions for protected methods which leads into a short dump during
CL_OO_CLASS_SECTION_SOURCE=>REVERT_SCAN_RESULTS.

The problem does not occur for public section because the public section
contains "CLASS ... INHERITING FROM ...", so superclsname gets
populated. It's obvious that the class definition statement is not
present in the protected section.

The crash is reported as DBSQL_DUPLICATE_KEY_ERROR in the program
SAPLSEOR at INSERT_REDEFINITIONS.

The code is the following:

    * first refresh db table
        perform delete_redefinitions
          using inhkey.
        delete adjacent duplicates from redefinitions.
    * insert again
        insert seoredef from table redefinitions.

One might think that the delete statement form clears the table seoredef
but the problem is that the variable inhkey contains the super class
name so no redefinitions are actually removed and the insert statement
attempts to insert the redefinitions without parent class again.

The proper solution is to enhance CL_OO_CLASS_SECTION_SOURCE=>SCAN_SECTION_SOURCE
to pass the super class name to SCAN_ABAP_OBJECTS_SECTION - at least for
the protected section.

However, I am not patient and I am not going to wait for the proper fix
(which the maintainers may refuse).

### CODE REVIEW

**Comment by filak-sap** [comment]
I already attempted to fix the problem in https://github.com/larshp/abapGit/pull/2701 but that PR was completely wrong.

**Comment by larshp** [comment]
heh, dark magic 🕶 

any suggestions on how we can test this? can we add the scenario to a repo under https://github.com/abapGit-tests ?

**Comment by jfilak** [comment]
If you can pull abapGit, then you cannot re-produce the problem - yeah, we are not even able to pull abapGit because there are classes with protected redefined methods (I have been updating abapGit via sapcli last few months).

I will create an abapGit-tests repo. Hold on!

BTW: I consider entire abapGit's (de)serialization code a beyond dark magic - especially the part where you pull classes in Active mode, call Source Scanner and reverts scan results - that part blows up my mind the similar way as when I imagine infinite universe and God orchestrating it ...

**Comment by larshp** [comment]
awaiting abapGit-tests repo

**Comment by larshp** [comment]
lets try to merge it, but beware 💀

**Comment by jfilak** [comment]
Oh dear, I forgot to add the promised test repo :( I hope I can find free time soon .. sorry

**Comment by larshp** [comment]
ref https://github.com/larshp/abapGit/issues/3053

**Pull request merged**
