### PR TITLE
Remove GitHub 2FA implementation

### LINKED ISSUE #3150: Deprecation of GitHub API password based authentication
> Hi @flaiker,
> 
> You recently used a password to access an endpoint through the GitHub API using SAP NetWeaver Application Server (1.0;752). We will deprecate basic authentication using password to this endpoint soon:
> 
> https://api.github.com/
> 
> We recommend using a personal access token (PAT) with the appropriate scope to access this endpoint instead. Visit https://github.com/settings/tokens for more information.
> 
> Thanks,
> The GitHub Team

https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-passwords

https://developer.github.com/v3/auth/

This will break our current 2FA implementation for GitHub. Any ideas for a different approach where no private key is stored on a shared system?

### PR DESCRIPTION
**Pull request by flaiker**
as it relies on a soon to be deprecated authentication mechanism.

Fixes #3150

See https://developer.github.com/changes/2020-02-14-deprecating-password-auth/

### CODE REVIEW

**Comment by flaiker** [comment]
I didn't expect a merge conflict here to be honest. I noticed in abapGit the deletions didn't show up as red deletions but green new files from remote in the staging screen which I found a bit odd.

**Comment by mbtools** [comment]
I noticed the incorrect status icon when deleting, too. but on the staging page you should be able to mark these files as "to be removed" and the result seems to be what's expected.

**Comment by flaiker** [comment]
Huh, just noticed api.github.com is now used for the PR feature. Reverted the commits removing it from the SSL test and docs.

**Comment by flaiker** [comment]
Might be worth mentioning in the changelog popup that you can and should remove any left over generated tokens on GitHub at https://github.com/settings/tokens named "Generated by abapGit".

**Comment by larshp** [comment]
can `zcl_abapgit_2fa_auth_base` and `zcl_abapgit_2fa_auth_registry` also be deleted?

**Comment by flaiker** [comment]
I don't know if there are any custom implementations build by users. These would then also break.

**Comment by larshp** [comment]
hmm, suggest adding a MESSAGE TYPE I, telling the user to post an issue on github if its used, and a comment to delete the classes in 2 months

**Comment by flaiker** [comment]
Is the infrastructure not reusable for the OAuth approach #3766 ? (I don't know how OAuth works...)

**Comment by larshp** [comment]
no, AFAIK its not possible to implement oauth in the current setup

**Comment by larshp** [comment]
thanks 👍

**Pull request merged**
