### PR TITLE
Generic file filter mechanism + DDLS ignore baseinfo when not supported

### LINKED ISSUE #3158: DDLS: Files with Baseinfo (.ddls.baseinfo) do not dissappear from diff
Hi,

after the update to abapGit version 1.92 the `*.ddls.basinfo` files were added to the repository. However, during the pull of the same repository on another system these files do not disappear from the diff.
DDLS_baseinfo_diff_problem
Neither `Reset Local` or `Pull` has removed these files from the diff.

Kindly have a look at this issue. 

Thanks and Regards
Ludwig

P.S.: I am working on NW 7.53 SP03

### PR DESCRIPTION
**Pull request by christianguenter2**
fixes #3158 

**a) File filter** 
A generic file filter mechanism is introduced to filter either
- local files
or
- remote files

Purpose is to mitigate file diffs when repos in systems with different versions are synchronized.

With 
```    
zcl_abapgit_file_filter=>register(
        iv_id          = 'ID'
        io_file_filter = filter_object ).
```
 a new filter can be registered. Where `filter_object` must implement interface `zif_abapgit_file_filter` with its methods `filter_remote_files` and `filter_local_files`.

Custom filter logic can be implemented with the two new exit-methods `filter_remote_files` and `filter_local_files` of interface `zif_abapgit_exit`. 

**b) DDLS filter baseinfo**
When a local NW system doesn't support DDLS-baseinfo the corresponding remote files (*ddls.baseinfo) are ignored and hence no diff is shown

### CODE REVIEW

**Comment by larshp** [comment]
hmm, but diffs are diffs, not showing the diff after a pull might be okay

given the scenario that the user changes the DDLS, and nothing is shown regarding baseinfo, the user commits the new changes in good faith, not having the possibility to check inconsistencies

I'm not exactly sure what the baseinfo is for, in the examples I've seen it just replicates data that is in the other files

**Comment by christianguenter2** [comment]
Yeah, not sure either whether that's a good idea or not.

You mean in the described scenario the next commit will delete the baseinfo file? To be honest I don't know. Imho it should not delete the file.

**Comment by larshp** [comment]
well, we define the functionality

if the file is hidden/ignored in the overview I'd expect it not to show up when doing the commit. If it does not show up during the commit, then there is a chance that the new commit and the ignored file will not match

In my opinion its better to keep the functionallity as is, the developer is notified what files that do not match, the developer must decide what to do.

Off topic:
* CI should catch when the baseinfo and ddls do not match, but we do not have the tools for this scenario in the ABAP ecosystem currently
* I do not know/see the need for the baseinfo file, but I've also done limited CDS

**Comment by christianguenter2** [comment]
Ok, closing. I'll keep the branch for reference.

**Pull request closed without merging**
