### PR TITLE
Diff/Patch: Add Jump to file

### LINKED ISSUE #2890: Patch - jump to file
Frequently requested by colleagues - in the patch page, add a dropdown which shows all filtered files and allows you to scroll to that file when clicked.

As a workaround you can currently use ctrl+f, but this can cause significant lag due to the amount of elements on the page.

### PR DESCRIPTION
**Pull request by christianguenter2**
resolves #2890 

First try implementing jump for Diff/Patch page.
image

Maybe someday we can add a CTRL+P like file navigation.

### CODE REVIEW

**Comment by christianguenter2** [comment]
@FreHu Thanks for your feedback. I tried to address both of your concerns. Can you retry?

**Comment by FreHu** [comment]
Works perfectly. I got another idea and hacked together a floating menu, not sure where best to put it so it doesn't cover text.
image

**Comment by christianguenter2** [comment]
Nice idea! I also thought about fixing the header somehow. But then it would probably be fix everywhere in abapGit. Not sure whether we want that.

**Comment by FreHu** [comment]
Probably not, at least without testing (although diff for example is pretty much the same page). 
Maybe you could define the style in a class and toggle it on the correct pages.

**Comment by FreHu** [comment]
Or maybe just fix the buttons and not the `logo > diff`.

**Comment by FreHu** [comment]
Today I discovered this already has good keyboard navigation 
- click the jump link to focus
- select file with up, down arrows
- enter to jump. the jump list stays open
- home to go back to jump list

Disadvantages
- you can't scroll with arrow keys if the jump list is focused
- sometimes the focus gets messed up when you click something else and trying to refocus the jump list is a bit annoying

**Comment by christianguenter2** [comment]
> enter to jump. the jump list stays open

Hm, enter doesn't work for me but spacebar does.

**Comment by FreHu** [comment]
Maybe ctrl+p could work instead of the floating menu. Maybe merge it and see how things evolve? My colleagues like it as it is already.

**Comment by sbcgua** [comment]
+1 for merge. The feature is good and useful. Ctrl+p is not yet finalized anyway.

2 minor comments:
- I'd rename Jump to something else (Jump to file, or better Go to file ?) because Jump itself is confusing imho
- after file is selected the jump list scrolls away - its a potential stop for future improvements. Options are: keyboard shortcut or header that follows scrolling or some kind of hanging button at the corner. Or combination.

**Pull request merged**
