### PR TITLE
Hide "Action" column when toggling "Details"

### PR DESCRIPTION
**Pull request by mbtools**
Turning on "Details" in Repo Overview will now hide the "Action" column to improve display on smaller screens.

### CODE REVIEW

**Review by sbcgua — APPROVED** [review]
Looks good, ok for me
image

**Comment by sbcgua** [comment]
P.S. hmmm, does anyone use detail view ... ?

**Comment by larshp** [comment]
I think the detail view is the only place to see the last deserilaization and who created the repo

**Comment by sbcgua** [comment]
Ah, yes, you're right. Settings and/or some kind of info icon at repo head with a large info tooltip maybe ... yeah, anyway a separate feature :)

**Review by larshp — APPROVED** [review]

**Pull request merged**
