### PR TITLE
Fixes #1229: Enable SAP GUI for Java settings

### LINKED ISSUE #1229: Settings flags always on in SAP GUI for Java
Hello,

I'm currently using abapGit in SAP GUI for Java environment and whenever I make a change to settings, I noticed that the 'Proxy authentication' flag is always persisted as true, regardless of what I selected. Other flags, like 'Enable jump to ADT first', etc, all behave similar to Proxy authentication.

Steps to reproduce:

1. Execute ZABAPGIT.
2. Go to 'Advanced' and 'Settings'.
3. Try to set 'Proxy Authentication' to false.
4. Save.
5. Open the Settings page again.
6. Proxy authentication will be set to 'true'.

abapGit version: v1.50.1
SAP GUI for Javaversion: tested in 7.50 rev 0.3 and 7.40 rev 9
Operating system: Red Hat 7.4 

I don't know if it's a Red Hat specific issue. Perhaps someone could test it on Mac or even Windows.

### PR DESCRIPTION
**Pull request by EduardoCopat**
See #1229

### CODE REVIEW

**Comment by jfilak** [comment]
We need the second commit for the staging area too, right? I had no time to debug it yet, but whenever I try to commit sub-set of changed files in Java GUI I get the error "no files selected" :)

**Comment by EduardoCopat** [comment]
@jfilak Let me do some further testing then.

**Comment by larshp** [comment]
yeah, I guess this can be merged, it is one step in the right direction 👍

**Comment by EduardoCopat** [comment]
@jfilak #1866

**Pull request merged**
