### PR TITLE
Method descriptions - Issue #431

### PR DESCRIPTION
**Pull request by EduardoCopat**

### CODE REVIEW

**Comment by EduardoCopat** [comment]
I wonder if this CLAS object has too many responsibilities. Should it be split in two: INTF and CLAS ?

There are already many conditionals (ifs) for class or interface bevahior

**Comment by EduardoCopat** [comment]
Something is strange with my commit. It is deleting a method which I'm not.

**Comment by larshp** [comment]
yea, it should be split up, see https://github.com/larshp/abapGit/issues/21

**Comment by larshp** [comment]
the methods table(type = `seoo_methods_r`) contains a lot of data. It would be cool if a method can be added in the ABAP code, and the XML will not need to be updated. Currently it looks like a lot of the ABAP code will be replicated in the xml(eg. method parameters)

**Pull request closed without merging**
