### PR TITLE
Solve issue - Error determining the main package #2547

### PR DESCRIPTION
**Pull request by LMachado**
Sorry, i am noob in this caind of thing xD.
Now i balive right branch right now. hehe.
Thank you.

relate with:
#2548
#2551

### CODE REVIEW

**Comment by larshp** [comment]
yeah, looks good now, can you add a bit more description about the problem and how its solved? as text here

**Comment by LMachado** [comment]
Hello we have some problems determining the right path on zip constrocation.

For instance in our case, we have 3 packages:

ZFI-CA in
ZFI in
ZHOME is the root package

we got this path:  src/zfi-ca/zfi-ca_gen/zpx,
the right one is: src/zfi/zfi-ca/zfi-ca_gen/zpx.

The root problem is in the method find_top_package of class zcl_abapgit_transport.
Where is determinant the top package, used to in method zip. Pass this on creation of new instance of class zcl_abapgit_repo_offline.



the internal table have this information:

line 1 - ZFI-CA
line 2 - ZFI
line 3 - ZHOME

after sort
line 1- ZFI
line 2 - ZFI-CA
line 3 - ZHOME

To get the root package he need to read the last position of internal table.

**Comment by larshp** [comment]
What if the top package was called ZAA? then it would be the in the first position after sort?

**Comment by LMachado** [comment]
> What if the top package was called ZAA? then it would be the in the first position after sort?

yap, but if you have a subpackage - ZA in ZAA, this will return ZA.

Imagine you have a box with lable A in a box lable B in a box lable C.
the maim box will be C, but if you sort the boxs by the lable, the main box is A, and is is not true.

**Comment by larshp** [comment]
Actually I guess this is okay, merging

👍 

welcome to abapGit as a contributor 🎉

**Pull request merged**
