### PR TITLE
Login UX #303

### PR DESCRIPTION
**Pull request by sbcgua**
#303

### CODE REVIEW

**Comment by sbcgua** [comment]
abaplint: seems some keyword are missing. 
For bad indentation: can shift `BEGIN OF LINE` left, but I'd say this way looks clearer.

**Comment by larshp** [comment]
I agree that it looks better, but some day someone will pretty print the include and the indentation will be gone. We are limited by the tools that SAP provides :disappointed: can you add a commit where the include is pretty printed?

Apart from that I tested it a bit, and it looks good

**Comment by larshp** [comment]
cool, thanks, merging

**Comment by sbcgua** [comment]
BTW there is a possibility to enhance pretty printer.
http://www.hovitaga.com/Advanced-Pretty-Printer-enhancement-details
I didn't install this one honestly but it looks very interesting ... maybe I'll do when I have some time.

**Comment by larshp** [comment]
yes, I've seen it, and debugged the standard pretty printer code without finding a user exit. So I guess the advanced pretty printer is implemented via a modification or implicit enhancement spot.

**Pull request merged**
