### PR TITLE
Started to implement BRF+ serialization

### PR DESCRIPTION
**Pull request by SaschaWaechter**
https://github.com/larshp/abapGit/issues/33

Started to implement BRF+ serialization for System objects in BRF+. Worked for some little test projects. Feel free to improve.

### CODE REVIEW

**Comment by christianguenter2** [comment]
Can you provide a test repo here?
https://github.com/abapGit-tests/FDT0

**Comment by christianguenter2** [comment]
@SaschaWaechter can you fix the abapLint errors?

**Comment by larshp** [comment]
@SaschaWaechter

**Comment by larshp** [comment]
closing, feel free to reopen when lint errors are fixed and the branch is rebased

**Pull request closed without merging**
