### PR TITLE
Update guide-install.md

### PR DESCRIPTION
**Pull request by AlexandreHT**
Hello, 
I took the opportunity a a fresh abapGit install to update installation procedure. I only use offline import so I may have misunderstood some part of the online install.
BR, 
Alexandre

### CODE REVIEW

**Comment by mbtools** [comment]
Hi Alexandre,

we appreciate you suggestions and I agree, there's some clarification necessary. For the installation, it's not really about "online" vs "offline".  

There are two versions of abapGit: 
- A developer version
- A consumer version (I guess, I just invented this name, so not sure if others agree calling it this way)

The consumer version contains the same features as the developer version but all compiled into a single - very large - ABAP program. This consumer version is sometimes referred to as "merged version" or "full version" of abapGit. This makes the initial installation very easy (cut & paste or upload).

Either version can be installed whether your SAP system is connected to the Internet or not. And either version will be able to work with online or offline repositories. 

The recommended way is to install and use the consumer version. If you want to contribute to the abapGit project, then we recommend to you use the consumer version in order to install the developer version (by adding it as an online repository). 

Hope that helps,
Marc

PS: In case your system is not connected to the Internet, you can install the developer version also by adding it as an offline repository. But this is rather an exceptional case which obviously won't be able to interact with the Github repository.

**Comment by AlexandreHT** [comment]
Hi Marc, 
Interesting. As a matter of fact, when using consumer version I got at some point an erreur message asking me to install abapgit
That why I deduced that ZABAPGIT_FULL was an installer and needed the full project. SAPlink worked that way after all.

I may have misunderstood the error message.

If the project agree on a common naming for developper/consumer version, please let met know and I'll rephrase the doc page.

Alexandre

**Comment by sbcgua** [comment]
> That why I deduced that ZABAPGIT_FULL was an installer and needed the full project

Hmm, maybe it would be clearer to rename it to ZABAPGIT_MERGED (or something) ? Indeed, `full` is misleading...

Just a side note.

**Comment by larshp** [comment]
thanks, merging

welcome to abapGit as a contributor 🎉

**Comment by AlexandreHT** [comment]
Thanks!
I got time to rethink about what I clumsily called _online_ and _offline_ install. What would you think of calling it _standalone_ and _developper_ (as suggested by @mbtools) version? 

If so, it might be interesting to rename report `ZABAPGIT_FULL` to `ZABAPGIT_STANDALONE`.

What do you think?
Alexandre

**Comment by larshp** [comment]
yea, feel free to open more pull requests with additional changes

**Pull request merged**
