### PR TITLE
Finetunings in repo_head UI and html_helper

### PR DESCRIPTION
**Pull request by sbcgua**
Better placement of repo_head elements: package displayed most right both for on/offline, url shown just after repo name and without text-overflow cut
html_helper not indents style content in curly brackets

### CODE REVIEW

**Comment by sbcgua** [comment]
image

**Comment by sbcgua** [comment]
abaplint seems to dislike `IGNORING CASE` :)

**Comment by larshp** [comment]
yeah, it is full of bugs :) will fix

https://larshp.github.io/abaplint/viz/find.svg

**Comment by larshp** [comment]
thanks :+1:

**Pull request merged**
