### PR TITLE
Patch: new refresh functions

### PR DESCRIPTION
**Pull request by christianguenter2**
Three new refresh functions on the patch page.˙

1) Local refresh of single object 
2) Local refresh of all objects
3) Full refresh of all objects, local and remote
image

abapGit15

### CODE REVIEW

**Comment by FreHu** [comment]
Big thanks, I consider this a huge improvement to the committing experience. Some initial ones, I'll do some more thorough testing tomorrow:

- The jumping behavior is a bit confusing.
- I managed to get an error by trying to refresh `.abapgit.xml`.
image

**Comment by christianguenter2** [comment]
- Jumping: Yeah I'm not sure about that too. Otherwise it's also very annoying if the page jumps to the top after refreshing an object. 
- `Refresh object` depends currently on the object. As there is none for `.abapgit.xml` there error occurs. I disable `Refresh` for non object files. Will try to improve this further.

**Comment by FreHu** [comment]
After committing through patch, it would be interesting if abapgit had the option to go straight back to patch after committing, width updated diffs. What do you think about this?

**Comment by christianguenter2** [comment]
Good Idea, I think this should be possible. I'll investigate. 
I think that's then something for a follow up PR?

**Comment by FreHu** [comment]
Of course, split things up as you see fit.

**Comment by christianguenter2** [comment]
Yeah already working on it. Do you think we can merge this PR as is?

**Comment by FreHu** [comment]
- Currently refreshing jumps to the top, but does not jump back to the file. I think this is worse than jumping there and back, it's very easy to get lost.

fWQj46OO5b

- Deleting a file and then refreshing will lead to errors and a blank page:
image

From this state, doing refresh local will show a different error and refresh all will dump.

**Comment by christianguenter2** [comment]
- Ok, then I'll reenable jumping to the file.
- I'll check the deletion case

**Comment by christianguenter2** [comment]
@FreHu 
- jump to refreshed object enabled again
- refresh of deleted objects should work now
Can you check again?

**Comment by FreHu** [comment]
Confirmed working. But I found another dump when creating a new class, then doing refresh local.
image

**Comment by christianguenter2** [comment]
Thanks I'll check

**Comment by christianguenter2** [comment]
@FreHu fixed. Please try again.

**Comment by FreHu** [comment]
Works correctly now.

**Comment by christianguenter2** [comment]
I just added hotkey support for refresh all local objects, as I need that the most ;-) Now I'm done.

**Comment by christianguenter2** [comment]
Btw. using the hotkey jumping is much more smoother than when refreshing single objects

**Comment by FreHu** [comment]
I've never given hotkeys a chance, I'll try to give them a go.

**Comment by christianguenter2** [comment]
@larshp do you think we can merge this? I'd like to prepare a follow up PR :-)

**Comment by larshp** [comment]
hmm, there are changes to `src/zcl_abapgit_repo.clas.abap`, its the central point that needs most refactoring, adding additional methods makes it more difficult than it already is

**Comment by christianguenter2** [comment]
Hm, ok I see. Any idea how we can tackle this?

**Comment by sbcgua** [comment]
Imho. I'd propose to merge and then refactor separately. Repo needs refactoring for some time by now ... I've been proposing some idea before in #2216 - to separate repo as a container and local-remote "strategies".  

P.S. There is also #2664 hanging from my side :( can't get hands on it ... maybe soon.

**Pull request merged**
