### PR TITLE
bugfix #676

### LINKED ISSUE #676: transport to branch - not all files staged
Created new report in a transport, clicked "Transport to Branch", only the .abap file was pushed to the new branch, missing the .xml file

image

### PR DESCRIPTION
**Pull request by larshp**
fixes #676

### CODE REVIEW

**Comment by EduardoCopat** [comment]
I'm also working on this class. Putting some unit tests for the core functionality. 

To avoid merge requests, could you wait before merging? I can add your loop statement to my branch then.

**Comment by larshp** [comment]
looks like branch https://github.com/EduardoCopat/abapGit/tree/unit-test-transp2branch does not contain any commits

but if you add the loop in your branch we can close this PR, and move it to your branch instead

**Comment by EduardoCopat** [comment]
Yes, sorry, I didn't push yet.

Now I did, but it is work in progress...

**Comment by larshp** [comment]
to be moved to @EduardoCopat 's branch

**Pull request closed without merging**
