### PR TITLE
External files for css and js

### PR DESCRIPTION
**Pull request by sbcgua**
to #374 Main part of code
See also (but not a prerequisite for the moment): https://github.com/larshp/abapmerge/pull/16

- css/js removed from code, created as w3mi objects
- new `lcl_asset_manager` class created to extract the w3mi or fall back to inline resource which should be assembled by abapmerge (checked - works)
- `lcl_path` got back that path remover method (used now) + a small fix to w3mi serialization to hide original path to the file (for the privacy reasons)
- refactor of JS code - moved stage logic to a "class"

Seems this is it. There is some more work on css refactoring but I'll do it later - now the apprach works already so should be tested a bit and then finetuned.

### CODE REVIEW

**Comment by sbcgua** [comment]
P.S. assembled abapgit is 1.1Mb - wow :)

**Comment by sbcgua** [comment]
The last commit also centralizes images to `asset_manager`. So pages now are clean code.

**Comment by larshp** [comment]
time to write a ABAP minifier? :stuck_out_tongue_closed_eyes:

**Comment by larshp** [comment]
I get the following diff after pulling the code. Can we CONDENSE the filesize value, and perhaps CLEAR the version, so it is not in the XML?

image

**Comment by sbcgua** [comment]
Yeap, good idea.

**Comment by sbcgua** [comment]
Ah, forgot the version. Moment

**Comment by sbcgua** [comment]
SHould be ok now

**Comment by larshp** [comment]
lets do it :+1:

**Comment by larshp** [comment]
compiled version does not work:

image

**Comment by larshp** [comment]
fixed, updated package.json to use latest abapmerge version

**Pull request merged**
