### PR TITLE
Ignores deleted maintanence generated function groups

### LINKED ISSUE #1100: Table maintenance: Error from RS_GET_ALL_INCLUDES
I get the following error with a table maintenance dialog.
image

Steps to reproduce.
1) Create a repository with a db table and a table maintenance dialog.
2) Commit the changes 
3) Delete the table maintenance dialog with this options
image

4) Recreate the table maintenance dialog into the same function group as before
5) Refresh in abapGit

image

### PR DESCRIPTION
**Pull request by EduardoCopat**
Fixes #1100. See issue for more details.

I am not sure if this is the best approach for this problem, because it just ignores the function group (What happens if you delete the repository?)

### CODE REVIEW

**Comment by larshp** [comment]
@christianguenter2 can you help testing this PR?

**Comment by christianguenter2** [comment]
If I test the scenario described in the issue I still get the error 
image

**Comment by EduardoCopat** [comment]
Hi, @christianguenter2, could you please test again?

The scenario on this PR should be working. Also, I tested the scenarios described on the issue and they are working for me.

**Comment by larshp** [comment]
@christianguenter2 can you help testing?

**Comment by christianguenter2** [comment]
Doesn't work for me. I still get the error described in the issue.

**Comment by EduardoCopat** [comment]
I will close this PR for now, otherwise it will keep here for a long time. I need lost my sandbox system and I need to reconfigure it.

I will create another PR if I see I can fix the issue.

**Pull request closed without merging**
