### PR TITLE
Dynamically accessing fields which still don't exist in version 702

### PR DESCRIPTION
**Pull request by nununo**
Hello,

Please review it and please test it. 
Although I tried to be thoroughly careful, I couldn't test it since I'm not using any web dynpro objects in my repositories.
Also, feel free to review my coding style to align it with the project style.

Thanks,
Nuno

### CODE REVIEW

**Comment by larshp** [comment]
Thanks, looks good, I'll fix the error in abaplint

**Comment by nununo** [comment]
What exactly is the error abaplint is reporting? I didn't understand.

**Comment by larshp** [comment]
parser error, it does not understand the following statement, however it should as it is valid abap, fixed in a bit, will release new abaplint version

```abap
    CALL FUNCTION 'WDYC_GET_OBJECT'
      PARAMETER-TABLE
      lt_fm_param
      EXCEPTION-TABLE
      lt_fm_exception.
```

**Comment by nununo** [comment]
Ah!  I get it now. Thanks.

**Comment by larshp** [comment]
fixed, https://larshp.github.io/abaplint/viz/callfunction.svg , travis buid restarted manually

**Comment by nununo** [comment]
;)

Please make sure to test it with a real web dynpro to avoid any unwelcome regressions!
I couldn't test it in this system.

**Comment by larshp** [comment]
overwriting of protected field fixed in: https://github.com/larshp/abapGit/commit/4acf442e3c7c36164c300722f5cb13e1ea9c8608

**Comment by nununo** [comment]
Ah... ops... it had to be CHANGING... thanks for correcting it.

**Comment by nununo** [comment]
Unfortunately there is still an issue: when you introduce a CHANGING parameter... the RETURNING is no longer valid. I'll correct it and do a pull request asap.

**Pull request merged**
