### PR TITLE
Doc styling part1

### PR DESCRIPTION
**Pull request by sbcgua**
to #763, #764 

some initial tweaks, will do some later (maybe next weekend).

image

- added favicon
- added simle footer (no idea what else to put there :)
- some stuff with layouts
- image autosize

Thoughs:
- issue with logo. It is actually readable. But for human not for robots (search engines). So without "abapGit" text in header the site was named "documentation". On the other hand for a human it is now named "abapGit abapGit documentation". Not sure what to do with that for the moment. Any ideas ?
- It looks possible to build toc dynamically based on existing pages instead of manual YML. But that would probably mean giving up with 3 levels of nav (which are also look crouded imho). What if we combine online and offline docs in one page (1 online + 1 offline) ?
- I'd probably move MDs to some dir
- I'd probably move css to sass

P.S. jekyll is clunky for Win ... or I didn't get it right yet ...

P.P.S: https://github.com/facebook/react/tree/master/docs rules :)

### CODE REVIEW

**Comment by larshp** [comment]
I've tested Jekyll on c9.io, so I dont have to setup windows stuff(using the free tier)

looks good, thanks

**Comment by larshp** [comment]
logo issue: suggest removing the black/image "abapGit" and just have the git logo in the header

toc dynamic: I would like to control the sequence of the toc, not sure if this can be done dynamically

off + online: we could move them 1 level up, so they are top level like "Guide" and "Reference"

**Comment by sbcgua** [comment]
logo: then it will be git logo ! Another option is to put svg favicon there.

dynamic toc: not insisting. But the idea is: put category to page head (when published). Then [groub_by](https://jekyllrb.com/tutorials/navigation/#scenario-7-retrieving-items-based-on-front-matter-properties) docs by category. _data should contain YML to order categories (they are not added that frequently). So the sequence of groups will be predictable. And the seq of docs inside a group can be alphabetic.

combine on/offline: yes, 3 levels look cluttered. Level up would be OK. Or joining

**Comment by larshp** [comment]
group_by: looks cool, just need to be able to control the order, like in the linked example

perhaps a toc like this:

* abapGit
  * Installation
  * Upgrading
  * Uninstalling

* Online projects
  * Installing a repository
  * Keeping code up to date
  * Uninstalling a repository
  * Your first abapGit project
  * Moving package into git
  * Contributing to a project

* Offline projects
  * Importing zip
  * Exporting zip

* Reference
  * .abapgit.xml
  * Write protect
  * Supported object types

* Other
  * Articles and Presentations
  * ZABAPGIT_TEST_SSL
  * XML mismatch
  * Object File Formats
  * Technical Links
  * Regular backup
  * Migrating from SAPlink

**Comment by sbcgua** [comment]
Perhaps "getting started" instead of  "abapGit". But yeah this structure looks good. 
Will have a look when I have time - maybe still possible to make it dynamic.

**Pull request merged**
